### ISSUE TITLE
Testing dev branch on Langley

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#100]
First script died about halfway in:
```console
art@Langley:/home/covid/covizu/data$ grep -c ">" gisaid-filtered.fa 
38670

art@Langley:/home/covid/covizu$ python3 scripts/filtering.py 

Traceback (most recent call last):
  File "scripts/filtering.py", line 119, in <module>
    trim_right=args.trim_right, max_prop_n=args.maxpropN, minlen=args.minlen
  File "scripts/filtering.py", line 51, in filter_gisaid
    if len(s) < minlen:
TypeError: object of type 'int' has no len()
```

**Comment by ArtPoon** [comment]
Database corrupted, bad entry:
```
art@Langley:/home/covid/covizu$ python3 scripts/filtering.py   # write '{} {}'.format(h, s)
hCoV-19/Iran/PNZL/2020|EPI_ISL_467692|2020-03-10 0
```

**Comment by ArtPoon** [comment]
```console
art@Langley:/home/covid/covizu/data$ sqlite3
SQLite version 3.11.0 2016-02-15 17:29:24
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .open gsaid.db 
sqlite> select * from sequences where header="hCoV-19/Iran/PNZL/2020|EPI_ISL_467692|2020-03-10";
EPI_ISL_467692|hCoV-19/Iran/PNZL/2020|EPI_ISL_467692|2020-03-10|-3513791184953504122|0
sqlite> select * from sequences where header="hCoV-19/Germany/NRW-21/2020|EPI_ISL_419538|2020-03-14";
EPI_ISL_419538|hCoV-19/Germany/NRW-21/2020|EPI_ISL_419538|2020-03-14|9038704090342397998|??????????????????????????????????????????????????????AGATCTG...
```

**Comment by ArtPoon** [comment]
Ok this record has length 883 nt on GISAID, so the database script is not bothering to attempt aligning this sequence - but a record is still created in the local database.  @ewong347

**Comment by ArtPoon** [comment]
Added this to `filtering.py`:
```python
    for h, s in get_aligned(database):
        if not type(h)==str or not type(s)==str:
            print("Error: entry {} not string type: sequence {}".format(h, s))
            continue
```

```console
art@Langley:/home/covid/covizu$ python3 scripts/filtering.py 
Error: entry hCoV-19/Iran/PNZL/2020|EPI_ISL_467692|2020-03-10 not string type: sequence 0
Error: entry hCoV-19/Iran/PN-MKH/2020|EPI_ISL_467681|2020-03-10 not string type: sequence 0
Error: entry hCoV-19/Iran/PN-2130/2020|EPI_ISL_467670|2020-03-10 not string type: sequence 0
Error: entry hCoV-19/Iran/23/2020|EPI_ISL_450224|2020-03-31 not string type: sequence 0
Error: entry hCoV-19/Iran/PN-2142-S/2020|EPI_ISL_467672|2020-03-10 not string type: sequence 0
Error: entry hCoV-19/Iran/PNHJ/2020|EPI_ISL_467690|2020-03-10 not string type: sequence 0
Error: entry hCoV-19/Iran/PN-2062/2020|EPI_ISL_467680|2020-03-10 not string type: sequence 0
Error: entry hCoV-19/Iran/PN-2161/2020|EPI_ISL_467673|2020-03-10 not string type: sequence 0
Error: entry hCoV-19/Iran/18/2020|EPI_ISL_450219|2020-03-31 not string type: sequence 0
Error: entry hCoV-19/Iran/27/2020|EPI_ISL_450228|2020-03-31 not string type: sequence 0
Error: entry hCoV-19/Iran/26/2020|EPI_ISL_450227|2020-03-31 not string type: sequence 0
Error: entry hCoV-19/Indonesia/MRINUPH_01-461/2020|EPI_ISL_438547|2020-03 not string type: sequence 0
Discarded 155 non-human sequences.
Discarded 4466 problematic sequences with prop N > 0.05.
Discarded 0 sequences of length < 29000
Discarded 0 sequences with duplicate accession numbers
Discarded 1372 sequences with mangled headers / ambiguous sample dates
```

**Comment by ewong347** [comment]
Oops - I forgot to fix both of these issues while tinkering with the script.

Expected (live) behavior is:
```
aligner returns 0 if the sequence was <5000, 
database inserter to skip the entry if the aligned sequence ==0. 
```

I've gone back and cleaned out where sequences =0 and the stripped sequence <5000. This was on my to do list, but it slipped by mind.

**Comment by ewong347** [comment]
```
ewong347@Langley:/home/covid/covizu$ grep -c '>' data/gisaid-aligned.fa
54884
ewong347@Langley:/home/covid/covizu$ python3 scripts/filtering.py 

Discarded 134 non-human sequences.
Discarded 3903 problematic sequences with prop N > 0.05.
Discarded 0 sequences of length < 29000
Discarded 0 sequences with duplicate accession numbers
Discarded 1371 sequences with mangled headers / ambiguous sample dates
```

**Comment by ArtPoon** [comment]
Uh why did you run that script again?  I'm already in the middle of a TN93 run on that file!

**Comment by ewong347** [comment]
oh crap! I wanted to make sure that the changes I made worked. Does running the script again crash the tn93 run?

**Comment by ArtPoon** [comment]
Eh I think it's ok - the fasta file was loaded into memory on initializing the TN93 run.  :-)

**Comment by ArtPoon** [comment]
```console
art@Langley:/home/covid/covizu$ tn93 -t 0.00005 -o data/gisaid.tn93.csv data/gisaid-filtered.fa
Read 52230 sequences of length 29757
Will perform 1363960335 pairwise distance calculations
Progress:    10.9% ( 1908729 links found,     2.62e+05 evals/sec)
Progress:    69.3% (12259958 links found,     2.54e+05 evals/sec)
Progress:    73.2% (12917817 links found,     2.52e+05 evals/sec)
Progress:    76.4% (13484648 links found,      2.5e+05 evals/sec)
Progress:      81% (14258576 links found,     2.47e+05 evals/sec)
Progress:    86.3% (15184192 links found,      2.4e+05 evals/sec)
Progress:    92.5% (16446811 links found,     2.29e+05 evals/sec)
Progress:     100% (18015883 links found,     1.92e+05 evals/sec)
{
	"Actual comparisons performed" :1363960335,
	"Comparisons accounting for copy numbers " :1.36396e+09,
	"Total comparisons possible" : 1363960335,
	"Links found" : 18024596,
	"Maximum distance" : 0.0127598,
	"Sequences" : 52230,
	"Mean distance" : 0.000344141
```

Limiting output to `0.00005` is still generating over two gigabytes: 
```console
art@Langley:/home/covid/covizu$ ls -lth data/gisaid.tn93.csv 
-rw-rw-r-- 1 art covid 2.2G Jul 10 15:05 data/gisaid.tn93.csv
```

**Comment by ArtPoon** [comment]
```console
art@Langley:/home/covid/covizu$ python3 scripts/variants.py
importing TN93 distances
built graph with 35382 nodes
Modularity clustering...

  partitioning component of size 18878 into 278 communities
  partitioning component of size 50 into 3 communities
  partitioning component of size 576 into 8 communities
  partitioning component of size 51 into 3 communities
  partitioning component of size 28 into 3 communities
  partitioning component of size 21 into 3 communities
  partitioning component of size 65 into 3 communities
  partitioning component of size 14 into 3 communities
  partitioning component of size 39 into 2 communities
  partitioning component of size 11 into 2 communities
  partitioning component of size 23 into 2 communities
  partitioning component of size 19 into 3 communities
Partitioned graph from 3966 to 4267 components
art@Langley:/home/covid/covizu$ grep -c ">" data/variants.fa
19699
```

**Comment by ArtPoon** [comment]
Problem in `hclust.R`:
```console
art@Langley:/home/covid/covizu$ Rscript scripts/hclust.R
Loading required package: igraph
Loading required package: methods

Attaching package: ‘igraph’

The following objects are masked from ‘package:stats’:

    decompose, spectrum

The following object is masked from ‘package:base’:

    union

Loading required package: jsonlite
Loading required package: Rtsne
loading TN93 distance matrix
hierarchical clustering
Read the 19699 x 19699 data matrix successfully!
OpenMP is working. 1 threads.
Using no_dims = 2, perplexity = 30.000000, and theta = 0.500000
Computing input similarities...
Building tree...
 - point 10000 of 19699
Done in 177.49 seconds (sparsity = 0.008035)!
Learning embedding...
Iteration 50: error is 102.270982 (50 iterations in 17.29 seconds)
Iteration 100: error is 101.040628 (50 iterations in 10.81 seconds)
Iteration 150: error is 84.994141 (50 iterations in 4.21 seconds)
Iteration 200: error is 81.144778 (50 iterations in 4.11 seconds)
Iteration 250: error is 79.585123 (50 iterations in 4.22 seconds)
Iteration 300: error is 3.316303 (50 iterations in 3.84 seconds)
Iteration 350: error is 2.942900 (50 iterations in 3.80 seconds)
Iteration 400: error is 2.703894 (50 iterations in 3.81 seconds)
Iteration 450: error is 2.536218 (50 iterations in 3.79 seconds)
Iteration 500: error is 2.409433 (50 iterations in 3.76 seconds)
Iteration 550: error is 2.309696 (50 iterations in 3.84 seconds)
Iteration 600: error is 2.229238 (50 iterations in 3.72 seconds)
Iteration 650: error is 2.162424 (50 iterations in 3.77 seconds)
Iteration 700: error is 2.105685 (50 iterations in 3.77 seconds)
Iteration 750: error is 2.058243 (50 iterations in 3.76 seconds)
Iteration 800: error is 2.017149 (50 iterations in 3.76 seconds)
Iteration 850: error is 1.982527 (50 iterations in 3.82 seconds)
Iteration 900: error is 1.951729 (50 iterations in 3.77 seconds)
Iteration 950: error is 1.924949 (50 iterations in 3.78 seconds)
Iteration 1000: error is 1.903306 (50 iterations in 3.77 seconds)
Fitting performed in 97.40 seconds.
Error: all(is.element(variants$cluster, headers)) is not TRUE
Execution halted
```

```R
> headers <- rep(NA, times=nrow(tn93))
> con <- file('data/variants.fa', open='r')
> i <- 1
> while (length(line <- readLines(con, n=1, warn=FALSE)) > 0) {
+   if (grepl("^>", line)) {
+     headers[i] <- gsub("^>(.+)", "\\1", line)
+     i <- i + 1
+   }
+ }

> close(con)
> length(headers)
[1] 19699
> variants <- read.csv('data/variants.csv')
> length(unique(variants$cluster))
[1] 19974
> table(!is.element(variants$cluster, headers))

FALSE  TRUE 
50127   962
```

**Comment by ArtPoon** [comment]
Looks like this is due to `gisaid-filtered.fa` being replaced during analysis..

**Comment by ArtPoon** [comment]
Re-running pipeline from the start *sigh*.  I'm worried that this filtering step seems a bit stochastic:
```console
art@Langley:/home/covid/covizu$ bash covizu.sh 
Discarded 134 non-human sequences.
Discarded 3911 problematic sequences with prop N > 0.05.
Discarded 0 sequences of length < 29000
Discarded 0 sequences with duplicate accession numbers
Discarded 1386 sequences with mangled headers / ambiguous sample dates
Read 49658 sequences of length 29757
```

**Comment by ArtPoon** [comment]
Maybe we should create subfolders under `data/` for each run so that we don't have collisions like this in the future.
