### ISSUE TITLE
CalledProcessError: subprocess to rapidnj throws signal 6

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#124]
```console
art@orolo:~/git/covizu$ python3 scripts/clustering.py data/gisaid-human.json 
loading lineage classifications from database
loading JSON
dropped 17571 records with uncalled bases in excess of 600
filtered 12999 problematic features
391
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 387) >= this->size() (which is 387)
Traceback (most recent call last):
  File "scripts/clustering.py", line 196, in <module>
    nwk_str = rapidnj(lfeatures)
  File "scripts/clustering.py", line 170, in rapidnj
    nwk = subprocess.check_output(['rapidnj', outfile.name, '-i', 'pd'])
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['rapidnj', '/tmp/tmp3tfio_jx', '-i', 'pd']' died with <Signals.SIGABRT: 6>.
```

Direct execution on command line was fine:
```console
art@orolo:~/git/covizu$ rapidnj /tmp/tmp3tfio_jx -i pd
('hCoV-19/Oman/RESP-20-2181/2020|EPI_ISL_457939|2020-03-17':0,(((((((((((((('hCoV-19/Sweden/20-04736/2020|EPI_ISL_475544|2020-02-26':3,'hCoV-19/Shandong/IVDC-SD-001/2020|EPI_ISL_408482|2020-01-19':3):8
```

**Comment by ArtPoon** [comment]
Had to close the temporary file handle before calling rapidnj
