### ISSUE TITLE
rapidNJ crashed

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#125]
Seems like most jobs, if not all jobs were successful:
```console
art@orolo:~/git/covizu$ python3 scripts/clustering.py data/gisaid-human.json 
loading lineage classifications from database
loading JSON
dropped 17571 records with uncalled bases in excess of 600
filtered 12999 problematic features
Traceback (most recent call last):
  File "scripts/clustering.py", line 207, in <module>
    nwk_str = rapidnj(lfeatures)
  File "scripts/clustering.py", line 180, in rapidnj
    stdout = subprocess.check_output(cmd, stderr=subprocess.DEVNULL)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['rapidnj', '/tmp/tmp7vnsh619', '-i', 'pd', '--no-negative-length']' returned non-zero exit status 1.
art@orolo:~/git/covizu$ ls -lt *.nwk
-rw-rw-r-- 1 art art     133 Sep  3 18:49 B.22.nwk
-rw-rw-r-- 1 art art    1681 Sep  3 18:49 B.1.90.nwk
-rw-rw-r-- 1 art art    7427 Sep  3 18:49 B.1.1.30.nwk
-rw-rw-r-- 1 art art     788 Sep  3 18:49 B.1.1.13.nwk
-rw-rw-r-- 1 art art   10089 Sep  3 18:49 B.1.1.26.nwk
-rw-rw-r-- 1 art art    2956 Sep  3 18:49 B.1.5.10.nwk
-rw-rw-r-- 1 art art    3204 Sep  3 18:49 B.1.1.14.nwk
-rw-rw-r-- 1 art art     827 Sep  3 18:49 B.1.94.nwk
-rw-rw-r-- 1 art art     819 Sep  3 18:49 B.1.109.nwk
-rw-rw-r-- 1 art art    1815 Sep  3 18:49 B.1.1.15.nwk
-rw-rw-r-- 1 art art     438 Sep  3 18:49 B.1.87.nwk
-rw-rw-r-- 1 art art    6917 Sep  3 18:49 B.1.124.nwk
-rw-rw-r-- 1 art art     578 Sep  3 18:49 B.1.1.21.nwk
-rw-rw-r-- 1 art art    4038 Sep  3 18:49 B.1.121.nwk
-rw-rw-r-- 1 art art    1692 Sep  3 18:49 B.20.nwk
-rw-rw-r-- 1 art art    2721 Sep  3 18:49 B.14.nwk
-rw-rw-r-- 1 art art    1150 Sep  3 18:49 B.13.nwk
-rw-rw-r-- 1 art art    1522 Sep  3 18:49 B.19.nwk
-rw-rw-r-- 1 art art    4559 Sep  3 18:49 B.1.112.nwk
-rw-rw-r-- 1 art art    5158 Sep  3 18:49 B.1.1.3.nwk
-rw-rw-r-- 1 art art    1280 Sep  3 18:49 B.1.118.nwk
-rw-rw-r-- 1 art art    3848 Sep  3 18:49 B.1.107.nwk
-rw-rw-r-- 1 art art     732 Sep  3 18:49 B.17.nwk
-rw-rw-r-- 1 art art    7867 Sep  3 18:49 B.1.80.nwk
-rw-rw-r-- 1 art art    4884 Sep  3 18:49 B.1.68.nwk
-rw-rw-r-- 1 art art     377 Sep  3 18:49 A.1.3.nwk
-rw-rw-r-- 1 art art   32284 Sep  3 18:49 B.1.113.nwk
-rw-rw-r-- 1 art art    1668 Sep  3 18:49 B.1.5.8.nwk
-rw-rw-r-- 1 art art    4222 Sep  3 18:49 B.1.39.nwk
-rw-rw-r-- 1 art art     247 Sep  3 18:49 B.1.1.19.nwk
-rw-rw-r-- 1 art art    1188 Sep  3 18:49 B.1.32.nwk
-rw-rw-r-- 1 art art    4867 Sep  3 18:49 B.1.79.nwk
-rw-rw-r-- 1 art art    3499 Sep  3 18:49 B.1.106.nwk
-rw-rw-r-- 1 art art    2061 Sep  3 18:49 B.1.97.nwk
-rw-rw-r-- 1 art art    2335 Sep  3 18:49 B.1.83.nwk
-rw-rw-r-- 1 art art    5713 Sep  3 18:49 B.1.110.nwk
-rw-rw-r-- 1 art art    4926 Sep  3 18:49 B.1.120.nwk
-rw-rw-r-- 1 art art    1866 Sep  3 18:49 B.1.19.nwk
-rw-rw-r-- 1 art art    5351 Sep  3 18:49 B.1.5.2.nwk
-rw-rw-r-- 1 art art    3223 Sep  3 18:49 B.1.78.nwk
-rw-rw-r-- 1 art art   17364 Sep  3 18:49 B.1.22.nwk
-rw-rw-r-- 1 art art    3491 Sep  3 18:49 B.1.96.nwk
-rw-rw-r-- 1 art art    2305 Sep  3 18:49 B.1.29.nwk
-rw-rw-r-- 1 art art     956 Sep  3 18:49 B.1.98.nwk
-rw-rw-r-- 1 art art     834 Sep  3 18:49 B.1.84.nwk
-rw-rw-r-- 1 art art    1667 Sep  3 18:49 B.1.70.nwk
-rw-rw-r-- 1 art art    1261 Sep  3 18:49 B.1.31.nwk
-rw-rw-r-- 1 art art    4197 Sep  3 18:49 B.1.1.28.nwk
-rw-rw-r-- 1 art art     752 Sep  3 18:49 B.1.25.nwk
-rw-rw-r-- 1 art art    5755 Sep  3 18:49 B.1.23.nwk
-rw-rw-r-- 1 art art    2014 Sep  3 18:49 B.2.9.nwk
-rw-rw-r-- 1 art art     952 Sep  3 18:49 B.1.67.nwk
-rw-rw-r-- 1 art art    4245 Sep  3 18:49 B.1.111.nwk
-rw-rw-r-- 1 art art    1461 Sep  3 18:49 B.1.123.nwk
-rw-rw-r-- 1 art art    2297 Sep  3 18:49 B.1.40.nwk
-rw-rw-r-- 1 art art    2057 Sep  3 18:49 B.1.5.6.nwk
-rw-rw-r-- 1 art art    2176 Sep  3 18:49 B.1.71.nwk
-rw-rw-r-- 1 art art   42108 Sep  3 18:49 B.1.93.nwk
-rw-rw-r-- 1 art art    1521 Sep  3 18:49 B.1.1.12.nwk
-rw-rw-r-- 1 art art    4336 Sep  3 18:49 B.1.89.nwk
-rw-rw-r-- 1 art art    8057 Sep  3 18:49 B.1.42.nwk
-rw-rw-r-- 1 art art    6466 Sep  3 18:49 B.1.77.nwk
-rw-rw-r-- 1 art art    2109 Sep  3 18:49 B.1.66.nwk
-rw-rw-r-- 1 art art     697 Sep  3 18:49 B.1.122.nwk
-rw-rw-r-- 1 art art   20444 Sep  3 18:49 B.1.1.2.nwk
-rw-rw-r-- 1 art art   14216 Sep  3 18:49 B.1.5.9.nwk
-rw-rw-r-- 1 art art    4980 Sep  3 18:49 B.1.44.nwk
-rw-rw-r-- 1 art art    7719 Sep  3 18:49 B.1.35.nwk
-rw-rw-r-- 1 art art    2321 Sep  3 18:49 B.1.108.nwk
-rw-rw-r-- 1 art art     638 Sep  3 18:49 A.1.1.nwk
-rw-rw-r-- 1 art art    1200 Sep  3 18:49 B.15.nwk
-rw-rw-r-- 1 art art    3812 Sep  3 18:49 B.1.76.nwk
-rw-rw-r-- 1 art art    4823 Sep  3 18:49 B.1.105.nwk
-rw-rw-r-- 1 art art    3072 Sep  3 18:49 B.1.1.6.nwk
-rw-rw-r-- 1 art art    1858 Sep  3 18:49 B.1.88.nwk
-rw-rw-r-- 1 art art    3067 Sep  3 18:49 B.1.1.5.nwk
-rw-rw-r-- 1 art art   15832 Sep  3 18:49 B.1.1.33.nwk
-rw-rw-r-- 1 art art    1774 Sep  3 18:49 B.1.114.nwk
-rw-rw-r-- 1 art art   10342 Sep  3 18:49 B.1.9.nwk
-rw-rw-r-- 1 art art    4411 Sep  3 18:49 B.1.30.nwk
-rw-rw-r-- 1 art art    9186 Sep  3 18:49 B.1.75.nwk
-rw-rw-r-- 1 art art    9164 Sep  3 18:49 B.1.1.7.nwk
-rw-rw-r-- 1 art art    9033 Sep  3 18:49 B.1.104.nwk
-rw-rw-r-- 1 art art   19638 Sep  3 18:49 B.1.1.10.nwk
-rw-rw-r-- 1 art art    4044 Sep  3 18:49 B.1.12.nwk
-rw-rw-r-- 1 art art    3667 Sep  3 18:49 B.1.99.nwk
-rw-rw-r-- 1 art art    1640 Sep  3 18:49 B.1.1.17.nwk
-rw-rw-r-- 1 art art    2703 Sep  3 18:49 B.2.7.nwk
-rw-rw-r-- 1 art art    3429 Sep  3 18:49 B.1.74.nwk
-rw-rw-r-- 1 art art    1251 Sep  3 18:49 B.1.69.nwk
-rw-rw-r-- 1 art art     307 Sep  3 18:49 B.18.nwk
-rw-rw-r-- 1 art art    6022 Sep  3 18:49 B.1.102.nwk
-rw-rw-r-- 1 art art    1597 Sep  3 18:49 B.1.38.nwk
-rw-rw-r-- 1 art art    6598 Sep  3 18:49 A.6.nwk
-rw-rw-r-- 1 art art    8738 Sep  3 18:49 B.2.4.nwk
-rw-rw-r-- 1 art art   13373 Sep  3 18:49 B.16.nwk
-rw-rw-r-- 1 art art   15299 Sep  3 18:49 B.1.8.nwk
-rw-rw-r-- 1 art art    2165 Sep  3 18:49 B.1.5.3.nwk
-rw-rw-r-- 1 art art    1334 Sep  3 18:49 B.5.nwk
-rw-rw-r-- 1 art art    2040 Sep  3 18:49 A.4.nwk
-rw-rw-r-- 1 art art    5532 Sep  3 18:49 B.10.nwk
-rw-rw-r-- 1 art art     861 Sep  3 18:49 B.1.34.nwk
-rw-rw-r-- 1 art art   39921 Sep  3 18:49 B.1.11.nwk
-rw-rw-r-- 1 art art    3127 Sep  3 18:49 B.9.nwk
-rw-rw-r-- 1 art art    4209 Sep  3 18:49 B.2.6.nwk
-rw-rw-r-- 1 art art   15748 Sep  3 18:49 B.1.43.nwk
-rw-rw-r-- 1 art art    2500 Sep  3 18:49 B.1.41.nwk
-rw-rw-r-- 1 art art  101180 Sep  3 18:49 B.1.2.nwk
-rw-rw-r-- 1 art art   38139 Sep  3 18:49 B.1.21.nwk
-rw-rw-r-- 1 art art   20079 Sep  3 18:49 A.5.nwk
-rw-rw-r-- 1 art art   11837 Sep  3 18:49 B.1.26.nwk
-rw-rw-r-- 1 art art   29302 Sep  3 18:49 B.1.3.nwk
-rw-rw-r-- 1 art art    2145 Sep  3 18:49 B.11.nwk
-rw-rw-r-- 1 art art    7267 Sep  3 18:49 B.2.10.nwk
-rw-rw-r-- 1 art art  163008 Sep  3 18:49 B.1.1.1.nwk
-rw-rw-r-- 1 art art    6347 Sep  3 18:49 B.1.1.4.nwk
-rw-rw-r-- 1 art art   17111 Sep  3 18:49 B.1.13.nwk
-rw-rw-r-- 1 art art    2957 Sep  3 18:49 B.21.nwk
-rw-rw-r-- 1 art art   76547 Sep  3 18:49 B.6.nwk
-rw-rw-r-- 1 art art    2188 Sep  3 18:48 B.1.6.nwk
-rw-rw-r-- 1 art art   17704 Sep  3 18:48 B.2.2.nwk
-rw-rw-r-- 1 art art   25350 Sep  3 18:48 A.3.nwk
-rw-rw-r-- 1 art art    2757 Sep  3 18:48 B.1.37.nwk
-rw-rw-r-- 1 art art   72663 Sep  3 18:48 A.2.nwk
-rw-rw-r-- 1 art art   55735 Sep  3 18:48 B.3.nwk
-rw-rw-r-- 1 art art  115647 Sep  3 18:48 B.2.1.nwk
-rw-rw-r-- 1 art art  166775 Sep  3 18:48 B.1.5.nwk
-rw-rw-r-- 1 art art   45764 Sep  3 18:48 B.1.36.nwk
-rw-rw-r-- 1 art art 1094400 Sep  3 18:48 B.1.1.nwk
-rw-rw-r-- 1 art art    1603 Sep  3 18:30 B.2.8.nwk
-rw-rw-r-- 1 art art 1213003 Sep  3 18:30 B.1.nwk
-rw-rw-r-- 1 art art  112682 Sep  3 18:07 B.2.nwk
-rw-rw-r-- 1 art art  145408 Sep  3 18:07 B.nwk
-rw-rw-r-- 1 art art   48964 Sep  3 18:07 A.nwk
-rw-rw-r-- 1 art art  136496 Sep  3 18:07 A.1.nwk
-rw-rw-r-- 1 art art   26874 Sep  3 18:06 B.4.nwk
```

**Comment by ArtPoon** [comment]
Temporary distance matrix of one sequence (1x1):
```console
art@orolo:~/git/covizu$ rapidnj /tmp/tmp7vnsh619 -i pd --no-negative-length
ERROR: an error occured while constructing the tree
art@orolo:~/git/covizu$ cat /tmp/tmp7vnsh619 
    1
hCoV-19/Japan/Donner17/2020|EPI_ISL_438961|2020-04-11  0
```
Need to screen for this edge case.
