### ISSUE TITLE
multithreading for bootstrap

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#130]
Right now the most time-consuming step is applying bootstrapped weights to features in the symmetric difference sets:
```python
    t0 = datetime.now()

    # allocate distance matrix
    dists = [[0 for _ in range(n)] for _ in range(n)]
    print('[{}] allocated dists'.format(datetime.now() - t0))

    for k in range(nboot):
        sample = [int(m*random.random()) for _ in range(m)]
        print('[{}] sampled integers'.format(datetime.now() - t0))

        weights = dict([(y, sample.count(y)) for y in set(sample)])
        print('[{}] calculated weights'.format(datetime.now() - t0))

        for i, j in sym_diffs:
            dists[j][i] = dists[i][j] = sum([
                weights.get(f, 0) for f in sym_diffs[(i, j)]
            ])
        print('[{}] applied weights'.format(datetime.now() - t0))

        yield dists
```

```console
art@orolo:~/git/covizu$ python3 scripts/clustering.py data/gisaid-human.2.json --nboot 10
loading lineage classifications from database
loading JSON
filtered 12522 problematic features
dropped 17598 records with uncalled bases in excess of 600
[0:00:02.162101] start B.1, 17381 entries
[0:00:48.094408] generated distance matrix
[0:00:02.029775] allocated dists
[0:00:02.031260] sampled integers
[0:00:02.482119] calculated weights
[0:00:58.680856] applied weights
```

**Comment by ArtPoon** [comment]
Attempted the following - it ate up all my RAM :-(
```python

        # compute symmetric differences
        sym_diffs, m, labels = get_sym_diffs(lfeatures)
        print('[{}] generated distance matrix'.format(datetime.now() - t0))

        # export labels
        outfile = open('{}.labels.csv'.format(lineage), 'w')
        outfile.write('index,name\n')
        for i, names in enumerate(labels):
            for na in names:
                outfile.write('{},{}\n'.format(i, na))
        outfile.close()

        # bootstrap sampling and tree reconstruction
        trees = []
        def log_result(phy):
            trees.append(phy)

        pool = Pool(processes=4)
        for i in range(10):
            pool.apply_async(bootstrap, args=(sym_diffs, len(labels), m), callback=log_result)
        pool.close()
        pool.join()
```

**Comment by ArtPoon** [comment]
orolo died :-/
```console
art@orolo:~$ top

top - 17:45:25 up 54 days,  1:03,  2 users,  load average: 1.78, 0.55, 0.19
Tasks: 550 total,   5 running, 340 sleeping,   0 stopped,   0 zombie
%Cpu(s):  5.6 us,  4.4 sy,  0.0 ni, 87.7 id,  2.2 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 32852408 total,   201528 free, 32356432 used,   294448 buff/cache
KiB Swap: 33422844 total, 28173784 free,  5249060 used.   122840 avail Mem 

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND           
 45952 art       20   0 24.653g 0.020t    176 R  96.9 64.6   0:29.96 python3           
 45849 art       20   0 12.499g 0.011t    416 S  96.3 36.0   1:53.28 python3           
   224 root      20   0       0      0      0 R  51.7  0.0  22:43.27 kswapd0           
  1458 root      20   0       0      0      0 R  21.2  0.0  73:36.38 dmcrypt_write  
```

**Comment by ArtPoon** [comment]
Wrote new code that gives user the option of writing symmetric differences to a file instead of storing in memory - hopefully this will resolve the RAM issue.
First, here is the timing with the original code (sym diffs in RAM):
```console
art@orolo:~/git/covizu$ python3 scripts/clustering.py data/gisaid-human.2.json 
[0:00:00.000006] loading lineage classifications from database
[0:00:00.301702] loading JSON
filtered 12522 problematic features
dropped 17598 records with uncalled bases in excess of 600
[0:00:02.224012] start B.1, 17381 entries
[0:00:47.985535] generated distance matrix
[0:03:55.361149] generated dist matrix
[0:05:54.136117] rapidNJ complete
```
Memory usage at about 30% (of 36G)

**Comment by ArtPoon** [comment]
Timing with writing to file:
```console
art@orolo:~/git/covizu$ python3 scripts/clustering.py data/gisaid-human.2.json 
[0:00:00.000006] loading lineage classifications from database
[0:00:00.302981] loading JSON
filtered 12522 problematic features
dropped 17598 records with uncalled bases in excess of 600
[0:00:02.187951] start B.1, 17381 entries
[0:03:07.465960] generated distance matrix
[0:07:10.452833] generated dist matrix
```
Memory usage stayed around 1%

**Comment by ArtPoon** [comment]
Current attempt:
```python
        with Pool(2) as pool:
            results = [pool.apply_async(bootstrap, [sym_diffs, len(labels), m])
                       for _ in range(10)]
            trees = [r.get() for r in results]
```

```console
art@orolo:~/git/covizu$ python3 scripts/clustering.py data/gisaid-human.2.json 
[0:00:00.000007] loading lineage classifications from database
[0:00:00.302773] loading JSON
filtered 12522 problematic features
dropped 17598 records with uncalled bases in excess of 600
[0:00:02.194833] start B.1, 17381 entries
[0:03:06.137023] computed symmetric differences
Traceback (most recent call last):
  File "scripts/clustering.py", line 339, in <module>
    trees = [r.get() for r in results]
  File "scripts/clustering.py", line 339, in <listcomp>
    trees = [r.get() for r in results]
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/lib/python3.6/tempfile.py", line 624, in func_wrapper
    return func(*args, **kwargs)
TypeError: cannot serialize '_io.TextIOWrapper' object
```

**Comment by ArtPoon** [comment]
Note, I can't pass a callback function to `bootstrap`:
```console
Traceback (most recent call last):
  File "scripts/clustering.py", line 335, in <module>
    trees = [r.get() for r in results]
  File "scripts/clustering.py", line 335, in <listcomp>
    trees = [r.get() for r in results]
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
TypeError: expected str, bytes or os.PathLike object, not method
```

**Comment by ArtPoon** [comment]
Successful run, 10 bootstraps on 5 cores:
```console
art@orolo:~/git/covizu$ python3 scripts/clustering.py data/gisaid-human.2.json 
[0:00:00.000006] loading lineage classifications from database
[0:00:00.298366] loading JSON
filtered 12522 problematic features
dropped 17598 records with uncalled bases in excess of 600
[0:00:02.182735] start B.1, 17381 entries
[0:03:08.053424] computed symmetric differences
[0:16:42.338465] built NJ trees
[0:52:04.297140] built consensus tree
```

**Comment by ArtPoon** [comment]
More testing success!
```console
art@orolo:~/git/covizu$ python3 scripts/clustering.py data/gisaid-human.2.json --out working -t 24
[0:00:00.000007] loading lineage classifications from database
[0:00:00.319412] loading JSON
filtered 12522 problematic features
dropped 17598 records with uncalled bases in excess of 600
[0:00:02.318694] start B.1, 17381 entries
[0:03:13.802622] computed symmetric differences
[0:03:13.814323] launching pool with 24 threads
[0:57:38.952959] built NJ trees from 100 bootstraps
```
