### ISSUE TITLE
Map NJ trees to beadplots

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#136]
Replace minimum spanning trees with bootstrapped neighbor joining trees for drawing beadplots.

**Comment by ArtPoon** [comment]
Note we still have to validate the NJ tree reconstruction, see #131

**Comment by ArtPoon** [comment]
Ran all lineages for first time:
```
[0:00:00.000005] loading lineage classifications from database
[0:00:00.305473] loading JSON
filtered 12522 problematic features
dropped 17598 records with uncalled bases in excess of 600
[0:00:02.088742] start B.4, 391 entries
[0:00:02.344107] computed symmetric differences, reduced down to 263 variants
[0:00:02.344502] launching pool with 24 threads
[0:00:05.030189] built NJ trees from 100 bootstraps
[0:00:05.165593] start A.1, 2102 entries
[0:00:07.682055] computed symmetric differences, reduced down to 1061 variants
[0:00:07.683728] launching pool with 24 threads
[0:00:32.039488] built NJ trees from 100 bootstraps
[0:00:32.594269] start A, 733 entries
...
[0:01:36.648943] start B.1, 17381 entries
[0:04:45.105798] computed symmetric differences, reduced down to 8799 variants
[0:04:45.117707] launching pool with 24 threads
[0:58:50.516091] built NJ trees from 100 bootstraps
[0:58:58.580177] start B.2.8, 23 entries
...
[0:59:00.983938] start B.1.1, 15219 entries
[1:01:05.326063] computed symmetric differences, reduced down to 7357 variants
[1:01:05.337319] launching pool with 24 threads
[1:34:41.416039] built NJ trees from 100 bootstraps
[1:34:46.196887] start B.1.36, 623 entries
...
[1:38:30.686653] start B.12, 1 entries
[1:38:30.686938] computed symmetric differences, reduced down to 1 variants
[1:38:30.687087] launching pool with 24 threads
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "scripts/clustering.py", line 294, in bootstrap
    stdout = subprocess.check_output(cmd, stderr=subprocess.DEVNULL)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['rapidnj', '/tmp/tmpu8cgb896', '-i', 'pd', '--no-negative-length']' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts/clustering.py", line 370, in <module>
    trees = [r.get() for r in results]
  File "scripts/clustering.py", line 370, in <listcomp>
    trees = [r.get() for r in results]
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
```

```

**Comment by ArtPoon** [comment]
Fixed in commit
Analysis seems to have completed in about 3 hours.  
```console
art@orolo:~/git/covizu$ tail nohup.out
[3:24:09.625917] launching pool with 25 threads
[3:24:10.035283] built NJ trees from 100 bootstraps
[3:24:10.046055] start B.1.116, 83 entries
[3:24:10.049094] computed symmetric differences, reduced down to 25 variants
[3:24:10.049351] launching pool with 25 threads
[3:24:10.458632] built NJ trees from 100 bootstraps
[3:24:10.475788] start B.1.82, 9 entries
[3:24:10.476354] computed symmetric differences, reduced down to 5 variants
[3:24:10.476538] launching pool with 25 threads
[3:24:10.887001] built NJ trees from 100 bootstraps
```

However, there were two Python processes still running on Orolo that were taking up all the RAM:
```
art@orolo:~$ top

top - 14:33:29 up 4 days,  4:06,  2 users,  load average: 3.35, 2.89, 11.32
Tasks: 501 total,   2 running, 279 sleeping,   0 stopped,  21 zombie
%Cpu(s):  3.6 us,  0.8 sy,  0.0 ni, 93.7 id,  1.8 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 32852404 total,   235440 free, 32236920 used,   380044 buff/cache
KiB Swap: 33422844 total, 19103476 free, 14319368 used.   208516 avail Mem 

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND   
 21409 art       20   0 27.232g 0.023t   3036 R 100.0 74.8  27:10.95 python3   
 16670 art       20   0 11.625g 6.701g    444 S  27.9 21.4  51:21.62 python3 
```

**Comment by ArtPoon** [comment]
Implemented JSON generating code in `dev` branch, `beadplot.py`
Testing underway

**Comment by ArtPoon** [comment]
See #150

**Comment by ArtPoon** [comment]
Anticipated differences from previous JSON file:
* diversity measures are no longer being calculated - need to wait until we can carry over mutations (features) to this step
* unsampled ancestral nodes are represented by an entry in the `nodes` dictionary (associative list) containing an empty list, *i.e.*, no beads.
