### ISSUE TITLE
beadplot: NoneType error

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#150]
```console
art@Wernstrom covizu % python3 covizu/beadplot.py working/B.13.boot.nwk working/B.13.labels.csv
Detected multiple trees in file, handling as bootstrap

Traceback (most recent call last):
  File "covizu/beadplot.py", line 183, in <module>
    tree = annotate_tree(ctree, args.labels)
  File "covizu/beadplot.py", line 109, in annotate_tree
    for idx in node.name.split('|'):
AttributeError: 'NoneType' object has no attribute 'split'
```

Tree before `collapse_polytomies`:
```
(0:0.00000,(((1:0.00000,8:1.86735)0.71:1.54286,3:0.00000)0.72:1.43662,7:0.93878)0.88:2.02326,2:1.14286,4:0.95918,5:1.01020,6:2.19388)1.00:0.00000;
```

Tree after calling `collapse_polytomies`:
```
((((8:1.86735)10.71:1.54286)30.72:1.43662,7:0.93878)0.88:2.02326,2:1.14286,4:0.95918,5:1.01020,6:2.19388)01.00:0.00000;
```

**Comment by ArtPoon** [comment]
Displaying the above two trees on left (consensus) and right (collapsed polytomies), respectively:
![image](https://user-images.githubusercontent.com/1109328/96911111-62b63b00-146e-11eb-9d2b-b044b1d1f436.png)

**Comment by ArtPoon** [comment]
The problem is the node with confidence (support) 0.88 - it has no `name` attribute.  This represents an unsampled variant that is ancestral to two sampled variants.  Let's just give it an empty string.
