### ISSUE TITLE
Stream FASTA from db to minimap2

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#151]
Apparently minimap2 can handle stdin for input:
https://github.com/lh3/minimap2/issues/239

It would be nice to not have to write out a FASTA of all unaligned genome sequences to the filesystem every time we want to run the pipeline - i.e., it would be fastesr to stream this text directly from the sqlite3 database.

**Comment by ArtPoon** [comment]
Having trouble streaming from `db_utils:dump_raw()` to `minimap2:minimap2()`:
```python
def dump_raw(outfile=None, db='data/gsaid.db'):
    """
    Function to dump all raw seqs in RAQSEQ table
    :params:
        :outfile: destination (fasta) file to write seqs to
        :db: sqlite3 database
    """
    cur, conn = open_connection(db)
    seqs = cur.execute("SELECT `header`, `unaligned` FROM rawseq;").fetchall()
    if outfile is None:
        for h, s in seqs:
            yield '>{}\n{}\n'.format(h, s)
    else:
        with open(outfile, 'w') as fastafile:
            for h, s in seqs:
                fastafile.write('>{}\n{}\n'.format(h, s))
    fastafile.close()
    conn.close()
---
def minimap2(infile, ref, use_db=False, path='minimap2', nthread=3, minlen=29000):
    """
    Wrapper function for minimap2.

    :param infile:  str, path to input FASTA file or database
    :param ref:  str, path to FASTA with reference sequence(s)
    :param db:  bool, if True then stream data from database infile
    :param path:  str, path to binary executable
    :param nthread:  int, number of threads for parallel execution of minimap2
    :param minlen:  int, filter genomes below minimum length; to accept all, set to 0.

    :yield:  query sequence name, reference index, CIGAR and original
             sequence
    """
    if use_db:
        p = subprocess.Popen(
            [path, '-t', str(nthread), '-a', '--eqx', ref, '-'],
            stdin=dump_raw(db=infile), stdout=subprocess.PIPE, stderr=subprocess.DEVNULL
        )
```

```console
art@orolo:~/git/covizu$ python3 covizu/minimap2.py data/gsaid.db --db
Traceback (most recent call last):
  File "covizu/minimap2.py", line 267, in <module>
    for qname, diffs, missing in encode_diffs(mm2, reflen=reflen):
  File "covizu/minimap2.py", line 157, in encode_diffs
    for qname, rpos, cigar, seq in iter:
  File "covizu/minimap2.py", line 55, in minimap2
    stdin=dump_raw(db=infile), stdout=subprocess.PIPE, stderr=subprocess.DEVNULL
  File "/usr/lib/python3.6/subprocess.py", line 687, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/usr/lib/python3.6/subprocess.py", line 1192, in _get_handles
    p2cread = stdin.fileno()
AttributeError: 'generator' object has no attribute 'fileno'
```

Tried using `io.StringIO` instead:
```python
def dump_raw(outfile=None, db='data/gsaid.db'):
    """
    Function to dump all raw seqs in RAQSEQ table
    :params:
        :outfile: destination (fasta) file to write seqs to.  If None,
                  return StringIO object.
        :db: sqlite3 database
    """
    cur, conn = open_connection(db)
    seqs = cur.execute("SELECT `header`, `unaligned` FROM rawseq;").fetchall()
    conn.close()

    if outfile is None:
        # return file object for streaming
        fastafile = StringIO()
        for h, s in seqs:
            fastafile.write('>{}\n{}\n'.format(h, s))
        fastafile.seek(0)
        return fastafile
```

```console
art@orolo:~/git/covizu$ python3 covizu/minimap2.py data/gsaid.db --db
Traceback (most recent call last):
  File "covizu/minimap2.py", line 267, in <module>
    for qname, diffs, missing in encode_diffs(mm2, reflen=reflen):
  File "covizu/minimap2.py", line 157, in encode_diffs
    for qname, rpos, cigar, seq in iter:
  File "covizu/minimap2.py", line 55, in minimap2
    stdin=dump_raw(db=infile), stdout=subprocess.PIPE, stderr=subprocess.DEVNULL
  File "/usr/lib/python3.6/subprocess.py", line 687, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/usr/lib/python3.6/subprocess.py", line 1192, in _get_handles
    p2cread = stdin.fileno()
io.UnsupportedOperation: fileno
```

**Comment by ArtPoon** [comment]
I think the problem was that I'm supposed to be using `communicate`.
Original code:
```python
        p = subprocess.Popen(
            [path, '-t', str(nthread), '-a', '--eqx', ref, '-'],
            stdin=dump_raw(db=infile), stdout=subprocess.PIPE, stderr=subprocess.DEVNULL
        )
```

Proposed fix:
```python
        p = subprocess.Popen(
            [path, '-t', str(nthread), '-a', '--eqx', ref, '-'],
            stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL
        )
        p.communicate(dump_raw(db=infile))
```

**Comment by ArtPoon** [comment]
Still stuck...
```console
art@orolo:~/git/covizu$ python3 batch.py working/test.json --ft2bin fasttree2-mp  -mmt 8 -njt 12
🦠 [0:00:00.000005] Retrieving lineage genomes
Traceback (most recent call last):
  File "batch.py", line 61, in <module>
    fasta = treetime.retrieve_genomes(args.db, ref_file=args.ref, misstol=args.misstol)
  File "/home/art/git/covizu/covizu/treetime.py", line 192, in retrieve_genomes
    for row in filter_outliers(iter):
  File "/home/art/git/covizu/covizu/utils/seq_utils.py", line 345, in filter_outliers
    for qname, diffs, missing in iter:
  File "/home/art/git/covizu/covizu/minimap2.py", line 162, in encode_diffs
    for qname, rpos, cigar, seq in iter:
  File "/home/art/git/covizu/covizu/minimap2.py", line 72, in minimap2
    line.strip().split()[:10]
ValueError: not enough values to unpack (expected 10, got 0)
```

**Comment by ArtPoon** [comment]
Implemented in dev branch
