### ISSUE TITLE
Beadplot getting crowded for high prevalence lineages

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#159]
For example, here is lineage B for an outdated database (last updated about August 2020).
![image](https://user-images.githubusercontent.com/1109328/98181116-906c9c80-1ed0-11eb-99df-26076bd40040.png)

**Comment by ArtPoon** [comment]
Related problem - there are some variants that are marked with a "genomic distance" of near zero - these should be getting collapsed into the parental variant.

**Comment by ArtPoon** [comment]
For example, lineage B.2.8 has a few edges of near zero length (the first entry can be ignored because it is the "root" of the subtree):
```js
beaddata[5].variants.map(x => x.dist)
(25) [0, 1.552752575757576, 0.82, 0.85, 1.8595122727272724, 1.537037037037037, 0.86, 1.421875, 1.0589217299999998, 1.8450533333333334, 0.10635662000000001, 0.6570872011921, 0.7408541862214925, 5.429704999999999, 3.0600000011921, 5.15, 3.91, 4.31, 1.4282206000000002, 1.3611818771525994, 1.6455696202531647, 4.17235e-9, 1.08, 5.9605e-9, 1]
```

**Comment by ArtPoon** [comment]
I propose we should be collapsing branches that have a mean length below `0.5`, which implies that only a minority of bootstrap replicates have a branch length of `1` or greater..
![image](https://user-images.githubusercontent.com/1109328/98188828-c0706b80-1ee1-11eb-89cf-8f315d3b5bf3.png)

**Comment by ArtPoon** [comment]
Collapsing branches with mean lengths below 0.5 reduced the number of variants in `B` from 1637 to 1140.
Reprocessing full database in `orolo` to see visual impact.

**Comment by ArtPoon** [comment]
Screening genomes based on number of uncalled bases (missing data) was only being applied to time-scaled tree reconstruction.  We should be doing the same thing for clustering and bead plot generation.

**Comment by ArtPoon** [comment]
Attempted to run with `args.misstol` on Orolo, threw an exception while building NJ trees:
```console
🦠 [0:47:02.650951] built NJ trees from 100 bootstraps
🦠 [0:47:02.674104] start B.1.1.21, 4 entries
🦠 [0:47:02.759220] computed symmetric differences (1 variants)
Traceback (most recent call last):
  File "batch.py", line 119, in <module>
    ctree = clustering.consensus(trees, cutoff=args.cutoff)
  File "/home/art/git/covizu/covizu/clustering.py", line 290, in consensus
    trees = list(trees)
TypeError: 'NoneType' object is not iterable
```

**Comment by ArtPoon** [comment]
Wow with missing data limit of 300 bases, we're down to 905 variants in `B` and 5817 variants in `B.1`.

**Comment by ArtPoon** [comment]
After collapsing polytomies, beadplots comprised 861 variants in `B` and 5260 variants in `B.1`.
The only other thing I can think of is to increasing the bootstrap support threshold from 50%, and more aggressively collapse sequences into variants.

**Comment by ArtPoon** [comment]
Focus on #132, closing for now.
