### ISSUE TITLE
batch.py on Langley is choking

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#175]
No change since 1:30am today.
```console
art@Langley:/home/covid/covizu/debug$ tail covizu.log 
🦠 [0:35:55.323872] 4 sequences of lineage B.1.1.13 passed filters
🦠 [0:35:55.514158] lineage B.1.5.15 has 34 sequences
🦠 [0:35:55.912539] 27 sequences of lineage B.1.5.15 passed filters
🦠 [0:35:56.095180] lineage B.1.5.20 has 22 sequences
🦠 [0:35:56.397352] 20 sequences of lineage B.1.5.20 passed filters
🦠 [0:35:56.567518] lineage B.1.1.34 has 50 sequences
🦠 [0:35:57.070556] 44 sequences of lineage B.1.1.34 passed filters
🦠 [0:35:57.237796] lineage B.1.130 has 55 sequences
🦠 [0:35:57.775613] 49 sequences of lineage B.1.130 passed filters
🦠 [0:35:57.943476] lineage B.1.102 has 130 sequences
art@Langley:/home/covid/covizu/debug$ ls -lt
total 3396
-rw-rw-r-- 1 ewong347 ewong347   75825 Nov 21 01:36 covizu.log
-rw-rw-r-- 1 ewong347 ewong347  421870 Nov 21 01:00 Autobot.log
-rw-rw-r-- 1 ewong347 ewong347       0 Nov 21 01:00 filtered.log
-rw-rw-r-- 1 ewong347 ewong347     334 Nov 15 02:01 test.log
-rwxrwxrwx 1 root     root     2959028 Sep 20 21:49 Chunkybot.log
-rw-rw-r-- 1 ewong347 ewong347     426 Sep 13 04:05 Migrate.log
-rw-rw-r-- 1 ewong347 ewong347     604 Aug 24 06:37 backup-update.log
art@Langley:/home/covid/covizu/debug$ top -b -n1 | grep ewong | head
11055 ewong347  20   0 3282000 2.131g  28080 R 100.0  3.4 461:54.63 python3.7
 2151 ewong347  20   0   77248   7268   5564 S   0.0  0.0   0:00.64 systemd
 2152 ewong347  20   0  130560   3048      0 S   0.0  0.0   0:00.00 (sd-pam)
 2165 ewong347  20   0  281300   5968   5000 S   0.0  0.0   0:00.17 gnome-keyr+
 2171 ewong347  20   0  205064   5368   4764 S   0.0  0.0   0:00.00 gdm-x-sess+
 2178 ewong347  20   0   51304   5668   3712 S   0.0  0.0   0:05.79 dbus-daemon
 2185 ewong347  20   0  552936  13292  10220 S   0.0  0.0   0:00.47 gnome-sess+
 2295 ewong347  20   0   11308    320      0 S   0.0  0.0   0:10.52 ssh-agent
 2297 ewong347  20   0  349508   5644   5152 S   0.0  0.0   0:00.01 at-spi-bus+
 2302 ewong347  20   0   50060   4096   3596 S   0.0  0.0   0:00.14 dbus-daemon
```
Lots of zombie `minimap2` processes, I'm going to kill those off and see if that clears things up.

**Comment by ArtPoon** [comment]
Well, here's a problem:
```console
art@Langley:/home/covid/covizu$ python3 batch.py -h
Traceback (most recent call last):
  File "batch.py", line 5, in <module>
    from covizu import minimap2, clustering, treetime, beadplot
  File "/home/covid/covizu/covizu/minimap2.py", line 9, in <module>
    from covizu.utils.seq_utils import convert_fasta
  File "/home/covid/covizu/covizu/utils/seq_utils.py", line 4, in <module>
    from scipy.stats import poisson
ModuleNotFoundError: No module named 'scipy'
```

**Comment by ArtPoon** [comment]
Also needed to install Biopython

**Comment by ArtPoon** [comment]
@ewong347 I started a manual run on Langley
```console
art@Langley:/home/covid/covizu$ nohup python3 batch.py data/clusters.json &
[1] 18683
```

**Comment by ArtPoon** [comment]
```console
art@Langley:/home/covid/covizu$ tail nohup.out 
🦠 [0:04:02.831791] Reconstructing tree with fasttree2
🦠 [0:05:48.548416] Reconstructing time-scaled tree with treetime
Traceback (most recent call last):
  File "batch.py", line 79, in <module>
    clock=args.clock, verbosity=0)
  File "/home/covid/covizu/covizu/treetime.py", line 102, in treetime
    check_call(call)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['treetime', '--tree', '/tmp/cvz_tt_4ap8hv28', '--aln', '/tmp/cvz_tt_6edzipwj', '--dates', '/tmp/cvz_tt_6zhgajt0', '--outdir', 'data/', '--verbose', '0', '--clock-rate', '0.0008']' returned non-zero exit status 1.
```

**Comment by ArtPoon** [comment]
```console
art@Langley:/home/covid/covizu$ treetime
Traceback (most recent call last):
  File "/usr/local/bin/treetime", line 4, in <module>
    from treetime import version, make_parser
ModuleNotFoundError: No module named 'treetime'
```

**Comment by ArtPoon** [comment]
`numpy` on Langley is too old:
```console
art@Langley:/home/covid/treetime-0.8.0$ sudo python3 setup.py install
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
...
Installed /usr/local/lib/python3.6/dist-packages/phylo_treetime-0.8.0-py3.6.egg
Processing dependencies for phylo-treetime==0.8.0
error: numpy 1.13.3 is installed but numpy>=1.15 is required by {'matplotlib'}
art@Langley:/home/covid/treetime-0.8.0$ apt search python3-numpy
Sorting... Done
Full Text Search... Done
python3-numpy/bionic,now 1:1.13.3-2ubuntu1 amd64 [installed]
  Fast array facility to the Python 3 language
```

**Comment by ArtPoon** [comment]
Argh, too many problems with `pip` installs of Python modules all over the place.
Logging in as @ewong347 to run `batch.py` instead.

**Comment by ArtPoon** [comment]
So far so good - getting held up where I'd expect:
```console
ewong347@Langley:/home/covid/covizu$ tail nohup.out 
🦠 [0:11:38.175683] lineage B.1.1.48 has 13 sequences
🦠 [0:11:38.314881] 13 sequences of lineage B.1.1.48 passed filters
🦠 [0:11:38.489563] lineage B.1.1.45 has 13 sequences
🦠 [0:11:38.631723] 13 sequences of lineage B.1.1.45 passed filters
🦠 [0:11:38.804596] lineage B.1.137 has 21 sequences
🦠 [0:11:38.965162] 6 sequences of lineage B.1.137 passed filters
🦠 [0:11:38.968336] Neighbor-joining reconstruction
🦠 [0:11:38.968361] start B.1, 38301 entries
🦠 [0:31:02.162119] computed symmetric differences (17573 variants)
🦠 [0:31:02.163820] launching pool with 12 threads
```

**Comment by ArtPoon** [comment]
Note invocation was:
```console
ewong347@Langley:/home/covid/covizu$ nohup python3 batch.py data/clusters1.json &
```
using `clusters1.json` because `ewong347` does not have write permission to `clusters.json` (I overwrote it as `art`)

**Comment by ArtPoon** [comment]
@ewong347 I commented out the crontab for `covizu.sh` temporarily, because this test run is still in progress -- doing lineage `B.1` alone will take about six hours, based on previous test runs.

**Comment by ArtPoon** [comment]
fwiw Langley has twice the RAM as Orolo, so we may be able to get away with more than 12 threads for bootstrapping
see #165

**Comment by ArtPoon** [comment]
Wow, that took a lot longer than it did on `orolo`.  Adding threads with `-njt 18` should help.
```console
ewong347@Langley:/home/covid/covizu$ tail nohup.out 
🦠 [15:46:27.573484] launching pool with 12 threads
🦠 [15:46:37.408798] built NJ trees from 100 bootstraps
🦠 [15:46:37.417507] start B.1.1.45, 13 entries
🦠 [15:46:37.417904] computed symmetric differences (6 variants)
🦠 [15:46:37.417919] launching pool with 12 threads
🦠 [15:46:47.249219] built NJ trees from 100 bootstraps
🦠 [15:46:47.257353] start B.1.137, 6 entries
🦠 [15:46:47.257760] computed symmetric differences (6 variants)
🦠 [15:46:47.257775] launching pool with 12 threads
🦠 [15:46:56.911292] built NJ trees from 100 bootstraps
```

**Comment by ArtPoon** [comment]
Data files confirmed to run properly on updated master branch on `filogeneti`
Note `dbstats.json` on server has not been updated since the 12th.
