### ISSUE TITLE
Annotate tree/beadplots with mutation data

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#177]
Since we are basing the entire analysis on "features", i.e., genetic differences from a reference genome, it should be straight-forward to incorporate this information into the JSON data, display it in tool tips, and make mutations searchable.

**Comment by ArtPoon** [comment]
Making mutations searchable will be complicated significantly by the fact that users will be inclined to search by amino acid residue in a given protein-coding region, and not nucleotide position relative to the entire reference genome.

**Comment by ArtPoon** [comment]
To minimize the impact of annotating nodes with mutations on JSON file size, we should only include the mutations associated with that node's branch, *i.e.*, we should not label a node with all differences of the corresponding sequence from the reference genome.

**Comment by ArtPoon** [comment]
If we're going to do this, then we should re-root each lineage-specific consensus tree.  Would it be feasible to use root-to-tip regression?

**Comment by ArtPoon** [comment]
* annotating the JSON with mutations for every node (bead) would result in an excessively large data file
* it may be possible to label edges instead of nodes with mutation events, but we would need to modify the interface to highlight subtrees that descend from a particular edge (and assume no reversion)
* alternatively, we could handle this on the server side instead of client side (server accepts asynchronous query from client and returns search result for a particular mutation)
* alternatively, instead of providing JSON data for all known mutations, we can choose a small subset of mutations to visualize (perhaps based on overall frequency in database)

**Comment by ArtPoon** [comment]
Experiment with rooting consensus trees first

**Comment by ArtPoon** [comment]
Experimented with treetime rooting of B.1.1.7 consensus tree.  I modified `beadplot.py` as follows:
```diff
diff --git a/covizu/beadplot.py b/covizu/beadplot.py
index c90eccf..c46eaa0 100644
--- a/covizu/beadplot.py
+++ b/covizu/beadplot.py
@@ -5,6 +5,7 @@ from covizu.clustering import consensus
 from Bio import Phylo
 from io import StringIO
 from csv import DictReader
+import sys
 
 
 def parse_labels(handle):
@@ -88,7 +89,7 @@ def annotate_tree(tree, label_dict, minlen=0.5, callback=None):
 
     :param tree:  Phylo.Clade, consensus tree
     :param label_dict:  dict, lists of genome labels keyed by tree tip integer index
-    :return:  dict, lists of sequence labels keyed by integer indices
+    :return:  Phylo.Clade, tree with `labels` node attributes
     """
 
     # validate tree and labels
@@ -165,7 +166,7 @@ def serialize_tree(tree):
 
 def parse_args():
     """ Command line interface """
-    parser = argparse.ArgumentParser(description="")
+    parser = argparse.ArgumentParser(description="Serialize consensus or bootstrap trees to JSON data.")
     parser.add_argument("tree", type=argparse.FileType('r'),
                         help="input, path to file with consensus tree or bootstrap trees")
     parser.add_argument("labels", type=argparse.FileType('r'),
@@ -174,6 +175,8 @@ def parse_args():
                         help="output, path to file to write JSON, defaults to stdout")
     parser.add_argument("--boot", action="store_true",
                         help="option, indicates that input file contains bootstrap trees")
+    parser.add_argument("--consensus", action="store_true",
+                        help="option, output consensus tree only (no JSON data).")
     parser.add_argument("--cutoff", type=float, default=0.5,
                         help="option, if user sets --boot, specifies bootstrap support "
                              "threshold parameter (default 0.5)")
@@ -198,6 +201,22 @@ if __name__ == "__main__":
 
     # sequence labels keyed by integers mapping to tips
     label_dict = parse_labels(args.labels)
+
+    if args.consensus:
+        for tip in ctree.get_terminals():
+            tip.branch_length /= 29900
+        for node in ctree.get_nonterminals():
+            node.branch_length /= 29900
+        Phylo.write(ctree, args.outfile, format='newick')
+        with open(args.outfile.name+'.csv', 'w') as out2:
+            out2.write('name,date\n')
+            for index, samples in label_dict.items():
+                coldates = [sample.split('|')[-1] for sample in samples]
+                coldates.sort()
+                out2.write('{},{}\n'.format(index, coldates[0]))
+
+        sys.exit()
+
     tree = annotate_tree(ctree, label_dict, minlen=args.minlen)
     obj = serialize_tree(tree)
     args.outfile.write(json.dumps(obj, indent=2))
```

Ran this modified script with:
```console
art@Wernstrom covizu % python3 covizu/beadplot.py working/B.1.1.7.nwk working/B.1.1.7.labels.csv --consensus -o working/B117.con.nwk
```
Found that letting `treetime` estimate the clock rate gave a better fit but a bad estimate (not enough data), so I constrained the rate to `8e-4` as usual:
```console
art@Wernstrom covizu % treetime --tree working/B117.con.nwk --dates working/B117.con.nwk.csv --sequence-length 29900 --verbose 1 --outdir working --clock-rate 0.0008
```

The end result is quite interesting:
![timetree-export](https://user-images.githubusercontent.com/1109328/108456883-5fc23000-723f-11eb-8cf8-42d0c7e677cd.png)

**Comment by ArtPoon** [comment]
Let's start with annotating clusters (lineages) with consensus mutations.  These can be deposited in `dbstats.json`.

**Comment by ArtPoon** [comment]
Making new branch `mutation`

**Comment by ArtPoon** [comment]
https://github.com/PoonLab/covizu/blob/d0034c25acf35307a85da3e98f8a66fb80c91709/covizu/utils/batch_utils.py#L125-L144

**Comment by ArtPoon** [comment]
Test script
```python
import json
from covizu.utils.batch_utils import get_mutations
from covizu.utils.seq_utils import SC2Locator

locator = SC2Locator()
by_lineage = json.load(open('data/by_lineage.json'))

for lineage, mutations in get_mutations(by_lineage).items():
    print(lineage)
    for feature in mutations:
        annot = locator.parse_mutation(feature)
        print('\t{}\t{}'.format(feature, annot))
```

**Comment by ArtPoon** [comment]
Drilling down on B.1.351, feature `('~', 5229, 'T')`.  Note 5229 is 0-index:
https://github.com/PoonLab/covizu/blob/e99e9658ba0894e1e5bdaf03c2df9a72c4cc593d/covizu/minimap2.py#L87
This should be orf1a K1655N.

**Comment by ArtPoon** [comment]
Got backend implementation done, running test.

**Comment by ArtPoon** [comment]
excerpt from resulting `dbstats.json`:
```json
{
"lastupdate": "2021-04-05", 
"noseqs": 32118, 
"lineages": 
  {"B": {
    "nsamples": 72, 
    "lastcoldate": "2020-02-10", 
    "residual": 0.13345851229644337, 
    "max_ndiffs": 9, 
    "mean_ndiffs": 2.1666666666666665, 
    "mutations": []}, 
  "A": {
    "nsamples": 79, 
    "lastcoldate": "2020-03-10", 
    "residual": 0.3372414971133768, 
    "max_ndiffs": 11, 
    "mean_ndiffs": 4.113924050632911, 
    "mutations": ["aa:orf8:L84S"]}, 
  "B.1": {
    "nsamples": 84, 
    "lastcoldate": "2020-03-18", 
    "residual": -0.3065274775215804, 
    "max_ndiffs": 13, 
    "mean_ndiffs": 6.892857142857143, 
    "mutations": ["aa:S:D614G", "aa:orf1b:P314L", "aa:orf1a:T265I", "aa:orf3a:Q57H"]}, 
```

**Comment by ArtPoon** [comment]
Implemented in commit adb3e6293a6e9a47751218789c5e598c7dce31b3

**Comment by ArtPoon** [comment]
Test run failed with exception:
```python
🏄 [18:28:43.355212] start B.1.1.404, 1 entries
Traceback (most recent call last):
  File "batch.py", line 147, in <module>
    annots = [locator.parse_mutation(f) for f in features]
  File "batch.py", line 147, in <listcomp>
    annots = [locator.parse_mutation(f) for f in features]
  File "/home/covizu/covizu/covizu/utils/seq_utils.py", line 356, in parse_mutation
    ramino = self.gcode[rcodon]
KeyError: 'TG'
```

Also forgot what language I was writing in, had to replace `alt.length` with `len(alt)`

**Comment by ArtPoon** [comment]
```python
[covizu@BEVi covizu]$ python3 -i working/issue177.py 
Traceback (most recent call last):
  File "working/issue177.py", line 9, in <module>
    annots = [locator.parse_mutation(f) for f in features]
  File "working/issue177.py", line 9, in <listcomp>
    annots = [locator.parse_mutation(f) for f in features]
  File "/home/covizu/.local/lib/python3.6/site-packages/covizu-0.3-py3.6.egg/covizu/utils/seq_utils.py", line 356, in parse_mutation
    ramino = self.gcode[rcodon]
KeyError: 'TG'
>>> lineage
'B.1.36.34'
>>> features
[('~', 240, 'T'), ('~', 3036, 'T'), ('~', 14407, 'T'), ('~', 18876, 'T'), ('~', 19031, 'T'), ('~', 22443, 'T'), ('~', 23402, 'G'), ('~', 23607, 'A'), ('~', 25562, 'T'), ('~', 26734, 'T'), ('~', 28853, 'T'), ('~', 4892, 'T'), ('~', 6967, 'T'), ('~', 12472, 'T'), ('~', 18801, 'T'), ('~', 22089, 'C'), ('~', 27753, 'T'), ('~', 27757, 'T')]
```

**Comment by ArtPoon** [comment]
```python
>>> for f in features:
...     print(f)
...     locator.parse_mutation(f)
... 
('~', 27757, 'T')
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/covizu/.local/lib/python3.6/site-packages/covizu-0.3-py3.6.egg/covizu/utils/seq_utils.py", line 356, in parse_mutation
    ramino = self.gcode[rcodon]
KeyError: 'TG'
>>> len(locator.refseq)
29903
>>> feat = ('~', 27757, 'T')
>>> typ, pos, alt = feat
>>> this_orf = None
>>> this_left, this_right = None, None
>>> for orf, coords in locator.orfs.items():
...     left, right = coords
...     if left <= pos < right:
...         this_orf = orf
...         this_left, this_right = left, right
...         break
... 
>>> this_orf
'orf7a'
>>> codon_left = 3 * ((pos-this_left)//3)
>>> codon_pos = (pos-this_left) % 3
>>> codon_left
363
>>> codon_pos
1
>>> rcodon = locator.refseq[this_left:this_right][codon_left:(codon_left+3)]
>>> rcodon
'TG'
```
Determined that I had the wrong coordinates for `orf7a`.  Fixed.

**Comment by ArtPoon** [comment]
Used the following script to patch the `dbstats.json` file:
```python
import json
import os
import covizu
from covizu.utils.seq_utils import SC2Locator
from covizu.utils.batch_utils import *
from covizu.utils.progress_utils import Callback

from datetime import datetime
from argparse import Namespace

args = Namespace(ref=os.path.join(covizu.__path__[0], "data/NC_045512.fa"), 
                 ft2bin='fasttree2', 
                 ttbin='treetime', 
                 outdir=os.getcwd(),
                 clock=8e-4)
cb = Callback()
by_lineage = json.load(open('data/by_lineage.json'))

timetree, residuals = build_timetree(by_lineage, args, cb.callback)

locator = SC2Locator()
mutations = {}
for lineage, features in get_mutations(by_lineage).items():
    annots = [locator.parse_mutation(f) for f in features]
    mutations.update({lineage: [a for a in annots if a is not None]})

dbstat_file = os.path.join('dbstats.issue177.json')
timestamp = datetime.now().isoformat().split('.')[0]

with open(dbstat_file, 'w') as handle:
    nseqs = sum([len(rows) for rows in by_lineage.values()])
    val = {
        'lastupdate': timestamp.split('T')[0],
        'noseqs': nseqs,
        'lineages': {}
    }
    for lineage, samples in by_lineage.items():
        ndiffs = [len(x['diffs']) for x in samples]
        val['lineages'][lineage] = {
            'nsamples': len(samples),
            'lastcoldate': max(x['covv_collection_date'] for x in samples),
            'residual': residuals[lineage],
            'max_ndiffs': max(ndiffs),
            'mean_ndiffs': sum(ndiffs)/len(ndiffs),
            'mutations': mutations[lineage]
        }
    json.dump(val, handle)
```

**Comment by ArtPoon** [comment]
Ok these repaired data files work.

**Comment by ArtPoon** [comment]
Do one more dry run
