### ISSUE TITLE
Integrate GISAID feed

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#186]

**Comment by ArtPoon** [comment]
* [ ] process GISAID feed JSON data
* [ ] adapt time-tree reconstruction to use feed data
* [ ] adapt clustering analysis to use feed data

**Comment by ArtPoon** [comment]
Debugging `batch.py` commit 356c11b26c8a278734b470163dada8e1340dab8b
```console
🦠 [0:04:53.463452] Retrieving lineage genomes
🦠 [0:04:54.439456] Reconstructing tree with fasttree2-mp
FastTree Version 2.1.10 Double precision (No SSE3), OpenMP (32 threads)
Alignment: standard input
Nucleotide distances: Jukes-Cantor Joins: balanced Support: SH-like 1000
Search: Normal +NNI +SPR (2 rounds range 10) +ML-NNI opt-each=1
TopHits: 1.00*sqrtN close=default refresh=0.80
ML Model: Jukes-Cantor, CAT approximation with 20 rate categories
Non-unique name 'None' in the alignment
```

**Comment by ArtPoon** [comment]
Dropped Python into interactive mode at this exception and confirmed that two entries in `by_lineage` dict were assigned `None` for lineage:
```python
>>> for h, s in fasta.items():
...   if 'None' in h:
...     print(h)
... 
|None|2020-04-29
|None|2020-11-03
```

**Comment by ArtPoon** [comment]
Ran the following code:
```python
>>> count = 0
>>> handle = lzma.open(path, 'rb')
>>> for line in handle:
...   record = json.loads(line)
...   if record['covv_lineage'] is None:
...     print(record['covv_virus_name'])
...     count += 1
... 
hCoV-19/Italy/UN-UI-0503/2020
hCoV-19/Philippines/PH-RITM-0014/2020
hCoV-19/Philippines/PH-RITM-0015/2020
hCoV-19/Iraq/ERBIL-8/2020
[... continues ...]
>>> count
936
```
I think for time being we need to exclude these from the pipeline.

**Comment by ArtPoon** [comment]
Omitting these records fixed the problem with fasttree2

**Comment by ArtPoon** [comment]
timetree ran ok too.

**Comment by ArtPoon** [comment]
Ok doing full trial run of `batch.py` on Orolo:
```console
art@orolo:~/git/covizu$ nohup python3 -i batch.py data/provision.json.xz data/clusters.json --mmthreads 8 --batchsize 1000 --ft2bin fasttree2-mp --njthreads 12 &
[1] 46590
```

**Comment by ArtPoon** [comment]
Uh oh, it crashed:
```console
🦠 [0:05:01.013133] aligned 216000 records
🦠 [0:05:02.422643] aligned 217000 records
🦠 [0:05:03.551729] Reconstructing tree with fasttree2-mp
🦠 [0:06:36.065091] Reconstructing time-scaled tree with treetime
removing B.1.129:  2020.498 < 2021.04
removing B.1.130:  2020.652 < 2022.39
🦠 [0:07:40.570739] start B, 2841 entries
🦠 [0:07:46.105815] computed symmetric differences (1571 variants)
🦠 [0:07:46.105836] launching pool with 12 threads
🦠 [0:09:19.907569] built NJ trees from 100 bootstraps
>>> Traceback (most recent call last):
  File "batch.py", line 155, in <module>
    result = make_beadplots(by_lineage, args, cb.callback)
  File "batch.py", line 142, in make_beadplots
    beaddict = beadplot.serialize_tree(ctree)
  File "/home/art/git/covizu/covizu/beadplot.py", line 146, in serialize_tree
    variant = intermed[0][1]
IndexError: list index out of range
```

**Comment by ArtPoon** [comment]
This problem was caused by the change in data source - needed to reconstitute the default GISAID labels with pipe `|` delimiters.

**Comment by ArtPoon** [comment]
`orolo` is offline - processing lineage B.1.1 appears to have slammed the swap.

**Comment by ArtPoon** [comment]
closing, need to address #165

**Comment by ArtPoon** [comment]
actually I don't know if this breaks anything in the front end, so reopen
