### ISSUE TITLE
Automate batch processing

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#199]
This should include daily download of provisioning file from the GISAID feed

**Comment by ArtPoon** [comment]
for transferring data files from BEVi to webserver, I think we need the following checks:
* that both `timetree.{timestamp}.nwk` and `clusters.{timestamp}.nwk` are non-empty
* that their time stamps are more recent than the current files on the webserver
* that their time stamps match
* others?

**Comment by ArtPoon** [comment]
Automation of download and analysis are complete.
Still need to handle transfer to webserver.

**Comment by ArtPoon** [comment]
* Created account for covizu user on webserver with SSL key.
* Conferred write privileges to user by adding it to the group associated with the data folder.
* Tested `scp` file transfer using yesterday's data files.

**Comment by ArtPoon** [comment]
```console
[covizu@BEVi ~]$ crontab -l
BASH_ENV=/home/covizu/.bashrc
0 16 * * * python3 /home/covizu/covizu/batch.py > ~/batch.log
```
Monitor tonight to see if process launches.

**Comment by ArtPoon** [comment]
cron job failed to run, `batch.log` was created but remained empty with no messages written.  Determined by running manually that I forgot to load the openmpi module, which causes `batch.py` to exit - a message should have been written to the log.
Revised `crontab`, running a job tonight and then will see if it spins up tomorrow.

**Comment by ArtPoon** [comment]
Haha, `cron` mails the user when there is an error:
```css
Message  2:
From covizu@BEVi.localdomain  Thu Dec 17 16:00:02 2020
Return-Path: <covizu@BEVi.localdomain>
X-Original-To: covizu
Delivered-To: covizu@BEVi.localdomain
From: "(Cron Daemon)" <covizu@BEVi.localdomain>
To: covizu@BEVi.localdomain
Subject: Cron <covizu@BEVi> cd /home/covizu/covizu; module load openmpi/gnu; python3 batch.py >> ~/batch.log
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <XDG_SESSION_ID=94085>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/1011>
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <BASH_ENV=/home/covizu/.bashrc>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/home/covizu>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=covizu>
X-Cron-Env: <USER=covizu>
Date: Thu, 17 Dec 2020 16:00:01 -0500 (EST)
Status: R

/bin/sh: module: command not found
Traceback (most recent call last):
  File "batch.py", line 222, in <module>
    args = parse_args()
  File "batch.py", line 18, in parse_args
    parser.add_argument('--url', type=str, default=os.environ["GISAID_URL"],
  File "/usr/lib64/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'GISAID_URL'
```

**Comment by ArtPoon** [comment]
Added `source /home/covizu/.bashrc` to scheduled cron job

**Comment by ArtPoon** [comment]
cron job broke:
```console
2020-12-18 16:00:06 (12.4 MB/s) - ‘data/provision.2020-12-18T16:00:02.json.xz’ saved 
[26387268/26387268]

Traceback (most recent call last):
  File "batch.py", line 243, in <module>
    by_lineage = process_feed(args, cb.callback)
  File "batch.py", line 102, in process_feed
    return gisaid_utils.sort_by_lineage(filtered, callback=callback)
  File "/home/covizu/covizu/covizu/utils/gisaid_utils.py", line 197, in sort_by_linea
ge
    for i, record in enumerate(records):
  File "/home/covizu/covizu/covizu/utils/gisaid_utils.py", line 154, in filter_proble
matic
    for record in records:
  File "/home/covizu/covizu/covizu/utils/gisaid_utils.py", line 119, in extract_featu
res
    result = list(encode_diffs(mm2, reflen=reflen))
  File "/home/covizu/covizu/covizu/minimap2.py", line 165, in encode_diffs
    for qname, rpos, cigar, seq in iter:
  File "/home/covizu/covizu/covizu/minimap2.py", line 57, in minimap2
    stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'minimap2': 'minimap2'
```
