### ISSUE TITLE
Enable users to process their own data as FASTA (?)

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#202]
This was a requested feature a while back.  Also, now that we have switched to processing the feed from GISAID, that means that other users won't be able to run the backend unless we do something like this.

**Comment by ArtPoon** [comment]
In progress on `dev` branch.  Complicated by recent updates to Pangolin - we will have to require users to install and run that program separately to generate lineage classifications.

**Comment by ArtPoon** [comment]
```
art@Wernstrom covizu % python3 local.py -h working/gisaid_canada_2021_01_05.fasta working/gisaid_canada_2021_01_05.pangolin.csv
Traceback (most recent call last):
  File "local.py", line 142, in <module>
    args = parse_args()
  File "local.py", line 96, in parse_args
    return parser.parse_args()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/argparse.py", line 1768, in parse_args
...
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/argparse.py", line 621, in _expand_help
    return self._get_help_string(action) % params
TypeError: %c requires int or char
```
Problem caused by `%` character in help text within `argparse.add_argument()`.  Solution was to use double percent sign `%%`.

**Comment by ArtPoon** [comment]
```
Traceback (most recent call last):
  File "local.py", line 152, in <module>
    by_lineage = process_local(args, cb.callback)
  File "local.py", line 138, in process_local
    return gisaid_utils.sort_by_lineage(filtered, callback=callback)
  File "/Users/art/git/covizu/covizu/utils/gisaid_utils.py", line 198, in sort_by_lineage
    for i, record in enumerate(records):
  File "/Users/art/git/covizu/covizu/utils/gisaid_utils.py", line 149, in filter_problematic
    mask = load_vcf(vcf_file)
  File "/Users/art/git/covizu/covizu/utils/seq_utils.py", line 218, in load_vcf
    _, pos, _, ref, alt, _, filt, info = line.strip().split()
ValueError: too many values to unpack (expected 8)
```
Space occurred in VCF file (e.g., `South Africa`).  Solution was to split explicitly on `\t`.

**Comment by ArtPoon** [comment]
```console
art@Wernstrom covizu % python3 local.py -mmt 1  working/gisaid_canada_2021_01_05.fasta working/gisaid_canada_2021_01_05.pangolin.csv
🏄 [0:00:02.920540] aligned 0 records
🏄 [0:00:08.376791] aligned 1000 records
Traceback (most recent call last):
  File "local.py", line 163, in <module>
    by_lineage = process_local(args, cb.callback)
  File "local.py", line 149, in process_local
    return gisaid_utils.sort_by_lineage(filtered, callback=callback)
  File "/Users/art/git/covizu/covizu/utils/gisaid_utils.py", line 198, in sort_by_lineage
    for i, record in enumerate(records):
  File "/Users/art/git/covizu/covizu/utils/gisaid_utils.py", line 155, in filter_problematic
    for record in records:
  File "/Users/art/git/covizu/covizu/utils/gisaid_utils.py", line 117, in extract_features
    for fasta, batch in batcher:
  File "/Users/art/git/covizu/covizu/utils/gisaid_utils.py", line 90, in batch_fasta
    for i, record in enumerate(gen):
  File "local.py", line 121, in stream_local
    prefix, country, qname, year = label.split('/')
ValueError: too many values to unpack (expected 4)
```

**Comment by ArtPoon** [comment]
Almost there:
```console
Traceback (most recent call last):
  File "local.py", line 184, in <module>
    result = make_beadplots(by_lineage, args, cb.callback, t0=cb.t0.timestamp())
  File "/home/art/git/covizu/batch.py", line 198, in make_beadplots
    beaddict = beadplot_serial(lineage, features, args)
  File "/home/art/git/covizu/batch.py", line 130, in beadplot_serial
    trees, labels = clustering.build_trees(features, args, callback=callback)
  File "/home/art/git/covizu/covizu/clustering.py", line 211, in build_trees
    union, labels, indexed = recode_features(records, callback=callback)
  File "/home/art/git/covizu/covizu/clustering.py", line 31, in recode_features
    label = '|'.join([record['covv_virus_name'], record['covv_accession_id'],
KeyError: 'covv_accession_id'
```
