### ISSUE TITLE
v0.3 needs to generate dbstats.json

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#203]

**Comment by ArtPoon** [comment]
Merged into master branch and pulled onto cluster - monitor tonight.

**Comment by ArtPoon** [comment]
Script threw an exception last night:
```python
Traceback (most recent call last):
  File "batch.py", line 233, in <module>
    args = parse_args()
  File "batch.py", line 91, in parse_args
    help="Bootstrap cutoff for consensus tree (default 0.5). "
  File "/usr/lib64/python3.6/argparse.py", line 1352, in add_argument
    return self._add_action(action)
  File "/usr/lib64/python3.6/argparse.py", line 1715, in _add_action
    self._optionals._add_action(action)
  File "/usr/lib64/python3.6/argparse.py", line 1556, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib64/python3.6/argparse.py", line 1366, in _add_action
    self._check_conflict(action)
  File "/usr/lib64/python3.6/argparse.py", line 1505, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib64/python3.6/argparse.py", line 1514, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --cutoff: conflicting option string: --cutoff
```
