### ISSUE TITLE
2020-12-31 mangled header broke pipeline

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#211]
```python
2020-12-31 22:00:07 (12.8 MB/s) - ‘data/provision.2020-12-31T22:00:01.json.xz’ saved [30662276/30662276]

Traceback (most recent call last):
  File "batch.py", line 248, in <module>
    by_lineage = process_feed(args, cb.callback)
  File "batch.py", line 107, in process_feed
    return gisaid_utils.sort_by_lineage(filtered, callback=callback)
  File "/home/covizu/covizu/covizu/utils/gisaid_utils.py", line 197, in sort_by_lineage
    for i, record in enumerate(records):
  File "/home/covizu/covizu/covizu/utils/gisaid_utils.py", line 154, in filter_problematic
    for record in records:
  File "/home/covizu/covizu/covizu/utils/gisaid_utils.py", line 116, in extract_features
    for fasta, batch in batcher:
  File "/home/covizu/covizu/covizu/utils/gisaid_utils.py", line 89, in batch_fasta
    for i, record in enumerate(gen):
  File "/home/covizu/covizu/covizu/utils/gisaid_utils.py", line 55, in load_gisaid
    if qname.split('/')[1][0].islower():
IndexError: string index out of range
```

**Comment by ArtPoon** [comment]
Found the culprit: `hCoV-19//Indonesia/JB-TFRIC19-R46646/2020`

**Comment by ArtPoon** [comment]
Passed test on cluster
