### ISSUE TITLE
Colour cluster bands on timetree with different information

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#213]
Instead of dominent country of sampling, we could colour clusters by:
* [x] divergence from root relative to molecular clock (to highlight rapidly mutating lineages like B.1.1.7)
* [x] number of samples
* [x] recency of samples
* [ ] diversity normalized by number of samples
* [ ] depth of sampling as estimated by the number of unsampled variants (ancestral nodes that are not directly observed by sequencing)

This could be an option the user can toggle between.

**Comment by ArtPoon** [comment]
Trying to extract estimated dates from TreeTime output (as a way of determining which lineages are more divergent than expected given the collection date of the representative genome), I am stuck on the following bug:
```python
Traceback (most recent call last):
  File "batch.py", line 253, in <module>
    timetree = build_timetree(by_lineage, args, cb.callback)
  File "batch.py", line 124, in build_timetree
    return treetime.parse_nexus(nexus_file, fasta)
  File "/Users/art/git/covizu/covizu/treetime.py", line 169, in parse_nexus
    node.name, (residuals[node.name]-statistics.mean(rv))/statistics.stdev(rv)
KeyError: 'B.5'
```

My current changes to `timetree.py`:
```diff
@@ -5,6 +5,7 @@ from tempfile import NamedTemporaryFile
 import os
 from io import StringIO
 import re
+import statistics  # Python 3.4+
 
 from Bio import Phylo
 
@@ -113,7 +114,7 @@ def treetime(nwk, fasta, outdir, binpath='treetime', clock=None, verbosi
ty=1):
 
 
 def date2float(isodate):
-    """ Convert ISO date string to float """
+    """ Convert ISO date string to float (years) """
     year, month, day = map(int, isodate.split('-'))
     dt = date(year, month, day)
     origin = date(dt.year, 1, 1)
@@ -121,13 +122,12 @@ def date2float(isodate):
     return dt.year + td/365.25
 
 
-def parse_nexus(nexus_file, fasta, date_tol, callback=None):
+def parse_nexus(nexus_file, fasta, callback=None):
     """
     Converting Treetime NEXUS output into Newick
 
     @param nexus_file:  str, path to TreeTime NEXUS output
-    @param fasta:  dict, {header: seq} from filter_fasta()
-    @param date_tol:  float, tolerance in tip date discordance
+    @param fasta:  dict, {header: seq} from retrieve_genomes()
     @param callback:  function, optional callback
     """
     coldates = {}
@@ -140,17 +140,16 @@ def parse_nexus(nexus_file, fasta, date_tol, callback=None):
 
     # extract date estimates and internal node names
     remove = []
+    residuals = {}
     with open(nexus_file) as handle:
         for line in handle:
             for m in pat.finditer(line):
                 node_name, branch_length, date_est = m.groups()
                 coldate = coldates.get(node_name, None)
-                if coldate and abs(float(date_est) - coldate) > date_tol:
-                    if callback:
-                        callback('removing {}:  {:0.3f} < {}\n'.format(
-                            node_name, coldate, date_est
-                        ), level='INFO')
-                    remove.append(node_name)
+                if coldate:
+                    # if estimated date is well below actual date, lineage has
+                    # more substitutions than expected under molecular clock
+                    residuals.update({node_name: coldate-float(date_est)})
 
     # second pass to excise all comment fields
     pat = re.compile('\[&U\]|\[&mutations="[^"]*",date=[0-9]+\.[0-9]+\]')
@@ -163,7 +162,12 @@ def parse_nexus(nexus_file, fasta, date_tol, callback=None):
     for node_name in remove:
         phy.prune(node_name)
 
+    # normalize residuals and append to tip labels
+    rv = residuals.values()
     for node in phy.get_terminals():
+        node.name = '{}__{}'.format(
+            node.name, (residuals[node.name]-statistics.mean(rv))/statistics.stdev(rv)
+        )
         node.comment = None
 
     for node in phy.get_nonterminals():
@@ -177,7 +181,7 @@ def parse_nexus(nexus_file, fasta, date_tol, callback=None):
 
 def retrieve_genomes(by_lineage, ref_file):
     """
-    Identify earliest sampled genome sequence for each Pangolin lineage.
+    Identify most recent sampled genome sequence for each Pangolin lineage.
     Export as FASTA for TreeTime analysis.
 
     :param by_lineage:  dict, return value from gisaid_utils::sort_by_lineage
@@ -226,11 +230,6 @@ def parse_args():
     parser.add_argument('--clock', type=float, default=8e-4,
                         help='optional, specify molecular clock rate for '
                              'constraining Treetime analysis (default 8e-4).')
-    parser.add_argument('--datetol', type=float, default=0.1,
-                        help='optional, exclude tips from time-scaled tree '
-                             'with high discordance between estimated and '
-                             'known sample collection dates (year units,'
-                             'default: 0.1)')
 
     parser.add_argument('--outdir', default='data/',
                         help='optional, directory to write TreeTime output files')
@@ -258,5 +257,5 @@ if __name__ == '__main__':
     nexus_file = treetime(nwk, fasta, outdir=args.outdir, binpath=args.ttbin,
                           clock=args.clock)
 
-    timetree = parse_nexus(nexus_file, fasta, date_tol=args.datetol)
+    timetree = parse_nexus(nexus_file, fasta)
     Phylo.write(timetree, file=args.outfile, format='newick')
```

**Comment by ArtPoon** [comment]
Looks like this might be an issue with the regex:
```python
>>> s = """utations="A2430C,C18570T",date=2020.86])NODE_0000034:0.45345[&mutations="C2445T,C9430T,T15156C,C15848T,C20368T,G26153T,C26527T,C29149T,G29239A",date=2020.76],(B.2.1:0.48044[&mutations="A264G,A413C,G1141T,G1158A,G2036T,A3138G,A7304C,G12845A,A13003G,G14966T,G18816T,G25354T,C27925A",date=2020.85],B.1.1.65:0.44765[&mutations="C4901T,G18985T,G19480A,C21844T,T23084C,C25318T,T25783C,G27358T",date=2020.82],B.1.1.50:0.47498[&mutations="C1758T,T8871C,G15438T,C19895T,G25726A,G25785T,A28989T,G29260T,G29751C",date=2020.85])NODE_0000031:0.06348[&mutations="G4510A",date=2020.37],(B.1.1.47:0.50703[&mutations="A1553G,C1758T,T6376C,G7388A,C9286T,C10252T,G11222T,C11962T,C14178T,A18036G,G18898T,C19763T,G23438T,C23997T,G25489T,C26085T,G26211T,G26620C,C27600T",date=2020.85],(B.1.1.30:0.22327[&mutations="C1601T,T1771A,G4105T,T16993C,G21624T,C21727T",date=2020.72],B.1.1.51:0.31343[&mutations="G6554A,C9724T,G15380T,C18508T,C27741T",date=2020.81])NODE_0000036:0.15807[&mutations="G4180T,T10453C,C11195T",date=2020.50])NODE_0000035:0.03143[&mutations="C1912T",date=2020.34])NODE_0000029:0.03848[&mutations="C313T",date=2020.31],(B.1.1.61:0.54366[&mutations="G213T,G1439T,C6696T,T18083C,C18568T,G21724C,T27267C,G27987T,A28653G,G28975T,C29743T",date=2020.82],(B.1.1.8:0.49448[&mutations="G701T,G4354A,C6573T,C10029T,G16153A,G20134T,C25528T,G25681T,A26555C,C29774T",date=2020.77],((B.1.1.40:0.35853[&mutations="G526T,C3811T,C3903T,C18885T,G19656T,G27561T",date=2020.69],B.1.1.52:0.46782[&mutations="T9151C,C9693T,C13887T,C14790T,C15924T,T16456C,C21910T,C22033A,C22480T,C23248T,C26028T,G29315C",date=2020.80])NODE_0000027:0.05399[&mutations="C1912T",date=2020.33],(B.1.1.63:0.45623[&mutations="C2973T,C12924T,C20312T,C21597T,C23533T,C27427A,C28308G,C29144T,C29514T",date=2020.73],(B.1.1.48:0.02454[&mutations="G26730A",date=2020.30],((B.1.1.5:0.43857[&mutations="G1957A,A3889G,C4345T,C11407T,C12973T,C12974T,C13274T,A18187G,T19839C,C20436T,G25563T,A25590T,C26858T,A28390G,C29149T",date=2020.86],B.1.1.46:0.42491[&mutations="G11447A,C19602T,C22675T,C27131T,T27384C",date=2020.85])NODE_0000061:0.04507[&mutations="G28077T",date=2020.42],((B.1.1.10:0.43922[&mutations="C835T,C7006T,C10376T,G25617T",date=2020.85],B.1.1.27:0.24524[&mutations="C6354T,G10265A,C16293T,C19011T,C24863T,G25429T,A25448G,G25816C,C27874T,G28325A",date=2020.66])NODE_0000056:0.03895[&mutations="C20178T",date=2020.41],((B.1.1.37:0.42152[&mutations="C5144T,T5182C,T6025C,C8683T,G15406T,C21614T,C21637T,G22992A,C23981A,A28169G",date=2020.86],(B.1.5.15:-0.00000[&mutations="",date=2020.75],B.1.1.39:0.10383[&mutations="G22801T,G23580C",date=2020.85])NODE_0000049:0.30950[&mutations="A1236G,G9130T,C16111T,T27319C,G28487A,C28868T,G29706T",date=2020.75])NODE_0000048:0.04431[&mutations="C3738T",date=2020.44],(B.1.1.34:0.37463[&mutations="C5497T,C5693T,G6368A,T6667G,C9967T,G15982T,G16853T,C21614T,G29711T",date=2020.77],(B.1.1.66:0.38644[&mutations="C1594T,C6633T,C18501T,C22383T,C23625T,G25767A,C27603T,G27632T,G28178T",date=2020.80],(B.1.1.60:0.41650[&mutations="A4851G,G5230T,C8251T,C11575T,C13517T,C18714T,C24378T,C28737T,T28879C",date=2020.83],(B.1.1.55:0.44382[&mutations="C6548T,T7738C,A11782G,C12880T,T13560C,T21570G,T25473C,C26464T,A28254C",date=2020.85],((B.1.1.29:0.29950[&mutations="C18263T,G25266T,T28382C",date=2020.84],(B.1.1.7:0.14331[&mutations="C11919T,C23604A,C27999T",date=2020.85],B.1.1.31:0.11599[&mutations="T9302C,C18657T,C26408T,C28435T,G29810T",date=2020.83],B.1.1.58:0.05042[&mutations="G16137T",date=2020.76])NODE_0000044:0.16712[&mutations="C13667T,G15957T,C19017T,A27865T,T27866A,T29785A",date=2020.71])NODE_0000043:0.13339[&mutations="G1210T,G9802T,G12067T",date=2020.54],(B.1.1.45:0.09136[&mutations="A14791T,C17410T,C27494T",date=2020.50],((B.1.1.54:0.31793[&mutations="T12503C,G25770T,G29449T,C29721T",date=2020.85],D.2:0.26055[&mutations="A1163T,T7540C,C10775T,C12116T,G16647T,C21516T,G22992A,G23401A,A27024C",date=2020.79])NODE_0000038:0.04313[&mutations="C18555T",date=2020.53],(B.1.1.68:0.35905[&mutations="C4276T,C9561T,G11230T,G11401T,C16915T,T17394C,T24088C,G25617T,C29730-,A29731-,C29732-,C29733-,G29734-,A29735-,G29736-,G29737-,C29738-,C29739-,A29740-,C29741-,G29742-,C29743-,G29744-,G29745-,A29746-,G29747-,T29748-,A29749-,C29750-,G29751-,A29752-,T29753-,C29754-,G29755-,A29756-,G29757-,T29758-,G29759-,T29760-,A29761-,C29762-,A29763-,G29764-,T29765-,G29766-,A29767-,A29768-,C29769-,A29770-,A29771-,T29772-,G29773-,C29774-,T29775-,A29776-,G29777-,G29778-",date=2020.85],(B.1.1.57:0.23337[&mutations="G3871T,G13835T,C18032T,C20234T,G23285T,C29077T",date=2020.73],(B.1.1.25:0.36024[&mutations="G204T,C12778T,G19518T,A20374G,C21627T,T22917G,G26065T,G26152T",date=2020.86],(B.1.1.72:0.34931[&mutations="C4113T,C8917T,G9389A,G18922A,C23202T,C28854T,C29171T",date=2020.85],(B.1.1.26:0.32199[&mutations="A2869G,G6352T,C6445T,G23438T,G23522C",date=2020.82],(B.1.1.59:0.05970[&mutations="C2638T,C9442T",date=2020.56],(B.1.1.38:0.19084[&mutations="G26428T,G26589T,C28153T",date=2020.69],B.1.1.28:0.31106[&mutations="A6319G,A7451G,G25088T,T26149C",date=2020.81])NODE_0000197:0.00000[&date=2020.50])NODE_0000196:0.00000[&date=2020.50])NODE_0000194:0.00000[&date=2020.50])NODE_0000193:0.00000[&date=2020.50])NODE_0000192:0.00428[&date=2020.50])NODE_0000191:0.00000[&date=2020.49])NODE_0000188:0.00200[&date=2020.49])NODE_0000186:0.08004[&date=2020.49])NODE_0000184:0.00000[&date=2020.41])NODE_0000181:0.00000[&date=2020.41])NODE_0000180:0.00000[&date=2020.41])NODE_0000179:0.00000[&date=2020.41])NODE_0000177:0.01277[&date=2020.41])NODE_0000176:0.00104[&date=2020.40])NODE_0000172:0.02055[&date=2020.40])NODE_0000169:0.00000[&date=2020.38])NODE_0000164:0.10101[&date=2020.38])NODE_0000160:0.00000[&date=2020.27])NODE_0000159:0.00000[&date=2020.27])NODE_0000156:0.00000[&date=2020.27])NODE_0000155:0.00000[&date=2020.27])NODE_0000154:0.00595[&date=2020.27])NODE_0000148:0.00000[&date=2020.27])NODE_0000146:0.00313[&date=2020.27])NODE_0000143:0.00311[&date=2020.27])NODE_0000141:0.00312[&date=2020.26])NODE_0000140:0.02225[&date=2020.26])NODE_0000138:0.00003[&date=2020.24])NODE_0000137:0.00487[&date=2020.24])NODE_0000135:0.00180[&date=2020.23])NODE_0000069:0.00114[&date=2020.23])NODE_0000066:0.06111[&date=2020.23])NODE_0000065:0.00162[&date=2020.17])NODE_0000060:0.01662[&date=2020.17])NODE_0000000:0.07783[&mutations="G28881A,G28882A,G28883C",date=2020.15],((B.1.120:0.46365[&mutations="C673T,C829T,G1580A,T4125C,C16616T,C26885T,C27603T,C28887T",date=2020.59],B.1.158:0.28879[&mutations="T241C,G1148T,A11716G,A14475-,T14476-,A14477-,C14478-,C14479-,A14480-,C14481-,T14482-,T14483-,C14484-,A14485-,G14486-,A14487-,G14488-,A14489-,G14490-,C14491-,T14492-,A14493-,G14494-,G14495-,T14496-,G14497-,T14498-,T14499-,G14500-,T14501-,C17678T,C17934T,C28849T,C28866"""
>>> for m in pat.finditer(s):
...   print(m.groups())
... 
('NODE_0000034', '0.45345', '2020.76')
('B.2.1', '0.48044', '2020.85')
('B.1.1.65', '0.44765', '2020.82')
('B.1.1.50', '0.47498', '2020.85')
('NODE_0000031', '0.06348', '2020.37')
('B.1.1.47', '0.50703', '2020.85')
('B.1.1.30', '0.22327', '2020.72')
('B.1.1.51', '0.31343', '2020.81')
('NODE_0000036', '0.15807', '2020.50')
('NODE_0000035', '0.03143', '2020.34')
('NODE_0000029', '0.03848', '2020.31')
('B.1.1.61', '0.54366', '2020.82')
('B.1.1.8', '0.49448', '2020.77')
('B.1.1.40', '0.35853', '2020.69')
('B.1.1.52', '0.46782', '2020.80')
('NODE_0000027', '0.05399', '2020.33')
('B.1.1.63', '0.45623', '2020.73')
('B.1.1.48', '0.02454', '2020.30')
('B.1.1.5', '0.43857', '2020.86')
('B.1.1.46', '0.42491', '2020.85')
('NODE_0000061', '0.04507', '2020.42')
('B.1.1.10', '0.43922', '2020.85')
('B.1.1.27', '0.24524', '2020.66')
('NODE_0000056', '0.03895', '2020.41')
('B.1.1.37', '0.42152', '2020.86')
('B.1.1.39', '0.10383', '2020.85')
('NODE_0000049', '0.30950', '2020.75')
('NODE_0000048', '0.04431', '2020.44')
('B.1.1.34', '0.37463', '2020.77')
('B.1.1.66', '0.38644', '2020.80')
('B.1.1.60', '0.41650', '2020.83')
('B.1.1.55', '0.44382', '2020.85')
('B.1.1.29', '0.29950', '2020.84')
('B.1.1.7', '0.14331', '2020.85')
('B.1.1.31', '0.11599', '2020.83')
('B.1.1.58', '0.05042', '2020.76')
('NODE_0000044', '0.16712', '2020.71')
('NODE_0000043', '0.13339', '2020.54')
('B.1.1.45', '0.09136', '2020.50')
('B.1.1.54', '0.31793', '2020.85')
('D.2', '0.26055', '2020.79')
('NODE_0000038', '0.04313', '2020.53')
('B.1.1.68', '0.35905', '2020.85')
('B.1.1.57', '0.23337', '2020.73')
('B.1.1.25', '0.36024', '2020.86')
('B.1.1.72', '0.34931', '2020.85')
('B.1.1.26', '0.32199', '2020.82')
('B.1.1.59', '0.05970', '2020.56')
('B.1.1.38', '0.19084', '2020.69')
('B.1.1.28', '0.31106', '2020.81')
('NODE_0000197', '0.00000', '2020.50')
('NODE_0000196', '0.00000', '2020.50')
('NODE_0000194', '0.00000', '2020.50')
('NODE_0000193', '0.00000', '2020.50')
('NODE_0000192', '0.00428', '2020.50')
('NODE_0000191', '0.00000', '2020.49')
('NODE_0000188', '0.00200', '2020.49')
('NODE_0000186', '0.08004', '2020.49')
('NODE_0000184', '0.00000', '2020.41')
('NODE_0000181', '0.00000', '2020.41')
('NODE_0000180', '0.00000', '2020.41')
('NODE_0000179', '0.00000', '2020.41')
('NODE_0000177', '0.01277', '2020.41')
('NODE_0000176', '0.00104', '2020.40')
('NODE_0000172', '0.02055', '2020.40')
('NODE_0000169', '0.00000', '2020.38')
('NODE_0000164', '0.10101', '2020.38')
('NODE_0000160', '0.00000', '2020.27')
('NODE_0000159', '0.00000', '2020.27')
('NODE_0000156', '0.00000', '2020.27')
('NODE_0000155', '0.00000', '2020.27')
('NODE_0000154', '0.00595', '2020.27')
('NODE_0000148', '0.00000', '2020.27')
('NODE_0000146', '0.00313', '2020.27')
('NODE_0000143', '0.00311', '2020.27')
('NODE_0000141', '0.00312', '2020.26')
('NODE_0000140', '0.02225', '2020.26')
('NODE_0000138', '0.00003', '2020.24')
('NODE_0000137', '0.00487', '2020.24')
('NODE_0000135', '0.00180', '2020.23')
('NODE_0000069', '0.00114', '2020.23')
('NODE_0000066', '0.06111', '2020.23')
('NODE_0000065', '0.00162', '2020.17')
('NODE_0000060', '0.01662', '2020.17')
('NODE_0000000', '0.07783', '2020.15')
('B.1.120', '0.46365', '2020.59')
>>> 
>>> "B.1.5.15" in s
True 
```

**Comment by ArtPoon** [comment]
Fixed in commit 502be70388015f9fd96f8469c2309f9bf6c1a621

**Comment by ArtPoon** [comment]
```js
drawtree.js:365 Uncaught TypeError: Cannot read property 'region' of undefined
    at SVGRectElement.<anonymous> (drawtree.js:365)
    at SVGRectElement.<anonymous> (d3.js:3501)
    at Transition.selection_each [as each] (d3.js:1176)
    at tweenValue (d3.js:3499)
    at Transition.transition_style [as style] (d3.js:3884)
    at changeTreeColour (drawtree.js:362)
    at HTMLSelectElement.<anonymous> (drawtree.js:381)
    at HTMLSelectElement.dispatch (jquery.js:5429)
    at HTMLSelectElement.elemData.handle (jquery.js:5233)
> vis.selectAll("rect").data()
...
85: {parentId: 134, parentLabel: "NODE_0000064", thisId: 130, thisLabel: "B.1.369", children: Array(0), …}
86: {parentId: 133, parentLabel: "NODE_0000002", thisId: 131, thisLabel: "B.1.3", children: Array(0), …}
87: undefined
88: {parentId: 133, parentLabel: "NODE_0000002", thisId: 132, thisLabel: "B.1.3.1", children: Array(0), …}
```

**Comment by ArtPoon** [comment]
Above error is thrown when we switch dropdown back from any other value to "Region", running `gisaid_canada` data files locally.

**Comment by ArtPoon** [comment]
Should probably not propagate color scheme from tree to beadplot, since these will be on vastly different scales, e.g., number of samples.

**Comment by ArtPoon** [comment]
I think I resolved the `TypeError` bug: `changeTreeColour()` function in `drawtree.js` was pulling all the `rect` objects including the cluster box that is not associated with data (via d3).

**Comment by ArtPoon** [comment]
I wrote a small script to generate a reduced data provision file (limit 100 samples per lineage):
```python
import json
import lzma
from covizu.utils.seq_utils import fromisoformat
from datetime import date

handle = lzma.open('provision.2021-01-03T22:00:02.json.xz', 'rb')
outfile = lzma.open('testdata.xz', 'wb')

minlen = 29000
mindate = date(2019, 12, 1)

lineages = {}
for line in handle:
    record = json.loads(line)

    if record['covv_lineage'] is None:
        continue

    qname = record['covv_virus_name'].strip().replace(',', '_')  # issue #206
    country = qname.split('/')[1]
    if country == '' or country[0].islower():
        continue

    record['covv_virus_name'] = qname  # in case we removed whitespace

    seq = record['sequence'].replace('\n', '')
    if len(seq) < minlen:
        continue
    record['sequence'] = seq

    if record['covv_collection_date'].count('-') != 2:
        continue
    coldate = fromisoformat(record['covv_collection_date'])
    if coldate < mindate or coldate > date.today():
        continue

    lineage = record['covv_lineage']
    if lineage not in lineages:
        lineages.update({lineage: 0})

    lineages[lineage] += 1
    if lineages[lineage] < 100:
        _ = outfile.write(line)

outfile.close()
handle.close()
```

**Comment by ArtPoon** [comment]
Using the above test data set, I found that one of the lineages (B.1.5.35) had a very strange residual:
```python
>>> timetree, residuals = parse_nexus(nexus_file, fasta)
>>> values = [v for k, v in residuals.items()]
>>> min(values)
-0.1928559709380934
>>> max(values)
19.921912121709227
```

**Comment by ArtPoon** [comment]
```python
>>> with open(nexus_file) as handle:
...     for line in handle:
...         for m in pat.finditer(line):
...             node_name, branch_length, date_est = m.groups()
...             if node_name == 'B.1.5.35':
...                 print (date_est)
...                 
...                 coldate = coldates.get(node_name, None)  # internal nodes have no collection date
...                 print(coldate)
... 
2020.17
2020.914442162902
````
The genome we picked for lineage B.1.5.35 is highly *under*-evolved for its collection date.

**Comment by ArtPoon** [comment]
```python
>>> for row in by_lineage['B.1.5.35']:
...   print(row['covv_collection_date'])
...   print(len(row['diffs']))
... 
2020-05-27
9
2020-06-03
6
2020-06-11
11
2020-06-11
8
2020-06-12
8
2020-06-12
11
2020-06-13
14
2020-06-15
9
2020-06-15
17
2020-11-30
8
```

**Comment by ArtPoon** [comment]
Will this be fixed by #228 ?

**Comment by ArtPoon** [comment]
Excluding lower quantile seems to have fixed the above issue, thanks @gopigugan

**Comment by ArtPoon** [comment]
Colour palette switch is working but we do really need a legend for users to interpret.
Probably need to move around the inputs at the top of the page to accommodate this, and to relocate the drop-down (select) to the left side of the page so that it appears above the tree it affects.

**Comment by ArtPoon** [comment]
*nyohohoho!*

<img width="548" alt="Screen Shot 2021-01-20 at 9 43 51 PM" src="https://user-images.githubusercontent.com/1109328/105273113-a5b8a500-5b68-11eb-8f80-988371cb2385.png">

<img width="257" alt="Screen Shot 2021-01-20 at 9 45 11 PM" src="https://user-images.githubusercontent.com/1109328/105273184-c97beb00-5b68-11eb-89bf-1b5ac4676ffd.png">

<img width="257" alt="Screen Shot 2021-01-20 at 9 45 29 PM" src="https://user-images.githubusercontent.com/1109328/105273203-d39de980-5b68-11eb-9ea2-08846d5f0cb9.png">

<img width="257" alt="Screen Shot 2021-01-20 at 9 45 43 PM" src="https://user-images.githubusercontent.com/1109328/105273222-dac4f780-5b68-11eb-8cea-e92515c8d089.png">

**Comment by ArtPoon** [comment]
Closing, maybe peel off new issues for the last two concepts
