### ISSUE TITLE
NotADirectory error thrown by treetime.py

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#230]
```console
art@Wernstrom covizu % python3 covizu/treetime.py ~/Desktop/by_lineage.json --ref covizu/data/NC_045512.fa 
Traceback (most recent call last):
  File "covizu/treetime.py", line 250, in <module>
    args = parse_args()
  File "covizu/treetime.py", line 228, in parse_args
    default=open(os.path.join(covizu.__path__[0], "data/NC_045512.fa")),
NotADirectoryError: [Errno 20] Not a directory: '/Library/Python/3.8/site-packages/covizu-0.3-py3.8.egg/covizu/data/NC_045512.fa'
```

This might be a macOS-specific problem.

**Comment by ArtPoon** [comment]
Added an if..else in dev branch to catch case when package `__path__` points to egg (macOS), which is what raises the directory error.
