### ISSUE TITLE
Jan 31 job still running as of Feb 2

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#240]
File listing, sorted by mod date:
```
-rw-rw-r-- 1 covizu covizu   3461163 Feb  1 08:09 B.1.177.labels.csv
-rw-rw-r-- 1 covizu covizu   1060941 Feb  1 08:07 B.1.497.nwk
-rw-rw-r-- 1 covizu covizu     47198 Feb  1 08:07 B.1.497.labels.csv
-rw-rw-r-- 1 covizu covizu   1547500 Feb  1 08:02 B.1.361.nwk
-rw-rw-r-- 1 covizu covizu     73512 Feb  1 08:01 B.1.361.labels.csv
-rw-rw-r-- 1 covizu covizu    950718 Feb  1 07:57 B.1.279.nwk
-rw-rw-r-- 1 covizu covizu     82577 Feb  1 07:57 B.1.279.labels.csv
...
-rw-rw-r-- 1 covizu covizu   2045163 Jan 31 22:33 B.1.labels.csv
-rw-rw-r-- 1 covizu covizu   1579115 Jan 31 22:33 B.1.1.282.nwk
-rw-rw-r-- 1 covizu covizu     77592 Jan 31 22:32 B.1.1.282.labels.csv
-rw-rw-r-- 1 covizu covizu     28553 Jan 31 22:32 timetree.2021-01-31T22:00:08.nwk
-rw-rw-r-- 1 covizu covizu     50718 Jan 31 22:32 dates.tsv
-rw-rw-r-- 1 covizu covizu    143085 Jan 31 22:32 divergence_tree.nexus
-rw-rw-r-- 1 covizu covizu    141567 Jan 31 22:32 timetree.nexus
-rw-rw-r-- 1 covizu covizu  46228294 Jan 31 22:32 ancestral_sequences.fasta
-rw-rw-r-- 1 covizu covizu     61874 Jan 31 22:32 timetree.pdf
-rw-rw-r-- 1 covizu covizu        56 Jan 31 22:32 molecular_clock.txt
-rw-rw-r-- 1 covizu covizu       555 Jan 31 22:32 sequence_evolution_model.txt
-rw-r--r-- 1 covizu covizu 320431935 Jan 31 22:15 by_lineage.json
-rw-rw-r-- 1 covizu covizu         0 Jan 31 22:00 clusters.2021-01-31T22:00:08.json
-rw-rw-r-- 1 covizu covizu  45676596 Jan 31 21:19 provision.2021-01-31T22:00:09.json.xz
```

```console
[covizu@BEVi data]$ top -b -n1 -u covizu
top - 12:20:26 up 591 days, 22:22,  8 users,  load average: 15.34, 15.53, 15.57
Tasks: 1061 total,  78 running, 983 sleeping,   0 stopped,   0 zombie
%Cpu(s): 19.1 us, 31.6 sy,  0.0 ni, 49.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 65681620 total, 29162212 free, 32919756 used,  3599652 buff/cache
KiB Swap: 32964604 total,  3964656 free, 28999948 used. 31922676 avail Mem 

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 42475 covizu    20   0 2760192   1.5g   1756 R 100.0  2.4   1531:40 python3
 42461 covizu    20   0 2757932   1.5g   1840 R  94.4  2.4   1530:56 python3
 42465 covizu    20   0 2757936   1.5g   1872 R  94.4  2.4   1532:04 python3
 42471 covizu    20   0 2757928   1.5g   1760 R  94.4  2.4   1534:30 python3
 42479 covizu    20   0 2757928   1.5g   1932 R  94.4  2.4   1536:39 python3
 42484 covizu    20   0 2760196   1.5g   1896 R  94.4  2.4   1544:20 python3
 42487 covizu    20   0 2757928   1.5g   1948 R  94.4  2.4   1539:21 python3
 42489 covizu    20   0 2760220   1.5g   1960 R  94.4  2.4   1547:30 python3
152598 covizu    20   0 2755324   1.1g    156 R  94.4  1.7   2959:49 python3
152607 covizu    20   0 2755324   1.1g    216 R  94.4  1.7   2955:54 python3
152611 covizu    20   0 2755332 807708    220 R  94.4  1.2   2997:07 python3
152617 covizu    20   0 2757576   1.1g    216 R  94.4  1.7   2973:08 python3
152623 covizu    20   0 2755328 812828    216 R  94.4  1.2   2987:34 python3
152626 covizu    20   0 2755324   1.1g    216 R  94.4  1.7   2999:47 python3
152629 covizu    20   0 2755332 803352    212 R  94.4  1.2   2986:09 python3
152602 covizu    20   0 2755328 805956    216 R  88.9  1.2   2970:49 python3
 41698 covizu    20   0  162820   3060   1552 R   5.6  0.0   0:00.02 top
 40789 covizu    20   0  167716   2500   1080 S   0.0  0.0   0:00.03 sshd
 40801 covizu    20   0  116792   3428   1688 S   0.0  0.0   0:00.05 bash
 42441 covizu    20   0  397036   2952    204 S   0.0  0.0   0:01.26 mpirun
 42446 covizu    20   0   12740    196      0 S   0.0  0.0   0:00.00 bprsh
 42447 covizu    20   0   12740    196      0 S   0.0  0.0   0:00.00 bprsh
 42448 covizu    20   0   12740    192      0 S   0.0  0.0   0:00.01 bprsh
 42449 covizu    20   0  316768   4376      0 S   0.0  0.0   0:01.04 orted
 42450 covizu    20   0  316768   2420     20 S   0.0  0.0   0:00.77 orted
 42451 covizu    20   0  316768   2380     32 S   0.0  0.0   0:00.96 orted
 42462 covizu    20   0 1776612 187344    472 S   0.0  0.3  82:38.34 python3
 42463 covizu    20   0 3143028   1.5g    424 R   0.0  2.4   1474:45 python3
 42464 covizu    20   0 3167636   1.5g    468 R   0.0  2.4   1494:52 python3
 42466 covizu    20   0 3143072   1.5g    228 R   0.0  2.4   1564:30 python3
 42467 covizu    20   0 3167648   1.5g    388 R   0.0  2.4   1475:26 python3
 42468 covizu    20   0 3143040   1.5g    428 R   0.0  2.4   1485:10 python3
 42469 covizu    20   0 3169880   1.5g    392 R   0.0  2.4   1481:56 python3
 42470 covizu    20   0 1776868 185956    472 S   0.0  0.3  81:57.95 python3
 42472 covizu    20   0 1752000 185468    260 S   0.0  0.3  82:11.10 python3
 42473 covizu    20   0 3167648   1.5g    396 R   0.0  2.4   1492:22 python3
 42474 covizu    20   0 3143072   1.5g    228 R   0.0  2.4   1577:52 python3
 42476 covizu    20   0 3167636   1.5g    252 R   0.0  2.4   1470:11 python3
 42477 covizu    20   0 3143040   1.5g    384 R   0.0  2.4   1440:14 python3
 42478 covizu    20   0 3143060   1.5g    240 R   0.0  2.4   1554:45 python3
 42480 covizu    20   0 3167648   1.5g    252 R   0.0  2.4   1546:06 python3
 42481 covizu    20   0 1752256 185936    472 S   0.0  0.3  82:52.70 python3
 42482 covizu    20   0 3145324   1.5g    240 R   0.0  2.4   1568:19 python3
 42483 covizu    20   0 3167636   1.5g    420 R   0.0  2.4   1466:38 python3
 42485 covizu    20   0 3143040   1.5g    408 R   0.0  2.4   1451:37 python3
 42486 covizu    20   0 1776880 185872    388 S   0.0  0.3  97:12.02 python3
 42488 covizu    20   0 3167636   1.5g    240 R   0.0  2.4   1486:23 python3
 42490 covizu    20   0 3169924   1.5g    248 R   0.0  2.4   1501:16 python3
 42491 covizu    20   0 3143060   1.5g    240 R   0.0  2.4   1575:47 python3
 42492 covizu    20   0 1776612 187268    396 S   0.0  0.3 108:34.07 python3
 42493 covizu    20   0 3145332   1.5g    240 R   0.0  2.4   1555:03 python3
 42494 covizu    20   0 1776612 187656    388 S   0.0  0.3  81:02.98 python3
 42495 covizu    20   0 3145320   1.5g    236 R   0.0  2.4   1575:26 python3
 42496 covizu    20   0 3143060   1.5g    412 R   0.0  2.4   1579:21 python3
 42497 covizu    20   0 3145324   1.5g    404 R   0.0  2.4   1550:02 python3
 42498 covizu    20   0 3143072   1.5g    408 R   0.0  2.4   1563:26 python3
 56294 covizu    20   0  113176     60     56 S   0.0  0.0   0:00.01 sh
 56512 covizu    20   0 8663092    300    104 S   0.0  0.0 218:32.84 python3
 56585 covizu    20   0   89720      0      0 S   0.0  0.0   0:00.00 sendmail
 56586 covizu    20   0   89692     12     12 S   0.0  0.0   0:00.00 postdrop
121093 covizu    20   0  167716   2652   1192 S   0.0  0.0   0:17.65 sshd
121119 covizu    20   0  116912   3644   1800 S   0.0  0.0   0:00.08 bash
147228 covizu    20   0  113176    308     56 S   0.0  0.0   0:00.00 sh
147473 covizu    20   0 8531968   5.7g    104 S   0.0  9.1 191:42.82 python3
147561 covizu    20   0   89720    996      0 S   0.0  0.0   0:00.00 sendmail
147562 covizu    20   0   89692    992      0 S   0.0  0.0   0:00.00 postdrop
149396 covizu    20   0  162956   3340   1620 S   0.0  0.0   9:46.54 top
152578 covizu    20   0  397172      0      0 S   0.0  0.0   0:02.48 mpirun
152583 covizu    20   0   12740      4      0 S   0.0  0.0   0:00.02 bprsh
152584 covizu    20   0   12740      4      0 S   0.0  0.0   0:00.02 bprsh
152585 covizu    20   0   12740     24      0 S   0.0  0.0   0:00.01 bprsh
152586 covizu    20   0  316768   2336      0 S   0.0  0.0   0:01.51 orted
152587 covizu    20   0  316768   2344      8 S   0.0  0.0   0:01.15 orted
152588 covizu    20   0  316768   2336      0 S   0.0  0.0   0:01.57 orted
152599 covizu    20   0 3165032   1.5g    100 R   0.0  2.4   2989:42 python3
152600 covizu    20   0 3142952   1.5g     92 R   0.0  2.4   3026:16 python3
152601 covizu    20   0 1751992 186948     96 S   0.0  0.3 115:54.40 python3
152603 covizu    20   0 3167284   1.5g    100 R   0.0  2.4   2976:08 python3
152604 covizu    20   0 3142980   1.5g     92 R   0.0  2.4   3032:45 python3
152605 covizu    20   0 3140432   1.5g     16 R   0.0  2.4   2924:29 python3
152606 covizu    20   0 3165032   1.5g     96 R   0.0  2.4   2977:55 python3
152608 covizu    20   0 3140712   1.5g     92 R   0.0  2.4   3000:28 python3
152609 covizu    20   0 3165040   1.5g     96 R   0.0  2.4   2995:38 python3
152610 covizu    20   0 3142692   1.5g     16 R   0.0  2.4   2936:04 python3
152612 covizu    20   0 3167324   1.5g     96 R   0.0  2.4   2986:59 python3
152613 covizu    20   0 3140720   1.5g     88 R   0.0  2.4   3020:43 python3
152614 covizu    20   0 3140432   1.5g     16 R   0.0  2.4   2896:14 python3
152615 covizu    20   0 3165040   1.5g     96 R   0.0  2.4   2947:46 python3
152616 covizu    20   0 3142948   1.5g     88 R   0.0  2.4   3003:48 python3
152618 covizu    20   0 3140420   1.5g     92 R   0.0  2.4   2951:41 python3
152619 covizu    20   0 3165032   1.5g     96 R   0.0  2.4   2898:28 python3
152620 covizu    20   0 3140720   1.5g     88 R   0.0  2.4   3017:13 python3
152621 covizu    20   0 3140432   1.5g     12 R   0.0  2.4   2897:24 python3
152622 covizu    20   0 3165040   1.5g     96 R   0.0  2.4   2971:12 python3
152624 covizu    20   0 3142968   1.5g     88 R   0.0  2.4   3001:12 python3
152625 covizu    20   0 3165032   1.5g     96 R   0.0  2.4   2968:19 python3
152627 covizu    20   0 3140720   1.5g     88 R   0.0  2.4   3010:49 python3
152628 covizu    20   0 3165040   1.5g     96 R   0.0  2.4   2965:33 python3
152630 covizu    20   0 3142960   1.5g     96 R   0.0  2.4   2998:53 python3
152631 covizu    20   0 3142960   1.5g     92 R   0.0  2.4   3004:11 python3
152632 covizu    20   0 3142988   1.5g     92 R   0.0  2.4   3015:59 python3
152633 covizu    20   0 3140712   1.5g     92 R   0.0  2.4   2990:00 python3
152634 covizu    20   0 3140720   1.5g    100 R   0.0  2.4   3026:45 python3
152635 covizu    20   0 3140720   1.5g     92 R   0.0  2.4   2988:10 python3
```

**Comment by ArtPoon** [comment]
Something's clearly wrong, I'm going to have to kill this job

**Comment by ArtPoon** [comment]
Killing the job freed the error reporting system, crontab mail reveals memory allocation issues:
```
Optimize all lengths: LogLk = -116167.889 Time 380.25
    410.51 seconds: ML split tests for    100 of    859 internal splits
    441.73 seconds: ML split tests for    200 of    859 internal splits
    471.02 seconds: ML split tests for    300 of    859 internal splits
    501.46 seconds: ML split tests for    400 of    859 internal splits
    530.25 seconds: ML split tests for    500 of    859 internal splits
    557.52 seconds: ML split tests for    600 of    859 internal splits
    583.67 seconds: ML split tests for    700 of    859 internal splits
    614.27 seconds: ML split tests for    800 of    859 internal splits
Total time: 631.80 seconds Unique: 862/862 Bad splits: 0/859
Traceback (most recent call last):
  File "covizu/clustering.py", line 297, in <module>
    phy = bootstrap(union, indexed, args.binpath, callback=cb.callback)
  File "covizu/clustering.py", line 96, in bootstrap
    stdout = subprocess.check_output(cmd, stderr=subprocess.DEVNULL)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['rapidnj', '/tmp/cvz_boot_zh7iufor', '-i', 'pd
', '--no-negative-length']' died with <Signals.SIGKILL: 9>.
Traceback (most recent call last):
  File "covizu/clustering.py", line 297, in <module>
    phy = bootstrap(union, indexed, args.binpath, callback=cb.callback)
  File "covizu/clustering.py", line 96, in bootstrap
    stdout = subprocess.check_output(cmd, stderr=subprocess.DEVNULL)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['rapidnj', '/tmp/cvz_boot_39xqqcte', '-i', 'pd
', '--no-negative-length']' died with <Signals.SIGKILL: 9>.
Traceback (most recent call last):
  File "covizu/clustering.py", line 297, in <module>
    phy = bootstrap(union, indexed, args.binpath, callback=cb.callback)
  File "covizu/clustering.py", line 96, in bootstrap
    stdout = subprocess.check_output(cmd, stderr=subprocess.DEVNULL)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['rapidnj', '/tmp/cvz_boot_wf2djto2', '-i', 'pd
', '--no-negative-length']' died with <Signals.SIGKILL: 9>.
Traceback (most recent call last):
  File "covizu/clustering.py", line 297, in <module>
    phy = bootstrap(union, indexed, args.binpath, callback=cb.callback)
  File "covizu/clustering.py", line 96, in bootstrap
    stdout = subprocess.check_output(cmd, stderr=subprocess.DEVNULL)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['rapidnj', '/tmp/cvz_boot_ggjpwid7', '-i', 'pd
', '--no-negative-length']' died with <Signals.SIGKILL: 9>.
Traceback (most recent call last):
  File "covizu/clustering.py", line 297, in <module>
    phy = bootstrap(union, indexed, args.binpath, callback=cb.callback)
  File "covizu/clustering.py", line 96, in bootstrap
    stdout = subprocess.check_output(cmd, stderr=subprocess.DEVNULL)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['rapidnj', '/tmp/cvz_boot_ea5h3gtt', '-i', 'pd
', '--no-negative-length']' died with <Signals.SIGKILL: 9>.
Traceback (most recent call last):
  File "covizu/clustering.py", line 297, in <module>
    phy = bootstrap(union, indexed, args.binpath, callback=cb.callback)
  File "covizu/clustering.py", line 96, in bootstrap
    stdout = subprocess.check_output(cmd, stderr=subprocess.DEVNULL)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1295, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "covizu/clustering.py", line 297, in <module>
    phy = bootstrap(union, indexed, args.binpath, callback=cb.callback)
  File "covizu/clustering.py", line 96, in bootstrap
    stdout = subprocess.check_output(cmd, stderr=subprocess.DEVNULL)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['rapidnj', '/tmp/cvz_boot_f7bb06ba', '-i', 'pd
', '--no-negative-length']' died with <Signals.SIGKILL: 9>.
/bin/sh: line 1: 147473 Killed                  python3 batch.py >> ~/batch.log
```

**Comment by ArtPoon** [comment]
Installed new node today, but haven't been able to boot it into the cluster yet.
Testing dev branch:
```console
[covizu@BEVi covizu]$ nohup python3 batch.py data/provision.2021-01-31T22\:00\:09.json.xz --mmthreads 8 --ftbin fasttree2-mp --njthreads 8 &
```

**Comment by ArtPoon** [comment]
Whoop, that command is outdated:
```console
[covizu@BEVi covizu]$ nohup python3 batch.py --infile data/provision.2021-01-31T22\:00\:09.json.xz --mmthreads 8 --ft2bin fasttree2-mp &
```

**Comment by ArtPoon** [comment]
Forgot to set `--dry-run` flag to prevent script from transferring data files to webserver.
New command:
```
nohup python3 batch.py --infile data/provision.2021-01-31T22\:00\:09.json.xz --dry-run &
```

**Comment by ArtPoon** [comment]
Ran successfully in about 22 hours - we really need that other server online.
