### ISSUE TITLE
epicov branch

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#244]
Feature addition for GISAID EpiCoV branch:
* [x] annotate samples by age and gender (in tooltip for beads)
* [x] use GISAID location instead of country to region map, see #205 
* [x] enable HTTPS (SSL certificate)
* [ ] require user to connect via HTTPS
* [x] check for valid session ID

**Comment by ArtPoon** [comment]
Pushed new branch `epicov` to repo

**Comment by ArtPoon** [comment]
Use `testdata.xz` on Orolo

**Comment by ArtPoon** [comment]
```console
art@orolo:~/git/covizu$ python3 batch.py --dry-run --infile working/testdata.xz --ft2bin fasttree
🏄 [0:36:56.929693] All done!
```

Screwed up, forgot that adding `location` changes index of `accession` in pipe-delimited labels:
```json
[{"nodes": {
"unsampled0": [], 
"Asia / China / Shandong / Qingdao": [["2020-01-19", "Asia / China / Shandong / Qingdao", "EPI_ISL_408482", "hCoV-19/Shandong/IVDC-SD-001/2020"]], 
"Asia / China / Hubei / Wuhan": [["2019-12-30", "Asia / China / Hubei / Wuhan", "EPI_ISL_402127", "hCoV-19/Wuhan/WIV02/2019"]], 
"Asia / Singapore": [["2020-02-02", "Asia / Singapore", "EPI_ISL_410719", "hCoV-19/Singapore/11/2020"]],
```

**Comment by ArtPoon** [comment]
Problem with lineage with only one variant:
```
🏄 [0:11:30.682536] start B.1.76, 2 entries
Traceback (most recent call last):
  File "batch.py", line 137, in <module>
    result = make_beadplots(by_lineage, args, cb.callback, t0=cb.t0.timestamp())
  File "/home/art/git/covizu/covizu/utils/batch_utils.py", line 84, in make_beadplots
    beaddict = beadplot_serial(lineage, features, args)
  File "/home/art/git/covizu/covizu/utils/batch_utils.py", line 32, in beadplot_serial
    variant = labels[0]['accession']  # use earliest sample as key
TypeError: list indices must be integers or slices, not str
```

**Comment by ArtPoon** [comment]
Script runs without errors, but output still contains dicts and not lists:
```json
[{"nodes": 
{"EPI_ISL_426179": [
  {"name": "hCoV-19/India/UN-c31/2020", "coldate": 
"2020-03-02", "location": "Asia / India", "accession": "EPI_ISL_426179", "gender
": "Male", "age": "15", "status": "unknown"}, 
  {"name": "hCoV-19/Scotland/EDB057/
2020", "coldate": "2020-03-18", "location": "Europe / United Kingdom / Scotland"
, "accession": "EPI_ISL_425861", "gender": "unknown", "age": "unknown", "status"
: "unknown"}, 
  {"name": "hCoV-19/Iceland/464/2020", "coldate": "2020-03-20", "loc
ation": "Europe / Iceland / Reykjavik", "accession": "EPI_ISL_424487", "gender":
 "Female", "age": "48", "status": "unknown"},
```

**Comment by ArtPoon** [comment]
Seems to be working now:
```
[{"nodes": {"EPI_ISL_426179": [["hCoV-19/India/UN-c31/2020", "EPI_ISL_426179", "Asia / India", "2020-03-02", "Male", "15", "unknown"]
```

**Comment by ArtPoon** [comment]
Try replacing all `unknown` values with empty string to reduce file size.
Clusters JSON on test file `working/reduced.2021-02-15.json.xz` is currently 1990471 bytes.

**Comment by ArtPoon** [comment]
`Number of cases` has no value in tooltips

**Comment by ArtPoon** [comment]
Got table populated with metadata
Also trying to provide visual feedback, when user mouseovers a table row, the corresponding bead is highlighted - however this is not working for rows that represent samples subsumed into a larger bead (multiple samples in same bead).  Not sure how to deal with this.

**Comment by ArtPoon** [comment]
I think I need to pass the `variant` field from `beaddata.points` to the table row level, preferably without displaying it.

**Comment by ArtPoon** [comment]
Replace with #246

**Comment by ArtPoon** [comment]
Reopening, need to require users to connect to epicov site via HTTPS

**Comment by ArtPoon** [comment]
Need to write a script that modifies `clusters.json` to `epicov` format by drawing information from provision `xz` file.  This would make our lives easier!
