### ISSUE TITLE
Pipeline crash 2021-05-23

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#289]
```console
[covizu@BEVi ~]$ tail -n100 batch.log
🏄 [1:39:19.761458] start B.1.1, 27565 entries
🏄 [1:39:26.710090][0/42] loading JSON
🏄 [1:39:26.710209][1/42] loading JSON

...

🏄 [1:39:26.711364][2/42] loading JSON
🏄 [1:39:26.711540][3/42] loading JSON
--------------------------------------------------------------------------
mpirun noticed that process rank 12 with PID 96380 on node n1 exited on signal 9 (Killed).
--------------------------------------------------------------------------
4 total processes killed (some possibly by mpirun during cleanup)
--------------------------------------------------------------------------
mpirun noticed that process rank 38 with PID 94191 on node n3 exited on signal 9 (Killed).
--------------------------------------------------------------------------
2 total processes killed (some possibly by mpirun during cleanup)
```

**Comment by ArtPoon** [comment]
Checked `mail` from `cron`:

```console
 N 92 (Cron Daemon)         Sun May 23 01:45 5102/388757 "Cron <covizu@BEVi> source "
& 92          
Message 92:
From covizu@BEVi.localdomain  Sun May 23 01:45:37 2021
Return-Path: <covizu@BEVi.localdomain>
X-Original-To: covizu
Delivered-To: covizu@BEVi.localdomain
From: "(Cron Daemon)" <covizu@BEVi.localdomain>
To: covizu@BEVi.localdomain
Subject: Cron <covizu@BEVi> source /home/covizu/.bashrc; cd /home/covizu/covizu; module
 load openmpi/gnu; python3 batch.py >> ~/batch.log
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <XDG_SESSION_ID=15395>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/1011>
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/share/pvm3/lib
:/home/covizu/.local/bin:/home/covizu/bin>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/home/covizu>
X-Cron-Env: <LOGNAME=covizu>
X-Cron-Env: <USER=covizu>
Date: Sat, 22 May 2021 00:00:03 -0400 (EDT)
Status: R

--2021-05-22 00:00:03--  https://www.epicov.org/epi3/3p/uwo/export/provision.json.xz

...

[n3][[26945,1],37][btl_tcp_endpoint.c:599:mca_btl_tcp_endpoint_recv_blocking] recv(19, 
0/8) failed: Connection reset by peer (104)
[n3:94190] pml_ob1_sendreq.c:189 FATAL
[n3][[26945,1],41][btl_tcp_endpoint.c:599:mca_btl_tcp_endpoint_recv_blocking] recv(21, 
0/8) failed: Connection reset by peer (104)
[n3][[26945,1],27][btl_tcp_endpoint.c:599:mca_btl_tcp_endpoint_recv_blocking] recv(22, 
0/8) failed: Connection reset by peer (104)
[n3:94107] pml_ob1_sendreq.c:189 FATAL
[n3:94194] pml_ob1_sendreq.c:189 FATAL
[n3][[26945,1],31][btl_tcp_endpoint.c:599:mca_btl_tcp_endpoint_recv_blocking] recv(20, 
0/8) failed: Connection reset by peer (104)
[n3:94158] pml_ob1_sendreq.c:189 FATAL
Traceback (most recent call last):
  File "batch.py", line 139, in <module>
    result = make_beadplots(by_lineage, args, cb.callback, t0=cb.t0.timestamp())
  File "/home/covizu/covizu/covizu/utils/batch_utils.py", line 102, in make_beadplots
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpirun', '--machinefile', 'mfile', 'python3',
 'covizu/clustering.py', 'data/by_lineage.json', 'B.1.427', '--nboot', '100', '--outdir
', 'data', '--timestamp', '1621656003.098403']' returned non-zero exit status 137.
```

**Comment by ArtPoon** [comment]
Checked `mail` from `cron`:

```console
 N 92 (Cron Daemon)         Sun May 23 01:45 5102/388757 "Cron <covizu@BEVi> source "
& 92          
Message 92:
From covizu@BEVi.localdomain  Sun May 23 01:45:37 2021
Return-Path: <covizu@BEVi.localdomain>
X-Original-To: covizu
Delivered-To: covizu@BEVi.localdomain
From: "(Cron Daemon)" <covizu@BEVi.localdomain>
To: covizu@BEVi.localdomain
Subject: Cron <covizu@BEVi> source /home/covizu/.bashrc; cd /home/covizu/covizu; module
 load openmpi/gnu; python3 batch.py >> ~/batch.log
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <XDG_SESSION_ID=15395>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/1011>
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/share/pvm3/lib
:/home/covizu/.local/bin:/home/covizu/bin>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/home/covizu>
X-Cron-Env: <LOGNAME=covizu>
X-Cron-Env: <USER=covizu>
Date: Sat, 22 May 2021 00:00:03 -0400 (EDT)
Status: R

...

[n3][[26945,1],37][btl_tcp_endpoint.c:599:mca_btl_tcp_endpoint_recv_blocking] recv(19, 
0/8) failed: Connection reset by peer (104)
[n3:94190] pml_ob1_sendreq.c:189 FATAL
[n3][[26945,1],41][btl_tcp_endpoint.c:599:mca_btl_tcp_endpoint_recv_blocking] recv(21, 
0/8) failed: Connection reset by peer (104)
[n3][[26945,1],27][btl_tcp_endpoint.c:599:mca_btl_tcp_endpoint_recv_blocking] recv(22, 
0/8) failed: Connection reset by peer (104)
[n3:94107] pml_ob1_sendreq.c:189 FATAL
[n3:94194] pml_ob1_sendreq.c:189 FATAL
[n3][[26945,1],31][btl_tcp_endpoint.c:599:mca_btl_tcp_endpoint_recv_blocking] recv(20, 
0/8) failed: Connection reset by peer (104)
[n3:94158] pml_ob1_sendreq.c:189 FATAL
Traceback (most recent call last):
  File "batch.py", line 139, in <module>
    result = make_beadplots(by_lineage, args, cb.callback, t0=cb.t0.timestamp())
  File "/home/covizu/covizu/covizu/utils/batch_utils.py", line 102, in make_beadplots
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpirun', '--machinefile', 'mfile', 'python3',
 'covizu/clustering.py', 'data/by_lineage.json', 'B.1.427', '--nboot', '100', '--outdir
', 'data', '--timestamp', '1621656003.098403']' returned non-zero exit status 137.
```

**Comment by ArtPoon** [comment]
Not sure what's happening here - whether it's B.1.1 or B.1.427 that caused problems - neither one of them have enough variants to cause an out-of-memory error.  There doesn't seem to be any other jobs running on the cluster that might have caused problems either.

**Comment by ArtPoon** [comment]
Checking `/var/log/messages` (archived):
```console
May 23 01:40:02 n3 [7456668.476936] python3 invoked oom-killer: gfp_mask=0x280da, order=0, oom_score_adj=0
May 23 01:40:02 n3 [7456668.477337] python3 cpuset=/ mems_allowed=0-1
May 23 01:40:02 n3 [7456668.477580] CPU: 37 PID: 96450 Comm: python3 Tainted: G           OE  ------------   3.10.0-1160.15.2.el7.792g0000.x86_64 #1

...

May 23 01:40:04 n3 [7456668.526985] Out of memory: Kill process 94191 (python3) score 36 or sacrifice child
May 23 01:40:04 n3 [7456668.527385] Killed process 94191 (python3), UID 1011, total-vm:9143392kB, anon-rss:7142588kB, file-rss:4kB, shmem-rss:6448kB
```
Not seeing any other processes on the nodes.

**Comment by ArtPoon** [comment]
Manually restarted pipeline.  The crash seemed to occur right after reconstructing the time-scaled tree (first variant), so it shouldn't take long to reproduce the problem.

**Comment by ArtPoon** [comment]
Crashed again:
```console
[covizu@BEVi ~]$ tail batch.log
🏄 [2:14:55.560765][37/42] loading JSON
🏄 [2:14:56.333260][4/42] loading JSON
🏄 [2:14:56.333740][0/42] loading JSON
--------------------------------------------------------------------------
mpirun noticed that process rank 20 with PID 21749 on node n2 exited on signal 9 (Killed).
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 20 with PID 17666 on node n2 exited on signal 9 (Killed).
--------------------------------------------------------------------------
2 total processes killed (some possibly by mpirun during cleanup)
```

Checking `mail`:
```
>N 94 (Cron Daemon)         Sun May 30 02:20 4726/360509 "Cron <covizu@BEVi> sour"
 N 95 (Cron Daemon)         Sun May 30 02:29 4683/357088 "Cron <covizu@BEVi> sour"
```

94:
```python
Total time: 783.08 seconds Unique: 1285/1285 Bad splits: 0/1282
Traceback (most recent call last):
  File "batch.py", line 142, in <module>
    result = make_beadplots(by_lineage, args, cb.callback, t0=cb.t0.timestamp())
  File "/home/covizu/covizu/covizu/utils/batch_utils.py", line 103, in make_beadplot
s
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpirun', '--machinefile', 'mfile', 'python
3', 'covizu/clustering.py', 'data/by_lineage.json', 'B.1.1', '--nboot', '100', '--ou
tdir', 'data', '--timestamp', '1622347209.871848']' returned non-zero exit status 13
7.
```

95:
```
Total time: 724.79 seconds Unique: 1286/1286 Bad splits: 0/1283
Traceback (most recent call last):
  File "batch.py", line 142, in <module>
    result = make_beadplots(by_lineage, args, cb.callback, t0=cb.t0.timestamp())
  File "/home/covizu/covizu/covizu/utils/batch_utils.py", line 103, in make_beadplot
s
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpirun', '--machinefile', 'mfile', 'python
3', 'covizu/clustering.py', 'data/by_lineage.json', 'B.1.429', '--nboot', '100', '--
outdir', 'data', '--timestamp', '1622260802.827299']' returned non-zero exit status 
137.
```

**Comment by ArtPoon** [comment]
`/var/log/messages-20210530`:
```console
May 30 02:17:17 n3 [8062216.674782] INFO: task python3:21729 blocked for more than 120 seconds.
May 30 02:17:17 n3 [8062216.675028] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
May 30 02:17:17 n3 [8062216.675409] python3         D ffff8817def1acc0     0 21729  21416 0x00000080
May 30 02:17:17 n3 [8062216.675969] Call Trace:

...

May 30 02:19:03 n2 [8329022.262391] python3 invoked oom-killer: gfp_mask=0x280da, order=0, oom_score_adj=0
May 30 02:19:03 n2 [8329022.271044] python3 cpuset=/ mems_allowed=0-1
May 30 02:19:03 n2 [8329022.276102] CPU: 25 PID: 21767 Comm: python3 Tainted: G           OE  ------------   3.10.0-1160.15.2.el7.792g0000.x86_64 #1
May 30 02:19:03 n2 [8329022.288829] Hardware name: Intel Corporation S2600WTTR/S2600WTTR, BIOS SE5C610.86B.01.01.0016.033120161139 03/31/2016
May 30 02:19:03 n2 [8329022.300868] Call Trace:

```

**Comment by ArtPoon** [comment]
```console
[covizu@BEVi covizu]$ cat mfile
BEVi slots=6 max_slots=32
n0 slots=4 max_slots=56
n1 slots=8 max_slots=56
n2 slots=8 max_slots=56
n3 slots=16 max_slots=80
```
Try reducing `n3` to 12 slots.

**Comment by ArtPoon** [comment]
See if using Slurm can prevent this from happening:
https://www.penguincomputing.com/documentation/scyld-clusterware/7/admin-guide/admin-guide/batching.html?highlight=slurm

**Comment by ArtPoon** [comment]
Pipeline crashed again:
```console
[covizu@BEVi ~]$ tail batch.log -n30
🏄 [23:01:59.832668][0/38] Writing distance matrix to temporary file
🏄 [23:01:59.849444][4/38] Writing distance matrix to temporary file
🏄 [23:01:59.973474][2/38] Writing distance matrix to temporary file
🏄 [23:02:00.410322][1/38] Writing distance matrix to temporary file
🏄 [23:02:00.511979][5/38] Writing distance matrix to temporary file
🏄 [23:02:00.628119][3/38] Writing distance matrix to temporary file
[BEVi][[21914,1],3][btl_tcp_endpoint.c:800:mca_btl_tcp_endpoint_complete_connect] connect() to 172.16.128.10 failed: No route to host (113)
[BEVi][[21914,1],4][btl_tcp_endpoint.c:800:mca_btl_tcp_endpoint_complete_connect] connect() to 172.16.128.10 failed: No route to host (113)
[BEVi][[21914,1],5][btl_tcp_endpoint.c:800:mca_btl_tcp_endpoint_complete_connect] connect() to 172.16.128.10 failed: No route to host (113)
--------------------------------------------------------------------------
ORTE has lost communication with a remote daemon.

  HNP daemon   : [[21914,0],0] on node BEVi
  Remote daemon: [[21914,0],1] on node n0

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
--------------------------------------------------------------------------
mpirun: abort is already in progress...hit ctrl-c again to forcibly terminate

Traceback (most recent call last):
  File "batch.py", line 142, in <module>
    result = make_beadplots(by_lineage, args, cb.callback, t0=cb.t0.timestamp())
  File "/home/covizu/covizu/covizu/utils/batch_utils.py", line 103, in make_beadplots
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpirun', '--machinefile', 'mfile', 'python3', 'covizu/clustering.py', 'data/by_lineage.json', 'B.1.1.311', '--nboot', '100', '--outdir', 'data', '--timestamp', '1623549269.025155']' returned non-zero exit status 1.
```

**Comment by ArtPoon** [comment]
Try reproducing problem using command from above error message, with cached `data/by_lineage.json` file.

**Comment by ArtPoon** [comment]
```console
[covizu@BEVi covizu]$ mpirun --machinefile mfile python3 covizu/clustering.py data/by_lineage.json B.1.1.311 --nboot 100 --outdir data --timestamp 1623549269.025155
🏄 [1 day, 12:43:19.659363][0/38] loading JSON
🏄 [1 day, 12:43:19.659364][4/38] loading JSON
🏄 [1 day, 12:43:19.659382][1/38] loading JSON
...
🏄 [1 day, 12:45:34.725809][15/38] Writing distance matrix to temporary file
🏄 [1 day, 12:45:34.866690][17/38] Writing distance matrix to temporary file
[covizu@BEVi covizu]$ 
```
ran with no issues

**Comment by ArtPoon** [comment]
@GopiGugan to restart pipeline while testing issue #264

**Comment by ArtPoon** [comment]
Pipeline died again.
```console
🏄 [23:38:32.443797][1/38] Writing distance matrix to temporary file
🏄 [23:38:32.551652][3/38] Writing distance matrix to temporary file
[BEVi][[63694,1],2][btl_tcp_endpoint.c:800:mca_btl_tcp_endpoint_complete_connect] connect() to 172.16.128.11 failed: No route to host (113)
[BEVi][[63694,1],3][btl_tcp_endpoint.c:800:mca_btl_tcp_endpoint_complete_connect] connect() to 172.16.128.11 failed: No route to host (113)
[BEVi][[63694,1],4][btl_tcp_endpoint.c:800:mca_btl_tcp_endpoint_complete_connect] connect() to 172.16.128.11 failed: No route to host (113)
[BEVi][[63694,1],5][btl_tcp_endpoint.c:800:mca_btl_tcp_endpoint_complete_connect] connect() to 172.16.128.11 failed: No route to host (113)
[n0][[63694,1],6][btl_tcp_endpoint.c:800:mca_btl_tcp_endpoint_complete_connect] connect() to 172.16.128.11 failed: No route to host (113)
[n0][[63694,1],7][btl_tcp_endpoint.c:800:mca_btl_tcp_endpoint_complete_connect] connect() to 172.16.128.11 failed: No route to host (113)
[n0][[63694,1],8][btl_tcp_endpoint.c:800:mca_btl_tcp_endpoint_complete_connect] connect() to 172.16.128.11 failed: No route to host (113)
[n0][[63694,1],9][btl_tcp_endpoint.c:800:mca_btl_tcp_endpoint_complete_connect] connect() to 172.16.128.11 failed: No route to host (113)
--------------------------------------------------------------------------
ORTE has lost communication with a remote daemon.

  HNP daemon   : [[63694,0],0] on node BEVi
  Remote daemon: [[63694,0],2] on node n1

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
--------------------------------------------------------------------------
```
@GopiGugan

**Comment by ArtPoon** [comment]
Uh oh, looks like some of the compute nodes rebooted:

```console
Jun 15 11:21:12 n0 [138228.265329] CPU45: Package temperature/speed normal
Jun 15 11:24:26 n1 bpslave-0: Ping timeout after 64 seconds - lost connection to master?
Jun 15 11:24:26 n1 bpslave-0: Unmounting filesystems
Jun 15 11:24:26 n1 bpslave-0:  umount '/home' detached (is busy)
Jun 15 11:24:26 n1 bpslave-0:  umount '/opt' detached (is busy)
Jun 15 11:24:26 n1 bpslave-0:  umount '/usr/bin' detached (is busy)
Jun 15 11:24:26 n1 bpslave-0:  umount '/usr/lib64/python3.6' detached (is busy)
Jun 15 11:24:26 n1 bpslave-0:  umount '/usr/local/bin' detached (is busy)
Jun 15 11:24:26 n1 bpslave-0:  umount '/usr/local/lib' detached (is busy)
Jun 15 11:24:26 n1 bpslave-0:  umount '/usr/local/lib64/R' detached (is busy)
Jun 15 11:24:26 n1 bpslave: read_master_set: slave 0 exited
Jun 15 11:24:26 n1 bpslave: All slaves exited...  manager exiting.
Jun 15 11:24:26 n2 bpslave-0: Ping timeout after 64 seconds - lost connection to master?
Jun 15 11:24:26 n2 bpslave-0: Unmounting filesystems
Jun 15 11:24:26 n2 bpslave-0:  umount '/home' detached (is busy)
Jun 15 11:24:26 n2 bpslave-0:  umount '/opt' detached (is busy)
Jun 15 11:24:26 n2 bpslave-0:  umount '/usr/bin' detached (is busy)
Jun 15 11:24:27 n2 bpslave-0:  umount '/usr/lib64/python3.6' detached (is busy)
Jun 15 11:24:27 n2 bpslave-0:  umount '/usr/local/bin' detached (is busy)
Jun 15 11:24:27 n2 bpslave-0:  umount '/usr/local/lib' detached (is busy)
Jun 15 11:24:27 n2 bpslave-0:  umount '/usr/local/lib64/R' detached (is busy)
Jun 15 11:24:27 n2 bpslave: read_master_set: slave 0 exited
Jun 15 11:24:27 n2 bpslave: All slaves exited...  manager exiting.
Jun 15 11:24:35 BEVi bpmaster-main: lost connection to slave 2 on read
Jun 15 11:24:37 BEVi bpmaster-main: lost connection to slave 1 on read
...
Jun 15 11:24:39 BEVi bpmaster-main: write_ghost_request: missing ghost 65801 for msg resp type:8 from=3,65801 result=67344
Jun 15 11:25:33 BEVi beoserv: NODESTATUS 2 dhcp-pxe Assign 172.16.128.12 for PXE BIOS from A4:BF:01:48:A1:BD
Jun 15 11:25:33 BEVi beoserv: NODESTATUS 2 tftp-file TFTP download /var/beowulf/boot/pxelinux.0
Jun 15 11:25:33 BEVi beoserv: NODESTATUS 2 tftp-file TFTP download /var/beowulf/boot/pxelinux.cfg/default
Jun 15 11:25:33 BEVi beoserv: NODESTATUS 2 tftp-kernel TFTP download /boot/vmlinuz-3.10.0-1160.15.2.el7.792g0000.x86_64
Jun 15 11:25:34 BEVi beoserv: NODESTATUS 2 tftp-initrd TFTP download /var/beowulf/boot/computenode.initrd
Jun 15 11:25:39 BEVi beoserv: NODESTATUS 1 dhcp-pxe Assign 172.16.128.11 for PXE BIOS from A4:BF:01:4B:2A:73
Jun 15 11:25:39 BEVi beoserv: NODESTATUS 1 tftp-file TFTP download /var/beowulf/boot/pxelinux.0
Jun 15 11:25:39 BEVi beoserv: NODESTATUS 1 tftp-file TFTP download /var/beowulf/boot/pxelinux.cfg/default
Jun 15 11:25:39 BEVi beoserv: NODESTATUS 1 tftp-kernel TFTP download /boot/vmlinuz-3.10.0-1160.15.2.el7.792g0000.x86_64
Jun 15 11:25:40 BEVi beoserv: NODESTATUS 1 tftp-initrd TFTP download /var/beowulf/boot/computenode.initrd
Jun 15 11:26:01 BEVi beoserv: NODESTATUS 2 dhcp-beoboot Assign 172.16.128.12 for BeoBoot from A4:BF:01:48:A1:BD A4:BF:01:48:A1:BE
Jun 15 11:26:06 172.16.128.12  [   29.825249] ixgbe 0000:03:00.0 eth0: NIC Link is Up 1 Gbps, Flow Control: None
```

**Comment by ArtPoon** [comment]
Going to open a ticket with Penguin

**Comment by ArtPoon** [comment]
```console
[covizu@BEVi covizu]$ tail issue264.log -n30
🏄 [23:38:32.191079][5/38] Writing distance matrix to temporary file
🏄 [23:38:32.443797][1/38] Writing distance matrix to temporary file
🏄 [23:38:32.551652][3/38] Writing distance matrix to temporary file
[BEVi][[63694,1],2][btl_tcp_endpoint.c:800:mca_btl_tcp_endpoint_complete_connect] connect() to 172.16.128.11 failed: No route to host (113)
[BEVi][[63694,1],3][btl_tcp_endpoint.c:800:mca_btl_tcp_endpoint_complete_connect] connect() to 172.16.128.11 failed: No route to host (113)
[BEVi][[63694,1],4][btl_tcp_endpoint.c:800:mca_btl_tcp_endpoint_complete_connect] connect() to 172.16.128.11 failed: No route to host (113)
[BEVi][[63694,1],5][btl_tcp_endpoint.c:800:mca_btl_tcp_endpoint_complete_connect] connect() to 172.16.128.11 failed: No route to host (113)
[n0][[63694,1],6][btl_tcp_endpoint.c:800:mca_btl_tcp_endpoint_complete_connect] connect() to 172.16.128.11 failed: No route to host (113)
[n0][[63694,1],7][btl_tcp_endpoint.c:800:mca_btl_tcp_endpoint_complete_connect] connect() to 172.16.128.11 failed: No route to host (113)
[n0][[63694,1],8][btl_tcp_endpoint.c:800:mca_btl_tcp_endpoint_complete_connect] connect() to 172.16.128.11 failed: No route to host (113)
[n0][[63694,1],9][btl_tcp_endpoint.c:800:mca_btl_tcp_endpoint_complete_connect] connect() to 172.16.128.11 failed: No route to host (113)
--------------------------------------------------------------------------
ORTE has lost communication with a remote daemon.

  HNP daemon   : [[63694,0],0] on node BEVi
  Remote daemon: [[63694,0],2] on node n1

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "batch.py", line 142, in <module>
    result = make_beadplots(by_lineage, args, cb.callback, t0=cb.t0.timestamp())
  File "/home/covizu/covizu/covizu/utils/batch_utils.py", line 105, in make_beadplots
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpirun', '--machinefile', 'mfile', 'python3', 'covizu/clustering.py', 'data/by_lineage.json', 'B.1.177.44', '--nboot', '100', '--outdir', 'data', '--binpath', 'rapidnj', '--timestamp', '1623685578.234581']' died with <Signals.SIGKILL: 9>.
```

**Comment by ArtPoon** [comment]
Advice from Penguin is add following line to `/etc/beowulf/config`:
```
pingtimeout 60   # for 60 seconds
```
To increase this setting from the default timeout of 16 seconds.  Head node and compute node exchange "are you there" signals every 4 seconds.  If network switch is overwhelmed with MPI transactions, then may be a small but substantial chance of a node failing all four checks and being treated as "down".

After modifying the `config` file, run ``systemctl reload clusterware` to propagate the updated timeout setting to all compute nodes (by reading the revised `/etc/beowulf/config` file).

Right now we are running the pipeline with `maxcount` set to `5000`.  Whether this finishes successfully or not, we can do the above steps after completion.

**Comment by ArtPoon** [comment]
```
Jun 16 15:54:41 n2 bpslave-0: Ping timeout after 64 seconds - lost connection to mas
ter?
Jun 16 15:54:41 n2 bpslave-0: Unmounting filesystems
Jun 16 15:54:41 n2 bpslave-0:  umount '/home' detached (is busy)
Jun 16 15:54:41 n2 bpslave-0:  umount '/opt' detached (is busy)
Jun 16 15:54:41 n2 bpslave-0:  umount '/usr/bin' detached (is busy)
Jun 16 15:54:41 n2 bpslave-0:  umount '/usr/lib64/python3.6' detached (is busy)
Jun 16 15:54:41 n0 bpslave-0: Ping timeout after 64 seconds - lost connection to mas
ter?
Jun 16 15:54:41 n2 bpslave-0:  umount '/usr/local/bin' detached (is busy)
Jun 16 15:54:41 n0 bpslave-0: Unmounting filesystems
Jun 16 15:54:41 n0 bpslave-0:  umount '/home' detached (is busy)
Jun 16 15:54:41 n0 bpslave-0:  umount '/opt' detached (is busy)
Jun 16 15:54:41 n2 bpslave-0:  umount '/usr/local/lib' detached (is busy)
Jun 16 15:54:41 n0 bpslave-0:  umount '/usr/bin' detached (is busy)
Jun 16 15:54:41 n2 bpslave-0:  umount '/usr/local/lib64/R' detached (is busy)
Jun 16 15:54:41 n2 bpslave: read_master_set: slave 0 exited
Jun 16 15:54:41 n2 bpslave: All slaves exited...  manager exiting.
Jun 16 15:54:41 n0 bpslave-0:  umount '/usr/lib64/python3.6' detached (is busy)
Jun 16 15:54:41 n0 bpslave-0:  umount '/usr/local/bin' detached (is busy)
Jun 16 15:54:41 n0 bpslave-0:  umount '/usr/local/lib' detached (is busy)
Jun 16 15:54:41 n0 bpslave-0:  umount '/usr/local/lib64/R' detached (is busy)
Jun 16 15:54:41 n0 bpslave: read_master_set: slave 0 exited
Jun 16 15:54:41 n0 bpslave: All slaves exited...  manager exiting.
Jun 16 15:54:41 n1 bpslave-0: Ping timeout after 64 seconds - lost connection to mas
ter?
Jun 16 15:54:41 n1 bpslave-0: Unmounting filesystems
Jun 16 15:54:41 n1 bpslave-0:  umount '/home' detached (is busy)
Jun 16 15:54:41 n1 bpslave-0:  umount '/opt' detached (is busy)
Jun 16 15:54:41 n1 bpslave-0:  umount '/usr/bin' detached (is busy)
Jun 16 15:54:41 n1 bpslave-0:  umount '/usr/lib64/python3.6' detached (is busy)
Jun 16 15:54:41 n1 bpslave-0:  umount '/usr/local/bin' detached (is busy)
Jun 16 15:54:41 n1 bpslave-0:  umount '/usr/local/lib' detached (is busy)
Jun 16 15:54:41 n1 bpslave-0:  umount '/usr/local/lib64/R' detached (is busy)
Jun 16 15:54:41 n1 bpslave: read_master_set: slave 0 exited
Jun 16 15:54:41 n1 bpslave: All slaves exited...  manager exiting.
```

**Comment by ArtPoon** [comment]
This last crash is associated with lineage B.1.177.82:
```
🏄 [1 day, 0:30:15.545223] start B.1.177.82, 1535 entries
```
This is the *same* lineage that caused problems in a previous run (`issue264a.log`).  However, the crash before *that* was caused by lineage B.1.177.44 (`issue264.log`).

**Comment by ArtPoon** [comment]
Modifying the timeout did not work:
```
🏄 [6:31:25.849737][19/38] Writing distance matrix to temporary file
bpsh: Child process exit abnormally.
bpsh: Child process exit abnormally.
bpsh: Child process exit abnormally.
bpsh: Child process exit abnormally.
...
🏄 [6:34:50.018325][2/38] Writing distance matrix to temporary file
[BEVi][[65224,1],5][btl_tcp_endpoint.c:800:mca_btl_tcp_endpoint_complete_connect] connect() to 172.16.128.10 failed: Connection refused (111)
[BEVi][[65224,1],4][btl_tcp_endpoint.c:800:mca_btl_tcp_endpoint_complete_connect] connect() to 172.16.128.10 failed: Connection refused (111)
[BEVi][[65224,1],3][btl_tcp_endpoint.c:800:mca_btl_tcp_endpoint_complete_connect] connect() to 172.16.128.10 failed: Connection refused (111)
--------------------------------------------------------------------------
ORTE has lost communication with a remote daemon.

  HNP daemon   : [[65224,0],0] on node BEVi
  Remote daemon: [[65224,0],1] on node n0

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
--------------------------------------------------------------------------

```

**Comment by ArtPoon** [comment]
* shut down all jobs running on the cluster (sorry @ewong347).  
* checked out `master` branch - to make sure problem is not associated with branch `issue264`
* re-installed module with `python3 setup.py install --user`
* `nohup python3 batch.py --dry-run > issue289.log &`

**Comment by ArtPoon** [comment]
`/var/log/messages` indicates that we actually made the ping timeout *shorter*
```
Jun 16 23:16:57 n2 bpslave-0: Ping timeout after 60 seconds - lost connection to master?
Jun 16 23:16:57 n2 bpslave-0: Unmounting filesystems
Jun 16 23:16:57 n2 bpslave-0:  umount '/home' detached (is busy)
Jun 16 23:16:57 n2 bpslave-0:  umount '/opt' detached (is busy)
Jun 16 23:16:57 n2 bpslave-0:  umount '/usr/bin' detached (is busy)
Jun 16 23:16:57 n2 bpslave-0:  umount '/usr/lib64/python3.6' detached (is busy)
Jun 16 23:16:57 n2 bpslave: read_master_set: slave 0 exited
Jun 16 23:16:57 n2 bpslave: All slaves exited...  manager exiting.
```

**Comment by ArtPoon** [comment]
* Changed `/etc/beowulf/config` to set `pingtimeout` to `300` seconds.
* Reloaded config file on compute nodes.
* Killed and restarted run.

**Comment by ArtPoon** [comment]
Pipeline still running, but strange error message came up:
```console
🏄 [1 day, 15:46:44.843654][4/38] Writing distance matrix to temporary file
Traceback (most recent call last):
  File "covizu/clustering.py", line 289, in <module>
    with open(csvfile, 'w') as handle:
FileNotFoundError: [Errno 2] No such file or directory: 'data/B.1.427/429.labels.csv'
```

**Comment by ArtPoon** [comment]
Argh.  It's because of this weird lineage name:
```
🏄 [1 day, 15:44:51.370003] start B.1.427/429, 1228 entries
🏄 [1 day, 15:44:54.840501][5/38] loading JSON
```

**Comment by ArtPoon** [comment]
Pipeline hasn't been updated since 4am this morning, so this directory separator bug froze the whole thing.
Need a hot fix and restart.

**Comment by ArtPoon** [comment]
Spinning this off to a new issue

**Comment by ArtPoon** [comment]
Launched run in `dev` branch with substantial changes addressing #295 and #297
```console
[covizu@BEVi covizu]$ nohup python3 batch.py --dry-run > issue289a.log &
[1] 87849
```

**Comment by ArtPoon** [comment]
Forgot something...
```python
🏄 [1:39:17.763719] start MPI on minor lineages
Traceback (most recent call last):
  File "batch.py", line 142, in <module>
    result = make_beadplots(by_lineage, args, cb.callback, t0=cb.t0.timestamp())
  File "/home/covizu/covizu/covizu/utils/batch_utils.py", line 100, in make_beadplots
    "--max-variants", str(args.max_variants),
AttributeError: 'Namespace' object has no attribute 'max_variants'
```

**Comment by ArtPoon** [comment]
We're hitting the swap pretty hard, need to reduce number of processes being run on head node.

**Comment by ArtPoon** [comment]
Successful run this weekend.
Running 6 processes on the head node consumed almost all RAM and resulted in an active swap, which was probably causing the ping timeout problem.
Reduced number of processes to 4 (should probably reduce further, even to zero).
