### ISSUE TITLE
Change allocation of computing resources

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#295]
We are running most lineages serially (on a single CPU) - only a minority of lineages are run with MPI.  It would be much more efficient to run the lineages with <500 sampled variants as distributed across multiple cores with MPI.

**Comment by ArtPoon** [comment]
Can probably organize jobs here:
https://github.com/PoonLab/covizu/blob/029dfa9112f338162703756b9811be2590dfae9b/covizu/utils/batch_utils.py#L84-L94

**Comment by ArtPoon** [comment]
Proposed change (in `dev`) - note this incorporates hot fix #297:
```diff
diff --git a/covizu/clustering.py b/covizu/clustering.py
index 925c087..7585437 100644
--- a/covizu/clustering.py
+++ b/covizu/clustering.py
@@ -233,7 +233,9 @@ def parse_args():
     )
     parser.add_argument("json", type=str,
                         help="input, JSON file")
-    parser.add_argument("lineage", type=str, help="input, lineage to process")
+    parser.add_argument("lineage", type=str, help="input, name of lineage to process (deep mode) or path to "
+                                                  "text file of minor lineage names (flat mode)")
+    parser.add_argument("--mode", type=str, default='deep', help="'flat' or 'deep'")
 
     parser.add_argument("-o", "--outdir", type=str, default=os.getcwd(),
                         help="output, directory to export trees (one file per lineage). "
@@ -271,45 +273,87 @@ if __name__ == "__main__":
     cb = Callback(t0=args.timestamp, my_rank=my_rank, nprocs=nprocs)
 
     # import lineage data from file
+    # FIXME: this consumes a few minutes to load the entire data set
     cb.callback('loading JSON')
     with open(args.json) as handle:
         by_lineage = json.load(handle)
 
-    records = by_lineage.get(args.lineage, None)
-    if records is None:
-        cb.callback("ERROR: JSON did not contain lineage {}".format(args.lineage))
-        sys.exit()
-
-    # generate distance matrices from bootstrap samples [[ MPI ]]
-    union, labels, indexed = recode_features(records, callback=cb.callback, limit=args.max_variants)
+    if args.mode == 'deep':
+        records = by_lineage.get(args.lineage, None)
+        if records is None:
+            cb.callback("ERROR: JSON did not contain lineage {}".format(args.lineage))
+            sys.exit()
 
-    # export map of sequence labels to tip indices
-    if my_rank == 0:
-        csvfile = os.path.join(args.outdir, "{}.labels.csv".format(args.lineage))
-        with open(csvfile, 'w') as handle:
-            handle.write("name,index\n")
-            for i, names in enumerate(labels):
-                for nm in names:
-                    handle.write('{},{}\n'.format(nm, i))
+        # generate distance matrices from bootstrap samples [[ MPI ]]
+        union, labels, indexed = recode_features(records, callback=cb.callback, limit=args.max_variants)
 
-    outfile = os.path.join(args.outdir, '{}.nwk'.format(args.lineage))
-
-    if len(indexed) == 1:
-        # lineage only has one variant, no meaningful tree
+        # export map of sequence labels to tip indices
+        lineage_name = args.lineage.replace('/', '_')  # issue #297
         if my_rank == 0:
-            with open(outfile, 'w') as handle:
-                handle.write('({}:0);\n'.format(labels[0][0]))
+            csvfile = os.path.join(args.outdir, "{}.labels.csv".format(lineage))
+            with open(csvfile, 'w') as handle:
+                handle.write("name,index\n")
+                for i, names in enumerate(labels):
+                    for nm in names:
+                        handle.write('{},{}\n'.format(nm, i))
+
+        outfile = os.path.join(args.outdir, '{}.nwk'.format(lineage_name))
+        if len(indexed) == 1:
+            # lineage only has one variant, no meaningful tree
+            if my_rank == 0:
+                with open(outfile, 'w') as handle:
+                    handle.write('({}:0);\n'.format(labels[0][0]))
+        else:
+            # MPI processing
+            trees = []
+            for bn in range(args.nboot):
+                if bn % nprocs == my_rank:
+                    phy = bootstrap(union, indexed, args.binpath, callback=cb.callback)
+                    trees.append(phy)
+            comm.Barrier()  # wait for other processes to finish
+            result = comm.gather(trees, root=0)
+
+            # only head node exports trees
+            if my_rank == 0:
+                trees = [phy for batch in result for phy in batch]  # flatten nested lists
+                Phylo.write(trees, file=outfile, format='newick')
+
+    elif args.mode == 'flat':
+        # load list of lineages from text file
+        minor_lineages = []
+        with open(args.lineages) as handle:
+            for line in handle:
+                minor_lineages.append(line.strip())
+
+        for li, lineage in enumerate(minor_lineages):
+            if li % nprocs != my_rank:
+                continue
+
+            records = by_lineage.get(lineage, None)
+            if records is None:
+                cb.callback("ERROR: JSON did not contain lineage {}".format(args.lineage))
+                sys.exit()
+
+            union, labels, indexed = recode_features(records, callback=cb.callback, limit=args.max_variants)
+
+            # export map of sequence labels to tip indices
+            lineage_name = lineage.replace('/', '_')  # issue #297
+            csvfile = os.path.join(args.outdir, "{}.labels.csv".format(lineage_name))
+            with open(csvfile, 'w') as handle:
+                handle.write("name,index\n")
+                for i, names in enumerate(labels):
+                    for nm in names:
+                        handle.write('{},{}\n'.format(nm, i))
+
+            outfile = os.path.join(args.outdir, '{}.nwk'.format(lineage_name))
+            if len(indexed) == 1:
+                # lineage only has one variant, no meaningful tree
+                with open(outfile, 'w') as handle:
+                    handle.write('({}:0);\n'.format(labels[0][0]))
+            else:
+                trees = [bootstrap(union, indexed, args.binpath, callback=cb.callback)
+                         for _ in range(args.nboot)]
+                Phylo.write(trees, file=outfile, format='newick')
     else:
-        # MPI processing
-        trees = []
-        for bn in range(args.nboot):
-            if bn % nprocs == my_rank:
-                phy = bootstrap(union, indexed, args.binpath, callback=cb.callback)
-                trees.append(phy)
-        comm.Barrier()  # wait for other processes to finish
-        result = comm.gather(trees, root=0)
-
-        # only head node exports trees
-        if my_rank == 0:
-            trees = [phy for batch in result for phy in batch]  # flatten nested lists
-            Phylo.write(trees, file=outfile, format='newick')
+        cb.callback("Unexpected mode argument {} in clustering.py".format(args.mode))
+        sys.exit()
diff --git a/covizu/utils/batch_utils.py b/covizu/utils/batch_utils.py
index cd995fb..b59676c 100644
--- a/covizu/utils/batch_utils.py
+++ b/covizu/utils/batch_utils.py
@@ -70,7 +70,7 @@ def import_labels(handle, callback=None):
     return result
 
 
-def make_beadplots(by_lineage, args, callback=None, t0=None):
+def make_beadplots(by_lineage, args, callback=None, t0=None, txtfile='minor_lineages.txt'):
     """
     Wrapper for beadplot_serial - divert to clustering.py in MPI mode if
     lineage has too many genomes.
@@ -78,44 +78,64 @@ def make_beadplots(by_lineage, args, callback=None, t0=None):
     :param by_lineage:  dict, feature vectors stratified by lineage
     :param args:  Namespace, from argparse.ArgumentParser()
     :param t0:  float, datetime.timestamp.
+    :param txtfile:  str, path to file to write minor lineage names
     :return:  list, beadplot data by lineage
     """
-    result = []
-    for lineage, features in by_lineage.items():
+    # partition lineages into major and minor categories
+    major = set([lineage for lineage, features in by_lineage.items()
+                 if len(features) > args.mincount])
+
+    # export minor lineages to text file
+    with open(txtfile, 'w') as handle:
+        for lineage in by_lineage:
+            if by_lineage not in major:
+                handle.write('{}\n'.format(lineage))
+
+    # launch MPI job across minor lineages
+    cmd = ["mpirun", "--machinefile", args.machine_file, "python3", "covizu/clustering.py",
+           args.bylineage, txtfile,  # positional arguments <JSON file>, <str>
+           "--mode", "flat",
+           "--nboot", str(args.nboot), "--outdir", "data"
+           ]
+    if t0:
+        cmd.extend(["--timestamp", str(t0)])
+    subprocess.check_call(cmd)
+
+    # process major lineages
+    for lineage in major:
+        features = by_lineage[lineage]
         if callback:
             callback('start {}, {} entries'.format(lineage, len(features)))
 
-        if len(features) < args.mincount:
-            # serial processing
-            if len(features) == 0:
-                continue  # empty lineage, skip (should never happen)
-            beaddict = beadplot_serial(lineage, features, args)
-        else:
             # call out to MPI
             cmd = [
-                "mpirun", "--machinefile", args.machine_file,
-                "python3", "covizu/clustering.py",
-                 args.bylineage, lineage,  # positional arguments <JSON file>, <str>
-                 "--nboot", str(args.nboot), "--outdir", "data"
+                "mpirun", "--machinefile", args.machine_file, "python3", "covizu/clustering.py",
+                args.bylineage, lineage,  # positional arguments <JSON file>, <str>
+                "--mode", "deep",
+                "--nboot", str(args.nboot), "--outdir", "data"
             ]
             if t0:
                 cmd.extend(["--timestamp", str(t0)])
             subprocess.check_call(cmd)
 
-            # import trees
-            outfile = open('data/{}.nwk'.format(lineage))
-            trees = Phylo.parse(outfile, 'newick')  # note this returns a generator
-
-            # import label map
-            with open('data/{}.labels.csv'.format(lineage)) as handle:
-                label_dict = import_labels(handle)
-
-            # generate beadplot data
-            ctree = clustering.consensus(trees, cutoff=args.boot_cutoff, callback=callback)
-            outfile.close()  # done with Phylo.parse generator
-
-            ctree = beadplot.annotate_tree(ctree, label_dict)
-            beaddict = beadplot.serialize_tree(ctree)
+    # parse output files
+    result = []
+    for lineage in by_lineage:
+        # import trees
+        lineage_name = lineage.replace('/', '_')  # issue #297
+        outfile = open('data/{}.nwk'.format(lineage_name))
+        trees = Phylo.parse(outfile, 'newick')  # note this returns a generator
+
+        # import label map
+        with open('data/{}.labels.csv'.format(lineage_name)) as handle:
+            label_dict = import_labels(handle)
+
+        # generate beadplot data
+        ctree = clustering.consensus(trees, cutoff=args.boot_cutoff, callback=callback)
+        outfile.close()  # done with Phylo.parse generator
+
+        ctree = beadplot.annotate_tree(ctree, label_dict)
+        beaddict = beadplot.serialize_tree(ctree)
 
         beaddict.update({'lineage': lineage})
         result.append(beaddict)
```

**Comment by ArtPoon** [comment]
Test run went fairly quickly, but crashed on processing outputs:
```console
🏄 [0:46:33.805028] Parsing output files
🏄 [0:46:33.811001] Recording splits and branch lengths
...
🏄 [0:47:56.919492] Building consensus tree
Traceback (most recent call last):
  File "issue297.py", line 20, in <module>
    result = make_beadplots(by_lineage, args, cb.callback)
  File "/home/covizu/covizu/covizu/utils/batch_utils.py", line 142, in make_beadplots
    ctree = beadplot.annotate_tree(ctree, label_dict)
  File "/home/covizu/covizu/covizu/beadplot.py", line 111, in annotate_tree
    tip.labels.extend(label_dict[tn])
KeyError: 'hCoV-19/Australia/NSW2168/2020'
```

**Comment by ArtPoon** [comment]
This sequence is associated with lineage B.6.5 and is its only entry:
```console
[covizu@BEVi covizu]$ grep -r NSW2168 data/*.labels.csv
data/B.6.5.labels.csv:hCoV-19/Australia/NSW2168/2020|EPI_ISL_500639|2020-03-19,0
[covizu@BEVi covizu]$ grep -r NSW2168 data/*.nwk
data/B.6.5.nwk:(hCoV-19/Australia/NSW2168/2020|EPI_ISL_500639|2020-03-19:0);
```

**Comment by ArtPoon** [comment]
Crud.
```python
🏄 [0:49:57.529943] Building consensus tree
Traceback (most recent call last):
  File "issue297.py", line 23, in <module>
    outfile = open(os.path.join(args.outdir, 'clusters.{}.json'.format(timestamp)), 'w')
NameError: name 'os' is not defined
```

**Comment by ArtPoon** [comment]
Successful run with test data.  Starting full run.

**Comment by ArtPoon** [comment]
Full run successful, closing.
