### ISSUE TITLE
Lineage B.1.427/429

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#297]
Encountered this problem while trying to resolve #289:
```python
🏄 [1 day, 15:44:51.312011] Building consensus tree
🏄 [1 day, 15:44:51.370003] start B.1.427/429, 1228 entries
🏄 [1 day, 15:44:54.840501][5/38] loading JSON
...
🏄 [1 day, 15:46:44.843654][4/38] Writing distance matrix to temporary file
Traceback (most recent call last):
  File "covizu/clustering.py", line 289, in <module>
    with open(csvfile, 'w') as handle:
FileNotFoundError: [Errno 2] No such file or directory: 'data/B.1.427/429.labels.csv'
...
🏄 [1 day, 15:46:58.461146][5/38] Writing distance matrix to temporary file
Traceback (most recent call last):
  File "batch.py", line 142, in <module>
    result = make_beadplots(by_lineage, args, cb.callback, t0=cb.t0.timestamp())
  File "/home/covizu/covizu/covizu/utils/batch_utils.py", line 103, in make_beadplots
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpirun', '--machinefile', 'mfile', 'python3', 'covizu/clustering.py', 'data/by_lineage.json', 'B.1.427/429', '--nboot', '100', '--outdir', 'data', '--timestamp', '1623948515.111964']' died with <Signals.SIGKILL: 9>.
```

**Comment by ArtPoon** [comment]
Patch:
```diff
diff --git a/covizu/clustering.py b/covizu/clustering.py
index 925c087..dd102e4 100644
--- a/covizu/clustering.py
+++ b/covizu/clustering.py
@@ -285,14 +285,15 @@ if __name__ == "__main__":
 
     # export map of sequence labels to tip indices
     if my_rank == 0:
-        csvfile = os.path.join(args.outdir, "{}.labels.csv".format(args.lineage))
+        lineage = args.lineage.replace('/', '_')  # issue #297
+        csvfile = os.path.join(args.outdir, "{}.labels.csv".format(lineage))
         with open(csvfile, 'w') as handle:
             handle.write("name,index\n")
             for i, names in enumerate(labels):
                 for nm in names:
                     handle.write('{},{}\n'.format(nm, i))
 
-    outfile = os.path.join(args.outdir, '{}.nwk'.format(args.lineage))
+    outfile = os.path.join(args.outdir, '{}.nwk'.format(lineage))
 
     if len(indexed) == 1:
         # lineage only has one variant, no meaningful tree
diff --git a/covizu/utils/batch_utils.py b/covizu/utils/batch_utils.py
index cd995fb..27ad36e 100644
--- a/covizu/utils/batch_utils.py
+++ b/covizu/utils/batch_utils.py
@@ -103,11 +103,12 @@ def make_beadplots(by_lineage, args, callback=None, t0=None):
             subprocess.check_call(cmd)
 
             # import trees
-            outfile = open('data/{}.nwk'.format(lineage))
+            lineage_name = lineage.replace('/', '_')  # issue #297
+            outfile = open('data/{}.nwk'.format(lineage_name))
             trees = Phylo.parse(outfile, 'newick')  # note this returns a generator
 
             # import label map
-            with open('data/{}.labels.csv'.format(lineage)) as handle:
+            with open('data/{}.labels.csv'.format(lineage_name)) as handle:
                 label_dict = import_labels(handle)
 
             # generate beadplot data
```

**Comment by ArtPoon** [comment]
Hot fixed `master` branch with above changes.
Running this test:
```console
mpirun -np 8 python3 covizu/clustering.py data/by_lineage.json B.1.427/429 --outdir issue297/ --max-variants 100
```

**Comment by ArtPoon** [comment]
Need to test this on a standard lineage as well.
Then commit to `master` branch and fire up a run all over again...

**Comment by ArtPoon** [comment]
Oops - 8 cores is at the upper limit of what the head node can handle:
```console
[art@BEVi ~]$ free -h
              total        used        free      shared  buff/cache   available
Mem:            62G         62G        256M         14M        157M         62M
Swap:           31G         14G         16G
```

**Comment by ArtPoon** [comment]
```console
[covizu@BEVi covizu]$ ls -l issue297
total 212
-rw-rw-r-- 1 covizu covizu   8009 Jun 19 13:14 B.1.427_429.labels.csv
-rw-rw-r-- 1 covizu covizu 207482 Jun 19 13:14 B.1.427_429.nwk
```

**Comment by ArtPoon** [comment]
Test script `issue297.py`:
```python
from covizu.utils.batch_utils import make_beadplots
import json
import argparse
import batch
from covizu.utils.progress_utils import Callback
from datetime import datetime


cb = Callback()

cb.callback("loading by_lineage.json")
with open('data/by_lineage.json') as handle:
    by_lineage = json.load(handle)

args = batch.parse_args()
args.outdir = "issue297/"
args.max_variants = 100

result = make_beadplots(by_lineage, args, cb.callback)

timestamp = datetime.now().isoformat().split('.')[0]
outfile = open(os.path.join(args.outdir, 'clusters.{}.json'.format(timestamp)), 'w')
outfile.write(json.dumps(result))
outfile.close() 
```

**Comment by ArtPoon** [comment]
Generate a test set:
```python
>>> import json
>>> handle = open('data/by_lineage.json')
>>> by_lineage = json.load(handle)
>>> reduced = {}
>>> for lineage, features in by_lineage.items():
...     reduced.update({lineage: features[:1000]})
... 
>>> outfile = open('data/issue297.json', 'w')
>>> json.dump(reduced, outfile)
>>> outfile.close()
```

**Comment by ArtPoon** [comment]
Tests passed and full workflow ran to completion this weekend, closing.
