### ISSUE TITLE
[vsportal] Problem running Pangolin outside of conda env

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#302]
```python
Traceback (most recent call last):
  File "/home/poona8/.local/bin/pangolin", line 33, in <module>
    sys.exit(load_entry_point('pangolin==3.1.5', 'console_scripts', 'pangolin')())
  File "/home/poona8/.local/bin/pangolin", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: pangolin
```

**Comment by ArtPoon** [comment]
Ah, I needed to use `pip3 install .` instead of `python3 setup.py install --user`

**Comment by ArtPoon** [comment]
`python3 setup.py install --user` installed to `/home/poona8/.local/lib/python3.9/site-packages/covizu-0.3-py3.9.egg`, which did not work.
`python3 setup.py install` installed to `/home/poona8/workspace/python-app/venv/lib/python3.9/site-packages/covizu-0.3-py3.9.egg`, which *did* work.
