### ISSUE TITLE
Pipeline died at alignment step 2021-07-11

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#307]
```console
[covizu@BEVi ~]$ ls -lt
total 52708
-rw-rw-r--  1 covizu covizu 23260596 Jul 11 00:44 batch.log
[covizu@BEVi ~]$ tail batch.log
🏄 [0:44:27.371747] aligned 1515000 records
🏄 [0:44:29.830419] aligned 1516000 records
🏄 [0:44:32.297573] aligned 1517000 records
🏄 [0:44:32.334258] aligned 1518000 records
🏄 [0:44:34.875012] aligned 1519000 records
🏄 [0:44:37.484877] aligned 1520000 records
🏄 [0:44:40.130590] aligned 1521000 records
🏄 [0:44:42.766963] aligned 1522000 records
🏄 [0:44:45.375875] aligned 1523000 records
🏄 [0:44:48.122178] aligned 1524000 records
```

**Comment by ArtPoon** [comment]
From cron mail:
```python
Traceback (most recent call last):
  File "batch.py", line 130, in <module>
    by_lineage = process_feed(args, cb.callback)
  File "batch.py", line 111, in process_feed
    return gisaid_utils.sort_by_lineage(filtered, callback=callback)
  File "/home/covizu/covizu/covizu/utils/gisaid_utils.py", line 212, in sort_by_lineage
    for i, record in enumerate(records):
  File "/home/covizu/covizu/covizu/utils/gisaid_utils.py", line 169, in filter_problematic
    for record in records:
  File "/home/covizu/covizu/covizu/utils/gisaid_utils.py", line 131, in extract_features
    for fasta, batch in batcher:
  File "/home/covizu/covizu/covizu/utils/gisaid_utils.py", line 101, in batch_fasta
    for i, record in enumerate(gen, 1):
  File "/home/covizu/covizu/covizu/utils/gisaid_utils.py", line 76, in load_gisaid
    coldate = fromisoformat(record['covv_collection_date'])
  File "/home/covizu/covizu/covizu/utils/seq_utils.py", line 124, in fromisoformat
    year, month, day = map(int, dt.split('-'))
ValueError: invalid literal for int() with base 10: 'Jun'
```

**Comment by ArtPoon** [comment]
Proposed hot fix:
```diff
diff --git a/covizu/utils/gisaid_utils.py b/covizu/utils/gisaid_utils.py
index c56a547..7f880bf 100644
--- a/covizu/utils/gisaid_utils.py
+++ b/covizu/utils/gisaid_utils.py
@@ -74,7 +74,7 @@ def load_gisaid(path, minlen=29000, mindate='2019-12-01', callback=None)
                 rejects['baddate'] += 1
                 continue
             coldate = fromisoformat(record['covv_collection_date'])
-            if coldate < mindate or coldate > date.today():
+            if coldate is None or coldate < mindate or coldate > date.today():
                 # reject sequences with nonsense collection date
                 rejects['baddate'] += 1
                 continue
diff --git a/covizu/utils/seq_utils.py b/covizu/utils/seq_utils.py
index 77bc216..534aba3 100644
--- a/covizu/utils/seq_utils.py
+++ b/covizu/utils/seq_utils.py
@@ -121,7 +121,10 @@ def apply_features(diffs, missing, refseq):
 
 def fromisoformat(dt):
     """ Convert ISO date to Python datetime.date object to support Python <3.7 """
-    year, month, day = map(int, dt.split('-'))
+    try:
+        year, month, day = map(int, dt.split('-'))
+    except ValueError:
+        return None
     return date(year, month, day)
```
