### ISSUE TITLE
Get vsportal backend working

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#311]
* Download sequences and metadata from [VirusSeq Portal](https://virusseq-dataportal.ca/explorer) using *Download All* link (API pending).
* Decompress gzipped tar file, *e.g.*, `tar -zvxf virusseq.tar.gz`
* Run Pangolin on FASTA file (`conda activate pangolin; pangolin [FASTA]`) - writes to `lineage_report.csv` unless we specify another output file stem.
* Convert data:
  ```
  % python3 convert.py virusseq-consensus-export-all-2021-06-30T17:03:29.727965Z.fasta \
  lineage_report.csv virusseq-consensus-export-all-2021-06-30T17:03:29.727965Z.tsv \
  -o virusseq-2021-06-30.json.xz --delimiter '\t' --name isolate \
  --coldate 'sample collection date' \
  --set-region 'North America' --country 'geo_loc_name (country)' \
  --accession "specimen collector sample ID"
  ```
* Process data: `python3 process.py virusseq-2021-06-30.json.xz`

**Comment by ArtPoon** [comment]
Problem with resulting `clusters.json` file:
```json
[{"nodes": {
  "None": [
    ["2020-10-10", "None", "Canada", "North America", "L00298195", "hCoV-19/Canada/Qc-L00298195/2020"], 
    ["2020-10-10", "None", "Canada", "North America", "L00298203", "hCoV-19/Canada/Qc-L00298203/2020"]
  ]}, 
"edges": [
  ["None", "None", 1.74, 0.57], 
  ["None", "None", 1.04, null], 
  ["None", "None", 0.91, null], 
  ["None", "None", 2.21, null], 
  ["None", "None", 1.92, null], 
  ["None", "None", 0.91, null],
```

**Comment by ArtPoon** [comment]
Fixed in commit e3991ed

**Comment by ArtPoon** [comment]
Ran on orolo:
```console
python3 process.py virusseq-2021-06-30.json.xz --ft2bin fasttree2-mp -np 6
```
Note `-np` argument means we don't need a machine file.  
TODO: if user sets neither `-np` nor `--machinefile`, then pipeline should run in serial mode.

**Comment by ArtPoon** [comment]
```console
wget https://data.nextstrain.org/files/ncov/open/metadata.tsv.gz
wget https://data.nextstrain.org/files/ncov/open/sequences.fasta.xz
conda activate pangolin
pangolin --update  # actually there was a major revision
pangolin sequences.fasta.xz --threads 8
```

**Comment by ArtPoon** [comment]
Forgot I need to write `region` and `country` to labels now, because these are not necessarily embedded in sequence names.

**Comment by ArtPoon** [comment]
Current data: `clusters.2021-07-21T23:22:29.json`
Front-end errors:
* `Error: <rect> attribute width: Expected length, "NaN".` (59 times)
* `Error: <text> attribute x: Expected length, "NaN".` (59 times)
* ```
  beadplot.js:674 Uncaught TypeError: Cannot read property 'replace' of undefined
    at SVGLineElement.<anonymous> (beadplot.js:674)
    at SVGLineElement.<anonymous> (d3.js:1209)
    at Selection.selection_each [as each] (d3.js:1176)
    at Selection.selection_attr [as attr] (d3.js:1233)
    at redraw (beadplot.js:673)
    at beadplot (beadplot.js:875)
    at Object.<anonymous> (covizu.js:163)
    at fire (jquery.js:3496)
    at Object.fireWith [as resolveWith] (jquery.js:3626)
    at done (jquery.js:9786)
  ```
* ```
  drawtree.js:277 Uncaught TypeError: mutations is not iterable
    at mutations_to_string (drawtree.js:277)
    at mouseover (drawtree.js:323)
    at SVGTextElement.<anonymous> (drawtree.js:415)
    at SVGTextElement.<anonymous> (d3.js:1526)
  ```

**Comment by ArtPoon** [comment]
Fixed first three problems.  Still getting `Uncaught TypeError: mutations is not iterable`.
Probably this field is not populated in `vsportal` branch.

**Comment by ArtPoon** [comment]
Processing newer VirusSeq data:
```console
(pangolin) art@orolo:~/git/covizu$ python3 convert.py virusseq-consensus-export-all-2021-07-21T15\:40\:59.370802Z.fasta lineage_report.csv virusseq-consensus-export-all-2021-07-21T15\:40\:59.370802Z.tsv -o virusseq-2021-07-21.json.xz --delimiter '\t' --name 'fasta header name' --coldate 'sample collection date' --set-region 'North America' --country 'geo_loc_name (country)' --accession "specimen collector sample ID"
```

**Comment by ArtPoon** [comment]
```console
(pangolin) art@orolo:~/git/covizu$ python3 process.py virusseq-2021-07-21.json.xz --ft2bin fasttree2-mp -np 8
🏄 [0:00:01.624509] aligned 0 records
🏄 [0:00:01.639270] aligned 1000 records
🏄 [0:00:03.310331] aligned 2000 records
🏄 [0:00:04.935787] aligned 3000 records
🏄 [0:00:06.442471] aligned 4000 records
🏄 [0:00:06.457993] aligned 5000 records
🏄 [0:00:08.193083] aligned 6000 records
🏄 [0:00:09.712305] aligned 7000 records
🏄 [0:00:11.282963] aligned 8000 records
🏄 [0:00:13.051069] aligned 9000 records
🏄 [0:00:13.206514] filtered 3008 problematic features
🏄 [0:00:13.206572]          3975 genomes with excess missing sites
🏄 [0:00:13.206580]          2219 genomes with excess divergence
```
This is a substantial fraction of genomes discarded with excess divergence, better check

**Comment by ArtPoon** [comment]
Weird error:
```console
🏄 [0:01:43.084084] start MPI on minor lineages
Traceback (most recent call last):
  File "covizu/clustering.py", line 13, in <module>
    from covizu.utils.progress_utils import Callback
ModuleNotFoundError: No module named 'covizu'
...
Traceback (most recent call last):
  File "process.py", line 172, in <module>
    analyze_feed(handle, args, callback=cb.callback)
  File "process.py", line 131, in analyze_feed
    result = make_beadplots(by_lineage, args, callback, t0=t0.timestamp())
  File "/home/art/git/covizu/covizu/utils/batch_utils.py", line 117, in make_beadplots
    subprocess.check_call(mpirun+cmd)
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpirun', '-np', '8', 'python3', 'covizu/clustering.py', 'data/by_lineage.json', 'minor_lineages.txt', '--mode', 'flat', '--max-variants', '5000', '--nboot', '100', '--outdir', 'data', '--timestamp', '1626979494.000991']' returned non-zero exit status 1.
```
