### ISSUE TITLE
vsportal: pangolin has become too slow

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#315]
It looks like it might be scorpio's fault

**Comment by ArtPoon** [comment]
Tried running in background with `nohup pangolin sequences.fasta.xz --threads 8 &` but the job apparently died with a broken pipe.  
Strange error messages in `nohup.out`:
```
OU389189                               N content too high       0.32      
Job stats:
job                     count    min threads    max threads
--------------------  -------  -------------  -------------
add_failed_seqs             1              1              1
align_to_reference          1              1              1
all                         1              1              1
generate_report             1              1              1
hash_sequence_assign        1              1              1
pangolearn                  1              1              1
scorpio                     1              8              8
total                       7              1              8

Error: write /dev/stdout: no space left on device
Usage:
  gofasta sam toMulti[Thu Jul 22 23:39:20 2021]
--- Logging error ---
Traceback (most recent call last):
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/snakemake/executors
/__init__.py", line 2372, in run_wrapper
    run(
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/pangolin/scripts/pa
ngolearn.smk", line 94, in __rule_align_to_reference
    if hash_string in set_hash:
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/snakemake/shell.py"
, line 263, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'minimap2 -a -x asm5 --sam-hit-only --secondary=no 
-t  8 /home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/pangolin/data/referen
ce.fasta '/tmp/tmpbzkmcet5/query.post_qc.fasta' -o /tmp/tmpbzkmcet5/mapped.sam &> /tmp/tmp
bzkmcet5/logs/minimap2_sam.log 
        gofasta sam toMultiAlign             -s /tmp/tmpbzkmcet5/mapped.sam             -t 8             --reference /home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/pangolin/data/reference.fasta             --trimstart 265             --trimend 29674             --trim             --pad > '/tmp/tmpbzkmcet5/sequences.aln.fasta'' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 592, in _callback
    raise ex
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 578, in cached_or_run
    run_func(*args)
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2405, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 63 of /home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/pangolin/scripts/pangolearn.smk:
Command 'minimap2 -a -x asm5 --sam-hit-only --secondary=no -t  8 /home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/pangolin/data/reference.fasta '/tmp/tmpbzkmcet5/query.post_qc.fasta' -o /tmp/tmpbzkmcet5/mapped.sam &> /tmp/tmpbzkmcet5/logs/minimap2_sam.log 
        gofasta sam toMultiAlign             -s /tmp/tmpbzkmcet5/mapped.sam             -t 8             --reference /home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/pangolin/data/reference.fasta             --trimstart 265             --trimend 29674             --trim             --pad > '/tmp/tmpbzkmcet5/sequences.aln.fasta'' returned non-zero exit status 1.
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/pangolin/scripts/pangolearn.smk", line 63, in __rule_align_to_reference

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
OSError: [Errno 28] No space left on device
Call stack:
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/concurrent/futures/thread.py", line 59, in run
    self.future.set_exception(exc)
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/concurrent/futures/_base.py", line 545, in set_exception
    self._invoke_callbacks()
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 601, in _callback
    self.print_job_error(job)
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 178, in print_job_error
    job.log_error(msg, **kwargs)
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/snakemake/jobs.py", line 947, in log_error
    logger.job_error(
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/snakemake/logging.py", line 394, in job_error
    self.handler(msg)
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/snakemake/logging.py", line 339, in handler
    handler(msg)
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/pangolin/utils/custom_logger.py", line 314, in text_handler
    self.logger.error("")
Message: ''
Arguments: ()
Exiting because a job execution failed. Look above for error message
--- Logging error ---
Traceback (most recent call last):
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/snakemake/logging.py", line 66, in emit
    self.flush()
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
OSError: [Errno 28] No space left on device
Call stack:
  File "/home/art/miniconda3/envs/pangolin/bin/pangolin", line 8, in <module>
    sys.exit(main())
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/pangolin/command.py", line 376, in main
    status = snakemake.snakemake(snakefile, printshellcmds=False, forceall=True,force_incomplete=True,workdir=tempdir,
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/snakemake/__init__.py", line 699, in snakemake
    success = workflow.execute(
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/snakemake/workflow.py", line 1056, in execute
    success = scheduler.schedule()
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/snakemake/scheduler.py", line 451, in schedule
    logger.error(_ERROR_MSG_FINAL)
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/snakemake/logging.py", line 373, in error
    self.handler(dict(level="error", msg=msg))
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/snakemake/logging.py", line 339, in handler
    handler(msg)
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/snakemake/logging.py", line 551, in text_handler
    self.logger.error(msg["msg"])
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/logging/__init__.py", line 1463, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/art/miniconda3/envs/pangolin/lib/python3.8/site-packages/snakemake/logging.py", line 73, in emit
    self.handleError(record)
Message: 'Exiting because a job execution failed. Look above for error message'
Arguments: ()

OU389919                               N content too high       0.41   
```

**Comment by ArtPoon** [comment]
Wrote an MPI-enabled Python script to try to speed up Pangolin (version 3.1.7) processing:
```console
(pangolin) art@orolo:~/git/pangolin$ time mpirun -np 6 python3 mangolin.py n1e4.fasta.xz
...
real	1m7.711s
user	6m56.547s
sys	3m24.852s
...
(pangolin) art@orolo:~/git/pangolin$ time pangolin n1e4.fasta.xz
real	4m37.979s
user	4m42.658s
sys	0m25.107s
```

**Comment by ArtPoon** [comment]
Looks like there is some duplicate processing:
```R
> files <- Sys.glob("mangolin.*.csv")
> dfs <- lapply(files, function(f) read.csv(f, header=T))
> mangolin <- do.call(rbind, dfs)
> dim(mangolin)
[1] 10015    13
> length(unique(mangolin$taxon))
[1] 10000
> which.max(table(mangolin$taxon))
GUM/GU-NHG-01/2020 
                98 
> sum(mangolin$taxon=='GUM/GU-NHG-01/2020')
[1] 16
> pangolin <- read.csv('lineage_report.csv')
> dim(pangolin)
[1] 10000    13
```

**Comment by ArtPoon** [comment]
It's the last record in the input file:
```console
art@orolo:~/git/pangolin$ unxz -c n1e4.fasta.xz | grep -n GUM/GU-NHG-01/2020
19999:>GUM/GU-NHG-01/2020
```

**Comment by ArtPoon** [comment]
Fixed, had to remove extra `chunk.append(record)` line in `mangolin.py`:
```R
> dfs <- lapply(files, function(f) read.csv(f, header=T))
> mangolin <- do.call(rbind, dfs)
> dim(mangolin)
[1] 10000    13
```

Check that outputs are the same:
```R
> mangolin$taxon <- as.character(mangolin$taxon)
> pangolin$taxon <- as.character(pangolin$taxon)
> mangolin <- mangolin[order(mangolin$taxon), ]
> pangolin <- pangolin[order(pangolin$taxon), ]
> all(mangolin$taxon == pangolin$taxon)
[1] TRUE
> all(mangolin$lineage == pangolin$lineage)
[1] TRUE
```

**Comment by ArtPoon** [comment]
```console
(pangolin) art@orolo:~/git/pangolin$ time mpirun -np 16 python3 mangolin.py ~/git/covizu/sequences.fasta.xz 
(1/16) processing 1000 sequences
(10/16) processing 1000 sequences
(15/16) processing 1000 sequences
...
(9/16) processing 524 sequences
(7/16) processing 524 sequences
(1/16) processing 524 sequences

real	59m53.500s
user	926m48.303s
sys	240m53.555s
(pangolin) art@orolo:~/git/pangolin$ unxz -c ~/git/covizu/sequences.fasta.xz | grep -c ">"
968385
```
Processed nearly 1M genomes in about an hour.

**Comment by ArtPoon** [comment]
Combine output files:
```python
>>> import csv
>>> fieldnames = ['taxon', 'lineage', 'conflict', 'ambiguity_score', 'scorpio_call',
...     'scorpio_support', 'scorpio_conflict', 'version', 'pangolin_version',
...     'pangoLEARN_version', 'pango_version', 'status', 'note']
>>> from glob import glob
>>> writer = csv.DictWriter(open('genbank-2021-07-21.pangolin.csv', 'w'), fieldnames=fieldnames)
>>> writer.writeheader()
>>> files = glob('mangolin.*.csv')
>>> len(files)
16
>>> for f in files:
>>>     reader = csv.DictReader(open(f))
>>>     for row in reader:
>>>         _ = writer.writerow(row)
```

Probably faster to do this in UNIX.

**Comment by ArtPoon** [comment]
```console
art@orolo:~/git/covizu$ python3 convert.py --append virusseq-2021-07-21.json.xz --xz --delimiter '\t' sequences.fasta.xz genbank-2021-07-21.pangolin.csv metadata.tsv --name strain --accession genbank_accession --coldate date --region region --country country --division division
🏄 [0:53:38.136342] Rejected 1337 short genomes, 80112 records with bad dates
```
