### ISSUE TITLE
Pipeline failed 2021-07-27 at treetime stage

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#322]
```
    697.68 seconds: ML split tests for   1200 of   1233 internal splits
Total time: 704.52 seconds Unique: 1236/1236 Bad splits: 0/1233
Traceback (most recent call last):
  File "/usr/local/bin/treetime", line 4, in <module>
    __import__('pkg_resources').run_script('phylo-treetime==0.8.0', 'treetime')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in 
run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1441, in
 run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/phylo_treetime-0.8.0-py3.6.egg/EGG-
INFO/scripts/treetime", line 12, in <module>
  File "/usr/local/lib/python3.6/site-packages/phylo_treetime-0.8.0-py3.6.egg/tree
time/argument_parser.py", line 213, in toplevel
  File "/usr/local/lib/python3.6/site-packages/phylo_treetime-0.8.0-py3.6.egg/tree
time/wrappers.py", line 566, in timetree
  File "/usr/local/lib/python3.6/site-packages/phylo_treetime-0.8.0-py3.6.egg/tree
time/treetime.py", line 156, in run
  File "/usr/local/lib/python3.6/site-packages/phylo_treetime-0.8.0-py3.6.egg/tree
time/treeanc.py", line 1305, in optimize_tree
  File "/usr/local/lib/python3.6/site-packages/phylo_treetime-0.8.0-py3.6.egg/tree
time/treeanc.py", line 1074, in optimize_branch_len
  File "/usr/local/lib/python3.6/site-packages/phylo_treetime-0.8.0-py3.6.egg/tree
time/treeanc.py", line 1117, in optimize_branch_lengths_joint
  File "/usr/local/lib/python3.6/site-packages/phylo_treetime-0.8.0-py3.6.egg/tree
time/treeanc.py", line 1158, in optimal_branch_length
  File "/usr/local/lib/python3.6/site-packages/phylo_treetime-0.8.0-py3.6.egg/tree
time/treeanc.py", line 1065, in add_branch_state
  File "/usr/local/lib/python3.6/site-packages/phylo_treetime-0.8.0-py3.6.egg/tree
time/gtr.py", line 606, in state_pair
AttributeError: 'NoneType' object has no attribute 'shape'
Traceback (most recent call last):
  File "batch.py", line 135, in <module>
    timetree, residuals = build_timetree(by_lineage, args, cb.callback)
  File "/home/covizu/covizu/covizu/utils/batch_utils.py", line 18, in build_timetr
ee
    clock=args.clock, verbosity=0)
  File "/home/covizu/covizu/covizu/treetime.py", line 67, in treetime
    check_call(call)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['treetime', '--tree', '/tmp/cvz_tt_guksu3
gw', '--aln', '/tmp/cvz_tt_jc9f_66w', '--dates', '/tmp/cvz_tt_h732lmvu', '--outdir
', 'data/', '--verbose', '0', '--plot-rtt', 'none', '--clock-filter', '0', '--cloc
k-rate', '0.0008']' returned non-zero exit status 1.
```

**Comment by ArtPoon** [comment]
Re-ran the Treetime call to try to get more debugging information:
```console
[covizu@BEVi ~]$ treetime --tree /tmp/cvz_tt_guksu3gw --aln /tmp/cvz_tt_jc9f_66w --dates /tmp/cvz_tt_h732lmvu --outdir iss322/ --verbose 0 --plot-rtt none --clock-filter 0 --clock-rate 0.0008

Attempting to parse dates...
	Using column 'name' as name. This needs match the taxon names in the tree!!
	Using column 'date' as date.

0.00	-TreeAnc: set-up

15.07	***WARNING: TreeAnc._attach_sequences_to_nodes: NO SEQUENCE FOR LEAF:
     	hCoV-19/SouthAfrica/KRISP-0368/2020

... [omitted many other WARNINGs] ...

15.85	***WARNING: TreeAnc._attach_sequences_to_nodes: NO SEQUENCE FOR LEAF:
     	hCoV-19/SouthKorea/KCDC2212/2020

15.86	***WARNING: TreeAnc: 79 nodes don't have a matching sequence in the
     	alignment. POSSIBLE ERROR.

Traceback (most recent call last):
  File "/usr/local/bin/treetime", line 4, in <module>
    __import__('pkg_resources').run_script('phylo-treetime==0.8.0', 'treetime')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in run_script
...
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by ArtPoon** [comment]
It's genomes with spaces in the country names:
```console
[covizu@BEVi ~]$ less /tmp/cvz_tt_jc9f_66w
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
>hCoV-19/South Korea/KCDC2212/2020
NNNNAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGA
```

**Comment by ArtPoon** [comment]
I had modified `treetime.py` on the cluster and forgot to revert back to `master` branch`:
```diff
diff --git a/covizu/treetime.py b/covizu/treetime.py
diff --git a/covizu/treetime.py b/covizu/treetime.py
index 629e143..72f74ff 100644
--- a/covizu/treetime.py
+++ b/covizu/treetime.py
@@ -162,24 +162,26 @@ def retrieve_genomes(by_lineage, ref_file, earliest=True):
diff --git a/covizu/treetime.py b/covizu/treetime.py
index 629e143..72f74ff 100644
--- a/covizu/treetime.py
diff --git a/covizu/treetime.py b/covizu/treetime.py
index 629e143..72f74ff 100644
--- a/covizu/treetime.py
+++ b/covizu/treetime.py
@@ -162,24 +162,26 @@ def retrieve_genomes(by_lineage, ref_file, earliest=True):
     # allocate lists
     coldates = []
     lineages = []
+    names = []
     seqs = []
 
     # retrieve unaligned genomes from database
     for lineage, records in by_lineage.items():
-        intermed = [(r['covv_collection_date'], r['diffs'], r['missing']) for r i
+        intermed = [(r['covv_collection_date'], r['covv_virus_name'], r['diffs'],
         intermed.sort(reverse=True)  # descending order
-        coldate, diffs, missing = intermed[-1] if earliest else intermed[0]
+        coldate, vname, diffs, missing = intermed[-1] if earliest else intermed[0
 
         # update lists
         lineages.append(lineage)
         coldates.append(coldate)
+        names.append(vname)
 
         # reconstruct aligned sequence from feature vector
         seq = apply_features(diffs, missing=missing, refseq=refseq)
         seqs.append(seq)
 
     # generate new headers in {name}|{accession}|{date} format expected by treeti
-    headers = map(lambda xy: '|{}|{}'.format(*xy), zip(lineages, coldates))
+    headers = map(lambda xy: '{}|{}|{}'.format(*xy), zip(lineages, names, coldate
     return dict(zip(headers, seqs))
 
 
@@ -225,10 +227,16 @@ if __name__ == '__main__':
     args = parse_args()
     cb = Callback()
 
-    cb.callback("Retrieving genomes")
+    cb.callback("loading JSON")
     with open(args.json) as handle:
         by_lineage = json.load(handle)
+
+    cb.callback("Retrieving genomes")
     fasta = retrieve_genomes(by_lineage, ref_file=args.ref, earliest=args.earlies
+    outfile = open('treetime.fasta', 'w')
+    for h, s in fasta.items():
+        outfile.write(">{}\n{}\n".format(h, s))
+    outfile.close()
 
     cb.callback("Reconstructing tree with {}".format(args.ft2bin))
     nwk = fasttree(fasta, binpath=args.ft2bin)
```

**Comment by ArtPoon** [comment]
Check that pipeline runs first

**Comment by ArtPoon** [comment]
Note, I had meant those edits to `treetime.py` to be temporary to diagnose #313, and forgot to revert
