### ISSUE TITLE
Reduce memory consumption

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#335]
See #330

**Comment by ArtPoon** [comment]
Or invest in something like a Superdome

**Comment by ArtPoon** [comment]
I noticed today that loading `by_lineage.json` consumes about 16GB on my workstation.  We might have to look into filtering excess numbers of genomes.

**Comment by ArtPoon** [comment]
Should probably move `clustering::recode_features()` to an earlier stage of the pipeline.  It is redundant to recompute the feature set and collapse identical variants every time we launch a job on a compute node from `by_lineage.json`.

**Comment by ArtPoon** [comment]
Refactoring in branch `iss339`

**Comment by ArtPoon** [comment]
Check whether `iss339` reduces file size of `by_lineage.json`
```console
[covizu@BEVi covizu]$ ls -lt data/by*
-rw-r--r-- 1 covizu covizu 3015237095 Sep  7 01:15 data/by_lineage.json
[covizu@BEVi covizu]$ git fetch
[covizu@BEVi covizu]$ git checkout iss339
Branch iss339 set up to track remote branch iss339 from origin.
Switched to a new branch 'iss339'
[covizu@BEVi covizu]$ python3 setup.py install --user
```

```python
[covizu@BEVi covizu]$ python3
Python 3.6.8 (default, Nov 16 2020, 16:55:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from batch import *
>>> args = parse_args()
>>> cb = Callback()
>>> args.infile = "data/provision.2021-09-07T00:00:03.json.xz"
>>> by_lineage = process_feed(args, cb.callback)
🏄 [0:00:24.859683] Processing GISAID feed data
```

**Comment by ArtPoon** [comment]
```python
🏄 [1:05:45.763060] filtered 879651 problematic features
🏄 [1:05:45.763088]          851935 genomes with excess missing sites
🏄 [1:05:45.763101]          143779 genomes with excess divergence
>>> 
>>> with open("test-iss335.json", 'w') as handle:
...     json.dump(by_lineage, handle)
```

```console
[covizu@BEVi covizu]$ ls -l test-iss335.json 
-rw-rw-r-- 1 covizu covizu 1914603691 Sep  7 21:35 test-iss335.json
```
About 35% smaller.

**Comment by ArtPoon** [comment]
Test `iss339` branch on `testdata.xz` (see #213) with `--dry-run` flag.

**Comment by ArtPoon** [comment]
```console
🏄 [0:02:00.061121] Reduced to 1 variants; generating feature set union
Traceback (most recent call last):
  File "test-iss335.py", line 6, in <module>
    result = make_beadplots(by_lineage, args, cb.callback, t0=cb.t0.timestamp())
  File "/home/covizu/covizu/covizu/utils/batch_utils.py", line 117, in make_beadplots
    json.dump(recoded, handle)
  File "/usr/lib64/python3.6/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib64/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib64/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.6/json/encoder.py", line 376, in _iterencode_dict
    raise TypeError("key " + repr(key) + " is not a string")
TypeError: key ('~', 209, 'T') is not a string
```

**Comment by ArtPoon** [comment]
Ok that `TypeError` message isn't kidding - I have to serialize the tuple keys.

**Comment by ArtPoon** [comment]
```python
Traceback (most recent call last):
  File "test-iss335.py", line 6, in <module>
    result = make_beadplots(by_lineage, args, cb.callback, t0=cb.t0.timestamp())
  File "/home/covizu/covizu/covizu/utils/batch_utils.py", line 120, in make_beadplots
    json.dump(recoded, handle)
  File "/usr/lib64/python3.6/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib64/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib64/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib64/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/usr/lib64/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'set' is not JSON serializable
```

**Comment by ArtPoon** [comment]
Weird error:
```console
🏄 [0:02:36.208900][0/26] ERROR: JSON did not contain lineage minor_lineages.txt
```

**Comment by ArtPoon** [comment]
Was passing `args.lineages` instead of `lineages.
New error:
```python
Traceback (most recent call last):
  File "covizu/clustering.py", line 345, in <module>
    union, labels, indexed = unpack_recoded(lineage, callback=cb.callback)
  File "covizu/clustering.py", line 269, in unpack_recoded
    for feat, idx in union.items():
AttributeError: 'list' object has no attribute 'items'
```

**Comment by ArtPoon** [comment]
Weird console message while testing, hopefully unrelated:
```console
[covizu@BEVi covizu]$ nohup python3 test-iss335.py > test-iss335.log &
[1] 35973
[covizu@BEVi covizu]$ nohup: ignoring input and redirecting stderr to stdout

[covizu@BEVi covizu]$ tail -f test-iss335.log
🏄 [0:00:00.000011] Loading JSON data
🏄 [0:01:37.213780] Recoding features, compressing variants..
🏄 [0:02:30.426408] start MPI on minor lineages
🏄 [0:02:51.951834][1/26] loading JSON
🏄 [0:02:51.952098][0/26] loading JSON
🏄 [0:02:51.058351][2/26] loading JSON
🏄 [0:02:51.058485][3/26] loading JSON
🏄 [0:02:52.894440][10/26] loading JSON
🏄 [0:02:52.894458][12/26] loading JSON
🏄 [0:02:52.894446][14/26] loading JSON
🏄 [0:02:52.894435][15/26] loading JSON
🏄 [0:02:51.417771][19/26] loading JSON
🏄 [0:02:51.417767][20/26] loading JSON
🏄 [0:02:51.417771][21/26] loading JSON
🏄 [0:02:51.417776][22/26] loading JSON
🏄 [0:02:51.417777][23/26] loading JSON
🏄 [0:02:51.417773][24/26] loading JSON
🏄 [0:02:51.417771][25/26] loading JSON
🏄 [0:02:51.417771][17/26] loading JSON
🏄 [0:02:51.418219][16/26] loading JSON
🏄 [0:02:51.418219][18/26] loading JSON
🏄 [0:02:52.664678][4/26] loading JSON
🏄 [0:02:52.664683][5/26] loading JSON
🏄 [0:02:52.895378][11/26] loading JSON
🏄 [0:02:52.664678][6/26] loading JSON
🏄 [0:02:52.895378][13/26] loading JSON
🏄 [0:02:52.664678][7/26] loading JSON
🏄 [0:02:52.664678][8/26] loading JSON
🏄 [0:02:52.664679][9/26] loading JSON

Message from syslogd@BEVi at Sep  7 23:07:28 ...
 kernel:do_IRQ: 22.121 No irq handler for vector (irq -1)


```

**Comment by ArtPoon** [comment]
```console
[covizu@BEVi covizu]$ ls -l recoded.json 
-rw-rw-r-- 1 covizu covizu 190556748 Sep  7 23:07 recoded.json
```

**Comment by ArtPoon** [comment]
```python
Traceback (most recent call last):
  File "test-iss335.py", line 6, in <module>
    result = make_beadplots(by_lineage, args, cb.callback, t0=cb.t0.timestamp())
  File "/home/covizu/covizu/covizu/utils/batch_utils.py", line 146, in make_beadplots
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpirun', '--machinefile', 'mfile', 'python3', 'covizu/clustering.py', 'recoded.json', 'minor_lineages.txt', '--mode', 'flat', '--max-variants', '5000', '--nboot', '100', '--outdir', 'data', '--timestamp', '1631070270.322395']' returned non-zero exit status 1.
```
Seem to be running into the same issue as #336, try running with `disown` argument

**Comment by ArtPoon** [comment]
This is strange - the pipeline is hanging at some point between completing the "flat" mode `clustering.py` run on "minor lineages", and starting the "deep" mode run:
```console
<U+1F3C4> [0:00:00.000011] Loading JSON data
<U+1F3C4> [0:01:30.655262] Recoding features, compressing variants..
<U+1F3C4> [0:02:21.413913] start MPI on minor lineages
<U+1F3C4> [0:02:43.137315][1/26] loading JSON
...
🏄 [2:53:12.692908][2/26] completed B.1.84
🏄 [2:53:14.909100][2/26] completed B.1.1.110
🏄 [2:53:17.086565][2/26] completed B.1.491
```

```console
[covizu@BEVi covizu]$ ls -lt data | head -n2
total 39451204
-rw-rw-r-- 1 covizu covizu       4101 Sep  8 16:10 B.1.491.nwk
[covizu@BEVi covizu]$ wc -l data/B.1.491.nwk
100 data/B.1.491.nwk
```

There is still a single python3 process still running on the cluster.

**Comment by ArtPoon** [comment]
Looks like one of the last minor lineages isn't done yet:
```console
[covizu@BEVi covizu]$ for f in `tail -n26 minor_lineages.txt`; do echo $f; grep -F -c $f test-iss335.log; done
B.1.499.1
1
B.1.496
1
B.1.350.1
1
B.1.1.427
1
B.1.1.190
1
B.1.1.114
1
AM.2
1
A.30
1
A.18
1
M.2
2
C.10
1
B.1.542
1
B.1.491
1
B.1.476
1
B.1.316
1
B.1.1.452
1
B.1.1.404
1
B.1.1.249
1
B.6.5
0
B.1.137
1
M.3
2
B.1.617
3
B.1.285
1
B.1.177.34
1
B.1.1.53
1
B.1.1.400
1
```

**Comment by ArtPoon** [comment]
B.6.5 is a single variant (two sample) lineage.\
```console
[covizu@BEVi covizu]$ ls -l data/B.6.5.*
-rw-rw-r-- 1 covizu covizu 137 Sep  7 06:59 data/B.6.5.labels.csv
-rw-rw-r-- 1 covizu covizu  62 Sep  7 06:59 data/B.6.5.nwk
[covizu@BEVi covizu]$ cat data/B.6.5.labels.csv 
name,index
hCoV-19/Australia/NSW2168/2020|EPI_ISL_500639|2020-03-19,0
hCoV-19/Australia/NSW-SAVID-4086/2020|EPI_ISL_3568417|2020-04-06,0
[covizu@BEVi covizu]$ cat data/B.6.5.nwk
(hCoV-19/Australia/NSW2168/2020|EPI_ISL_500639|2020-03-19:0);
```

Something about handling this edge case seems to be gumming up the pipeline.

**Comment by ArtPoon** [comment]
Directly inspecting the JSON file:
```python
>>> import json
>>> with open("recoded.json") as handle:
...   recoded = json.load(handle)
... 
>>> len(recoded)
1375
>>> recoded['B.6.5']['labels']
[['hCoV-19/Australia/NSW2168/2020|EPI_ISL_500639|2020-03-19', 'hCoV-19/Australia/NSW-SAVID-4086/2020|EPI_ISL_3568417|2020-04-06']]
```

**Comment by ArtPoon** [comment]
Manually killed the last running process.  Error message not very helpful:
```python
🏄 [2:53:17.086565][2/26] completed B.1.491
--------------------------------------------------------------------------
mpirun noticed that process rank 8 with PID 53218 on node n1 exited on signal 9 (Killed).
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "test-iss335.py", line 6, in <module>
    result = make_beadplots(by_lineage, args, cb.callback, t0=cb.t0.timestamp())
  File "/home/covizu/covizu/covizu/utils/batch_utils.py", line 148, in make_beadplots
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpirun', '--machinefile', 'mfile', 'python3', 'covizu/clustering.py', 'recoded.json', 'minor_lineages.txt', '--mode', 'flat', '--max-variants', '5000', '--nboot', '100', '--outdir', 'data/', '--binpath', 'rapidnj', '--timestamp', '1631121405.924751']' returned non-zero exit status 137.
```

**Comment by ArtPoon** [comment]
Confirmed that B.6.5 is associated with process of rank 8:
```python
>>> handle = open('minor_lineages.txt')
>>> for li, line in enumerate(handle):
...   if li % 26 == 8:
...     print(line.strip())
... 
None
B.1.1.70
B.40
B.1.177.56
B.1.349
B.1.36.1
B.1.1.10
B.1.1.207
B.1.177.83
B.1.177.41
B.1.160.7
B.1.1.448
B.1.1.220
B.1.319
B.1.1.159
B.1.453
B.1.160.23
C.38
B.1.1.517
AA.2
B.1.214.4
B.1.1.187
B.1.23
B.1.1.221
B.1.534
B.53
B.10
B.1.1.366
B.1.581
B.1.405
B.4.5
B.1.1.375
B.1.604
B.1.579
B.1.566
B.57
AZ.6
B.1.494
B.1.250
B.1.1.332
B.1.304
B.13
B.1.1.382
C.34
B.1.444
B.1.1.410
B.1.502
B.1.1.405
B.1.1.342
B.1.1.387
B.1.110.2
B.6.5
```

**Comment by ArtPoon** [comment]
Oh.  It didn't run *any* of these lineages:
```console
[covizu@BEVi covizu]$ grep "B.1.110.2" test-iss335.log
[covizu@BEVi covizu]$ grep "B.1.1.387" test-iss335.log
[covizu@BEVi covizu]$ grep "B.1.1.342" test-iss335.log
[covizu@BEVi covizu]$ grep "B.1.1.70" test-iss335.log
```

Is it the `None`?

**Comment by ArtPoon** [comment]
```python
>>> import json
>>> recoded = json.load(open('recoded.json'))
>>> rdata = recoded.get('None', None)
>>> len(rdata['labels'])
3688
```
Nothing seems too unusual about this key-value pair.

**Comment by ArtPoon** [comment]
Trying to reproduce problem with following test script:
```python
from mpi4py import MPI
from covizu.clustering import *
from covizu.utils.progress_utils import Callback
from Bio import Phylo

comm = MPI.COMM_WORLD
my_rank = comm.Get_rank()
nprocs = comm.Get_size()

binpath = 'rapidnj'
nboot = 100

# command-line execution
cb = Callback(my_rank=my_rank, nprocs=nprocs)

cb.callback("Loading JSON")
recoded = json.load(open('recoded.json'))
lineage = 'None'

cb.callback("Unpacking data")
union, labels, indexed = unpack_recoded(recoded, lineage, callback=cb.callback)

cb.callback("Building trees")
trees = [bootstrap(union, indexed, binpath, callback=cb.callback)
         for _ in range(nboot)]

Phylo.write(trees, file="test-none.nwk", format="newick")
```

```console
[covizu@BEVi covizu]$ module load openmpi/gnu
[covizu@BEVi covizu]$ mpirun --machinefile mfile python3 test-none.py
🏄 [0:00:00.000014][1/26] Loading JSON
...
🏄 [0:00:03.634278][19/26] Building trees
```

**Comment by ArtPoon** [comment]
Oops - that test script shouldn't be run as an MPI job.  I had 26 processes all doing the same thing!
```python
from covizu.clustering import *
from covizu.utils.progress_utils import Callback
from Bio import Phylo

binpath = 'rapidnj'
nboot = 100

# command-line execution
cb = Callback()

cb.callback("Loading JSON")
recoded = json.load(open('recoded.json'))
lineage = 'None'

cb.callback("Unpacking data")
union, labels, indexed = unpack_recoded(recoded, lineage, callback=cb.callback)

cb.callback("Building trees")
trees = []
for i in range(nboot):
    cb.callback("Starting {}".format(i))
    trees.append(bootstrap(union, indexed, binpath, callback=cb.callback)
    cb.callback("Finished {}".format(i))

Phylo.write(trees, file="test-none.nwk", format="newick")
```

**Comment by ArtPoon** [comment]
Okay, modified the progress monitoring to get a better sense of how long this will take:
```
🏄 [0:00:00.000013] Loading JSON
🏄 [0:00:02.545367] Unpacking data
🏄 [0:00:02.562471] Building trees
🏄 [0:00:02.562496] Starting 0
🏄 [0:02:14.158187] Finished 0
🏄 [0:02:14.158316] Starting 1
🏄 [0:04:29.513873] Finished 1
🏄 [0:04:29.513966] Starting 2
🏄 [0:06:42.905174] Finished 2
🏄 [0:06:42.905263] Starting 3
...
🏄 [1:04:08.643911] Starting 29
🏄 [1:06:24.119565] Finished 29
🏄 [1:06:24.119637] Starting 30
```
So about 137 seconds per tree, or almost 4 hours.  Since I've been terminating runs around 3 hours (since all other processes were done), I wasn't giving enough time for the `None` lineage to complete.  What is it about this lineage that consumes so much more time?  What if we just exclude it?

**Comment by ArtPoon** [comment]
Re-running from raw data:
```python
from batch import *
import json

args = parse_args()
cb = Callback()
cb.callback("Loading JSON data")

args.infile = "data/provision.2021-09-07T00:00:03.json.xz"
by_lineage = process_feed(args, cb.callback)
with open("test-iss335a.json", 'w') as handle:
    json.dump(by_lineage, handle)

#by_lineage = json.load(open("test-iss335.json"))

result = make_beadplots(by_lineage, args, cb.callback, t0=cb.t0.timestamp())
with open("clusters.iss335.json", 'w') as outfile:
    outfile.write(json.dumps(result))
```

**Comment by ArtPoon** [comment]
This script ran to completion successfully in 9 hours 10 minutes:
```
🏄 [1:03:52.277226] filtered 879651 problematic features
🏄 [1:03:52.277257]          851935 genomes with excess missing sites
🏄 [1:03:52.277266]          143779 genomes with excess divergence
🏄 [1:09:34.762383] Recoding features, compressing variants..
...
🏄 [3:40:33.495144][5/36] starting B.1.285
🏄 [3:40:35.070314] start B.1, 46191 entries
🏄 [3:40:56.824217][1/36] loading JSON
...
🏄 [8:14:17.195008][34/36] loading JSON
🏄 [8:22:14.587484] Parsing output files
🏄 [8:22:14.723551] Recording splits and branch lengths
...
🏄 [9:10:55.736371] Building consensus tree
```
