### ISSUE TITLE
opendata: CalledProcessError

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#336]
```
🏄 [5:09:15.209353][5/8] Reduced to 7720 variants; generating feature set union
Traceback (most recent call last):
  File "process.py", line 172, in <module>
    analyze_feed(handle, args, callback=cb.callback)
  File "process.py", line 131, in analyze_feed
    result = make_beadplots(by_lineage, args, callback, t0=t0.timestamp())
  File "/home/art/git/covizu/covizu/utils/batch_utils.py", line 136, in make_beadplots
    subprocess.check_call(mpirun+cmd)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpirun', '-np', '8', 'python3', 'covizu/clustering.py', 'data/by_lineage.json', 'B.1', '--mode', 'deep', '--max-variants', '5000', '--nboot', '100', '--outdir', 'data', '--binpath', 'rapidnj', '--timestamp', '1630002852.654368']' returned non-zero exit status 1.
```

**Comment by ArtPoon** [comment]
Appending `disown` seems to have done the trick:
```
nohup python3 process.py opendata.2021-08-25.xz --ft2bin fasttree2-mp -np 4 > issue336.log & disown
```

```
🏄 [14:57:56.857530] Building consensus tree
🏄 [14:58:06.243639] All done!
```
