### ISSUE TITLE
opendata: ValueError possibly due to an incorrect date

### ISSUE THREAD

**Issue by GopiGugan** [PoonLab/covizu#362]
```console
ggugan@Ala:~/covizu/covizu$ wget https://data.nextstrain.org/files/ncov/open/sequences.fasta.xz
ggugan@Ala:~/covizu/covizu$ wget https://data.nextstrain.org/files/ncov/open/metadata.tsv.gz
ggugan@Ala:~/covizu/covizu$ nohup python3 convert.py sequences.fasta.xz metadata.tsv.gz --xz --mgz --region region --division division --outfile opendata.json.xz &
ggugan@Ala:~/covizu/covizu$ cat nohup.out 
Traceback (most recent call last):
  File "convert.py", line 214, in <module>
    for record in feed:
  File "convert.py", line 89, in combine
    dt = seq_utils.fromisoformat(coldate)
  File "/home/ggugan/covizu/covizu/covizu/utils/seq_utils.py", line 125, in fromisoformat
    return date(year, month, day)
ValueError: month must be in 1..12
```

**Comment by ArtPoon** [comment]
Can you catch the exception so that we can determine which record is causing this issue?  Then we can report it to the Nextstrain team

**Comment by ArtPoon** [comment]
Hm, that's in the original Genbank record.  We're have to write a catch for that edge case.
