### ISSUE TITLE
Pipeline crash 2021-11-27 (KeyError)

### ISSUE THREAD

**Issue by GopiGugan** [PoonLab/covizu#370]
```console
[covizu@BEVi ~]$ tail -n300 batch.log
...
🏄 [11:11:06.295840][6/44] ERROR: JSON did not contain lineage AY.120
🏄 [11:11:06.874543][2/44] ERROR: JSON did not contain lineage AY.120
...
🏄 [11:31:24.923533][4/44] ERROR: JSON did not contain lineage AY.122.1
🏄 [11:31:25.436247][0/44] ERROR: JSON did not contain lineage AY.122.1
...
🏄 [11:54:26.532242][1/44] ERROR: JSON did not contain lineage AY.113
🏄 [11:54:26.536055][3/44] ERROR: JSON did not contain lineage AY.113
...
🏄 [12:39:20.855585][1/44] ERROR: JSON did not contain lineage AY.119
🏄 [12:39:20.863214][3/44] ERROR: JSON did not contain lineage AY.119
...
🏄 [14:28:51.531921][1/44] ERROR: JSON did not contain lineage AY.118
🏄 [14:28:51.535711][3/44] ERROR: JSON did not contain lineage AY.118
...
🏄 [14:28:55.577776] start AY.7.1, 6457 entries
🏄 [14:30:48.010615] start AY.100, 14710 entries
🏄 [14:40:56.259644] start AY.99.2, 7751 entries
🏄 [14:48:17.927035] Parsing output files
Traceback (most recent call last):
  File "batch.py", line 158, in <module>
    result = make_beadplots(by_lineage, args, cb.callback, t0=cb.t0.timestamp())
  File "/home/covizu/covizu/covizu/utils/batch_utils.py", line 201, in make_beadplots
    ctree = beadplot.annotate_tree(ctree, label_dict)
  File "/home/covizu/covizu/covizu/beadplot.py", line 113, in annotate_tree
    tip.labels = label_dict[tip.name]
KeyError: '14'

```

**Comment by ArtPoon** [comment]
```
[covizu@BEVi covizu]$ ls -lt recoded.json 
-rw-rw-r-- 1 covizu covizu 321539458 Nov 27 03:30 recoded.json
[covizu@BEVi covizu]$ grep -c AY\.120 recoded.json 
0
[covizu@BEVi covizu]$ grep -c AY\.1 recoded.json 
1
[covizu@BEVi covizu]$ grep -c AY\.12 recoded.json 
1
[covizu@BEVi covizu]$ ls -l data/AY.12*
-rw-rw-r-- 1 covizu covizu  3279124 Nov 26 20:27 data/AY.120.1.nwk
-rw-rw-r-- 1 covizu covizu  1153385 Nov 26 20:52 data/AY.120.2.1.nwk
-rw-rw-r-- 1 covizu covizu   511330 Nov 26 20:08 data/AY.120.2.nwk
-rw-rw-r-- 1 covizu covizu 11395204 Nov 25 11:15 data/AY.120.nwk
-rw-rw-r-- 1 covizu covizu  7579693 Nov 26 21:07 data/AY.121.nwk
-rw-rw-r-- 1 covizu covizu  7606497 Nov 25 11:39 data/AY.122.1.nwk
-rw-rw-r-- 1 covizu covizu 11406591 Nov 27 02:44 data/AY.122.nwk
-rw-rw-r-- 1 covizu covizu  1018846 Sep  7 13:38 data/AY.12.labels.csv
-rw-rw-r-- 1 covizu covizu  1838105 Nov 27 04:50 data/AY.12.nwk
```
@GopiGugan is the modification date for `AY.120.nwk` after you started the pipeline run?

**Comment by GopiGugan** [comment]
No, I started the run Nov 26 at ~17:00

**Comment by ArtPoon** [comment]
Yeah I thought so.  Ok, so `AY.120` is not in `recoded.json`, but the script called for it.  Is this because of a stale Newick file in `/data`?

**Comment by ArtPoon** [comment]
@GopiGugan - the pipeline is running right now.  Could it be that it restarted with new data and overwrote the `recoded.json` file with new lineages?

**Comment by GopiGugan** [comment]
> Yeah I thought so. Ok, so `AY.120` is not in `recoded.json`, but the script called for it. Is this because of a stale Newick file in `/data`?

But shouldn't it have still been written to `recoded.json`? As long as its in `by_lineage` it should have written an entry into `recoded.json` because `clustering.recode_features()` didn't throw an error, right?

https://github.com/PoonLab/covizu/blob/eac6bcd819cee3b3cd1a6a4f4d1943868ba98d59/covizu/utils/batch_utils.py#L111-L122



> @GopiGugan - the pipeline is running right now. Could it be that it restarted with new data and overwrote the `recoded.json` file with new lineages?

No the pipeline isn't running right now

**Comment by ArtPoon** [comment]
@GopiGugan did you not comment out the cron job?
Anyhow I guess we'll have to let the current job run to completion and hope for the best...

**Comment by GopiGugan** [comment]
> @GopiGugan did you not comment out the cron job? Anyhow I guess we'll have to let the current job run to completion and hope for the best...

The cron job was commented out. Not sure how another run started

**Comment by GopiGugan** [comment]
Rerun of the pipeline was successful:

```console
[covizu@BEVi ~]$ tail -n10 batch.log
🏄 [14:39:42.739304] start AY.98.1, 35946 entries
🏄 [14:48:42.196173] start AY.23, 9439 entries
🏄 [14:57:49.412201] start AY.34, 6079 entries
🏄 [15:04:32.666311] start AY.3.1, 6754 entries
🏄 [15:12:26.279439] start AY.118, 9734 entries
🏄 [15:21:40.063090] start AY.7.1, 6485 entries
🏄 [15:23:17.810729] start AY.100, 14798 entries
🏄 [15:32:54.708516] start AY.99.2, 7788 entries
🏄 [15:41:28.672322] Parsing output files
🏄 [17:35:56.500831] All done!
```

**Comment by ArtPoon** [comment]
awesome thanks

**Comment by ArtPoon** [comment]
@GopiGugan to close after next run if it is clean

**Comment by GopiGugan** [comment]
Latest run was successful:

```console
[covizu@BEVi ~]$ tail -10 batch.log
🏄 [14:52:53.133206] start AY.98.1, 36063 entries
🏄 [15:02:06.425433] start AY.23, 9470 entries
🏄 [15:11:21.979173] start AY.34, 6221 entries
🏄 [15:18:15.762847] start AY.3.1, 6851 entries
🏄 [15:26:23.668736] start AY.118, 9850 entries
🏄 [15:35:23.972986] start AY.7.1, 6494 entries
🏄 [15:37:02.856209] start AY.100, 15087 entries
🏄 [15:46:48.222162] start AY.99.2, 7905 entries
🏄 [15:55:26.649373] Parsing output files
🏄 [17:50:40.641383] All done!
```

**Comment by ArtPoon** [comment]
Run time's pushing 18 hours...
