### ISSUE TITLE
Wrong install location for submodule files

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#391]
```console
Traceback (most recent call last):
  File "covizu/utils/gisaid_utils.py", line 358, in <module>
    by_lineage = sort_by_lineage(filtered, callback=cb.callback)
  File "covizu/utils/gisaid_utils.py", line 237, in sort_by_lineage
    for i, record in enumerate(records):
  File "covizu/utils/gisaid_utils.py", line 176, in filter_problematic
    mask = load_vcf(vcf_file)
  File "/usr/local/lib/python3.6/dist-packages/covizu-0.3-py3.6.egg/covizu/utils/seq_utils.py", line 238, in load_vcf
    vcf = open(vcf_file)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/covizu-0.3-py3.6.egg/covizu/data/ProblematicSites_SARS-CoV2/problematic_sites_sarsCov2.vcf'
art@orolo:~/git/covizu$ ls /usr/local/lib/python3.6/dist-packages/covizu-0.3-py3.6.egg/covizu/data/
lineages.csv  MT291829.fa   problematic_sites_sarsCov2.vcf
LR757995.fa   NC_045512.fa
```

**Comment by GopiGugan** [comment]
I believe the following should fix this issue. This just assumes that the submodule has already been initialized by the user prior to running `setup.py`:

```diff
diff --git a/covizu/minimap2.py b/covizu/minimap2.py
index 9219eba..be126a8 100644
--- a/covizu/minimap2.py
+++ b/covizu/minimap2.py
@@ -240,7 +240,7 @@ def parse_args():
     if '.egg' in path:
         import pkg_resources
         ref_file = pkg_resources.resource_filename('covizu', 'data/NC_045512.fa')
-        vcf_file = pkg_resources.resource_filename('covizu', "data/ProblematicSites_SARS-CoV2/problematic_sites_sarsCov2.vcf")
+        vcf_file = pkg_resources.resource_filename('covizu', "data/problematic_sites_sarsCov2.vcf")
     else:
         ref_file = os.path.join(path, "data", "NC_045512.fa")
         vcf_file = os.path.join(path, "data/ProblematicSites_SARS-CoV2", "problematic_sites_sarsCov2.vcf")
diff --git a/setup.py b/setup.py
index 1babd37..4039de7 100644
--- a/setup.py
+++ b/setup.py
@@ -20,6 +20,7 @@ setuptools.setup(
         "Operating System :: OS Independent",
     ],
     package_data={'covizu': [
-        'data/NC_045512.fa'
+        'data/NC_045512.fa',
+        'data/ProblematicSites_SARS-CoV2/problematic_sites_sarsCov2.vcf'
     ]}
 )
```
