### ISSUE TITLE
Issues installing development environment

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#406]
@SyouTono242 to document

**Comment by SyouTono242** [comment]
I had the following problems installing CoVizu by cloning the repository:

I followed the steps listed in [INSTALL.md](https://github.com/PoonLab/covizu/blob/master/INSTALL.md):
```
git clone https://github.com/PoonLab/covizu
git submodule init
git submodule update
sudo python3 setup.py install
```
Then I downloaded [dbstats.json](https://filogeneti.ca/CoVizu/data/dbstats.json) and added it into the `/data` folder, so now there are these files
```
covizu:~$ ls data 
clusters.json		dbstats.json		timetree.nwk
countries.json		mut_annotations.json
```

However when I try to run the server, I'm still getting this error message:
```
covizu:~$ bash run-server.sh

> covizu@1.0.0 start
> node server.js

/CoVizu/covizu/server/parseCluster.js:370
    tips[root_idx].max_ndiffs = tip_stats.max_ndiffs;
                                          ^

TypeError: Cannot read property 'max_ndiffs' of undefined
    at map_clusters_to_tips (/CoVizu/covizu/server/parseCluster.js:370:43)
    at Object.<anonymous> (/CoVizu/covizu/server.js:31:14)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by GopiGugan** [comment]
@SyouTono242 I was not able to reproduce this in the `dev` branch.

Can you try downloading [clusters.json](https://filogeneti.ca/covizu/data/clusters.json), [dbstats.json](https://filogeneti.ca/covizu/data/dbstats.json) and [timetree.nwk](https://filogeneti.ca/covizu/data/timetree.nwk) again and replace these files in your `/data` directory?

**Comment by SyouTono242** [comment]
@GopiGugan Thanks for the help! 

Downloading them does seem to fix the TypeError problem. I now have
```
data:~$ ls -l
total 394696
-rw-------@ 1 shaoyiran  staff  200942036 14 Jun 00:51 clusters.json
-rw-------@ 1 shaoyiran  staff       7381  7 Jun 00:02 countries.json
-rw-------@ 1 shaoyiran  staff     985136 14 Jun 00:52 dbstats.json
-rw-------@ 1 shaoyiran  staff      98899  7 Jun 00:02 mut_annotations.json
-rw-------@ 1 shaoyiran  staff      39157 14 Jun 00:52 timetree.nwk
```

However I'm not 100% sure whether the server is running right and/or how I can open the local website. `bash run-server.sh` and `npm start` are both giving me this:
```
covizu:~$ bash run-server.sh

> covizu@1.0.0 start
> node server.js

```
but `http://localhost:8001/` is just showing me a `ERR_CONNECTION_REFUSED` error. Is that an intended behaviour? Am I missing anything from the instructions?
