### ISSUE TITLE
Pipeline failed 2022-06-25

### ISSUE THREAD

**Issue by GopiGugan** [PoonLab/covizu#408]
```bash
🏄 [10:21:44.233132][2/44] starting XU
bpsh: Child process exit abnormally.
--------------------------------------------------------------------------
ORTE has lost communication with a remote daemon.

  HNP daemon   : [[10831,0],0] on node BEVi
  Remote daemon: [[10831,0],1] on node n0

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "batch.py", line 157, in <module>
    result = make_beadplots(by_lineage, args, cb.callback, t0=cb.t0.timestamp())
  File "/home/covizu/covizu/covizu/utils/batch_utils.py", line 181, in make_beadplots
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mpirun', '--machinefile', 'mfile', 'python3', 'covizu/clustering.py', 'recoded.json', 'minor_lineages.txt', '--mode', 'flat', '--max-variants', '5000', '--nboot', '100', '--outdir', 'data/', '--binpath', 'rapidnj', '--timestamp', '1656176538.048786']' returned non-zero exit status 205.
```

**Comment by GopiGugan** [comment]
Similar occurrences in #350 #289

**Comment by ArtPoon** [comment]
Only thing that comes to mind is that another user was running a pile of processes on `n0`

**Comment by ArtPoon** [comment]
I dug through the `/var/log/messages*` files and found an error message that could be associated with this:
```
Jun 25 23:28:22 BEVi beoserv: NODESTATUS 0 dhcp-beoboot Assign 172.16.128.10 for BeoBoot from A4:BF:01:12:2D:D3 A4:BF:01:12:2D:D4
Jun 25 23:28:27 172.16.128.10  [   29.914705] ixgbe 0000:03:00.0 eth0: NIC Link is Up 1 Gbps, Flow Control: None
Jun 25 23:28:27 172.16.128.10  [   29.915486] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Jun 25 23:28:28 172.16.128.10  [   30.860008] task_packer: Version 7.0.0-x86-64
Jun 25 23:28:28 172.16.128.10  [   30.860279] task_packer: (c) 2006-2018 Penguin Computing, Inc.
Jun 25 23:28:28 172.16.128.10  [   30.864784] bproc: Beowulf Distributed Process Space Version 5.0.0
Jun 25 23:28:28 172.16.128.10  [   30.865052] bproc: (C) 1999-2003 Erik Hendriks <erik@hendriks.cx>
Jun 25 23:28:28 172.16.128.10  [   30.865315] bproc: (C) 1999-2018 Penguin Computing, Inc.
Jun 25 23:28:28 172.16.128.10  bpslave: manager daemon pid:420
Jun 25 23:28:28 172.16.128.10  bpslave-iod: I/O daemon pid:421
Jun 25 23:28:28 172.16.128.10  bpslave-0: worker daemon pid:422
Jun 25 23:28:28 172.16.128.10  bpslave-0: filecache daemon pid:423
Jun 25 23:28:28 BEVi bpmaster-main: replacing slave 0
Jun 25 23:28:28 172.16.128.10  bpslave-0: Set ping timeout to 300 seconds
Jun 25 23:28:28 172.16.128.10  [   31.179221] task_packer_load_task_helper_thread:1495 Need to 'daemonize'?
Jun 25 23:28:30 172.16.128.10  [   33.028073] loop: module loaded
Jun 25 23:28:30 172.16.128.10  [   33.233063] squashfs: version 4.0 (2009/01/31) Phillip Lougher
Jun 25 23:28:30 172.16.128.10  [   33.490720] Key type dns_resolver registered
Jun 25 23:28:31 172.16.128.10  [   33.527878] NFS: Registering the id_resolver key type
Jun 25 23:28:31 172.16.128.10  [   33.528152] Key type id_resolver registered
Jun 25 23:28:31 172.16.128.10  [   33.528403] Key type id_legacy registered
Jun 25 23:28:51 n0 sendstats: /usr/sbin/sendstats version 0.9.4
Jun 25 23:28:52 n0 rpc.statd[93113]: Version 1.3.0 starting
Jun 25 23:28:52 n0 sm-notify[93114]: Version 1.3.0 starting
Jun 25 23:28:52 n0 rpc.statd[93113]: Initializing NSM state
Jun 25 23:28:52 n0 [   54.987509] IPMI message handler: version 39.2
Jun 25 23:28:52 n0 [   54.995720] ipmi device interface
Jun 25 23:28:52 n0 [   55.027844] ipmi_si: IPMI System Interface driver
Jun 25 23:28:52 n0 [   55.028127] ipmi_si dmi-ipmi-si.0: probing via SMBIOS
Jun 25 23:28:52 n0 [   55.028391] ipmi_platform: ipmi_si: SMBIOS: io 0xca2 regsize 1 spacing 1 irq 0
Jun 25 23:28:52 n0 [   55.028851] ipmi_si: Adding SMBIOS-specified kcs state machine
Jun 25 23:28:52 n0 [   55.029270] ipmi_si: Trying SMBIOS-specified kcs state machine at i/o address 0xca2, slave address 0x20, irq 0
Jun 25 23:28:52 n0 [   55.086987] ipmi_si dmi-ipmi-si.0: Found new BMC (man_id: 0x000157, prod_id: 0x006f, dev_id: 0x21)
Jun 25 23:28:52 n0 [   55.160447] ipmi_si dmi-ipmi-si.0: IPMI kcs interface initialized
Jun 25 23:28:54 n0 slurmd[93416]: error: Domain socket directory /var/spool/slurmd: No such file or directory
Jun 25 23:28:54 n0 slurmd[93416]: error: xcpuinfo_hwloc_topo_load: failed (load will be required after read failures).
Jun 25 23:28:54 n0 slurmd[93450]: slurmd version 20.11.5 started
Jun 25 23:28:54 n0 slurmd[93450]: slurmd started on Sat, 25 Jun 2022 23:28:54 -0400
Jun 25 23:28:54 n0 slurmd[93450]: CPUs=56 Boards=1 Sockets=2 Cores=14 Threads=2 Memory=56262 TmpDisk=28131 Uptime=57 CPUSpecList=(null) FeaturesAvail=(null) FeaturesActive=(null)
```

**Comment by ArtPoon** [comment]
I'm guessing the node ran out of RAM and since it is diskless there was no swap, so it crashed and rebooted back into the cluster network.

**Comment by ArtPoon** [comment]
Only thing I can think of is to reduce the number of slots associated with `n0`

**Comment by ArtPoon** [comment]
`n0` is slated for replacement with a new server
