### ISSUE TITLE
Substring search seems to be broken

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#411]
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'attributes')
    at main_search (search.js:166:57)
    at async wrap_search (search.js:102:5)
    at async HTMLInputElement.<anonymous> (covizu.js:340:7)
```
Steps to reproduce:
1. Load page
2. Search for `BE.1` and click on highlighted `rect` to load beadplot (see #410 )
3. Do a second search for `ON-PHL`.  Page will be stuck.  JS console will throw the above error.

**Comment by ArtPoon** [comment]
close upon merging PR #414
