### ISSUE TITLE
DOMException: illegal character?

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#421]
```
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '.lines#Cote_d'Ivoire-IPCI-cv430' is not a valid selector.
    at Object.select (https://filogeneti.ca/covizu/js/d3.js:1689:34)
    at SVGLineElement.<anonymous> (https://filogeneti.ca/covizu/js/beadplot.js:774:30)
    at SVGLineElement.<anonymous> (https://filogeneti.ca/covizu/js/d3.js:1526:16)
```

**Comment by ArtPoon** [comment]
I think we have to escape the apostrophe?

**Comment by ArtPoon** [comment]
close on next PR
