### ISSUE TITLE
Iteration through search results is broken

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#435]
To reproduce:
* search for "Canada" and limit collection dates to last three weeks (2022-11-16 as of today)
* when search results are rendered, use "Next" button to click through highlighted beads
* iteration breaks after attempting to step from 3rd to 4th result

Snippet from console:
```js
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'scrollIntoView')
    at select_working_bead (search.js:443:16)
    at HTMLButtonElement.<anonymous> (covizu.js:482:9)
/api/cid/EPI_ISL_15930625:1          Failed to load resource: the server responded with a status of 503 (Service Unavailable)
/api/cid/EPI_ISL_15930384:1          Failed to load resource: the server responded with a status of 503 (Service Unavailable)
search.js:443 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'scrollIntoView')
    at select_working_bead (search.js:443:16)
    at HTMLButtonElement.<anonymous> (covizu.js:482:9)
style.css:1          Failed to load resource: the server responded with a status of 503 (Service Unavailable)
gisaid.css:1          Failed to load resource: the server responded with a status of 503 (Service Unavailable)
```

**Comment by ArtPoon** [comment]
I wrote the issue shortly after encountering the error, so that timestamp should be pretty close.

**Comment by GopiGugan** [comment]
> New data files were uploaded to the web server at ~9 am today.

I was looking at the wrong time before. New files were uploaded at 13:31 today, which was around the time the issue was opened

**Comment by ArtPoon** [comment]
Ok then that's a likely explanation.  Would it be possible to have a 503 response trigger a pop-up for the user to know that the server is being updated and is temporarily unavailable?
