### ISSUE TITLE
Local install error, missing DATA_FOLDER

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#443]
On running `npm start`, node threw this exception:
```
.env is missing HTTP_PORT. Defaulting to 8001
/home/art/git/covizu/config.js:50
    throw new Error('.env is missing DATA_FOLDER env variable')
```

**Comment by GopiGugan** [comment]
@nav-mohan recent change requires a `.env.dev` file with the following contents:
```
HTTP_PORT='8001'
NODE_ENV='DEV'
DATA_FOLDER='data'
```
I believe it may be easier if we have default values set when there isn't a `.env.dev` file present for development

**Comment by ArtPoon** [comment]
Ok I created this file and ran into a different error:
```console
art@orolo:~/git/covizu$ NODE_ENV='DEV' node server.js
/home/art/git/covizu/server/parseCluster.js:247
      var nodelist = unique(cluster.edges.map(x => x.slice(0, 2)).flat());
                                                                  ^

TypeError: cluster.edges.map(...).flat is not a function
    at parse_clusters (/home/art/git/covizu/server/parseCluster.js:247:67)
    at Object.<anonymous> (/home/art/git/covizu/server.js:23:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by ArtPoon** [comment]
Got server running locally now.  Need to update installation instructions.
