### ISSUE TITLE
cron is not running pipeline

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#71]
@ewong347 are you still triggering downloads manually?  otherwise the `covizu.sh` script should be running the whole analysis to update the JSON files.

**Comment by ArtPoon** [comment]
I've been resisting the impulse to regularly update the JSON data files on the repo, but I guess if we are going to publish the page on GitHub then we'll have to do it.

Alternatively if we publish on `filogeneti.ca` then we can generate the JSONs on Langley and sftp transfer them to the webserver.  
* `filogeneti.ca` would pull front-end code from the master branch.  
* Langley pulls back-end code from the master branch.  
* FTP transfer JSONs from Langley to `filogeneti.ca`
* We continue to push changes to dev and then do a pull request merge into master.

**Comment by ArtPoon** [comment]
Note, I don't want sequence data exposed on `filogeneti.ca` where it is browsable.

**Comment by ewong347** [comment]
See pull request, crontab is running just the autobot script, i'd like to merge refactor with master so we can start running covizu.sh

**Comment by ArtPoon** [comment]
btw we're having serious permissions problem on Langley

**Comment by ArtPoon** [comment]
```R
writing JSON file
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
Calls: write -> cat -> file
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file 'data/clusters.json': Permission denied
Execution halted
Traceback (most recent call last):
  File "scripts/treetime.py", line 196, in <module>
    fasta = filter_fasta(args.fasta, args.json, cutoff=args.mincount)
  File "scripts/treetime.py", line 38, in filter_fasta
    result.update({fasta[accn]['label']: fasta[accn]['sequence']})
KeyError: 'EPI_ISL_427722'
```

```console
art@Langley:/home/covid/covizu$ ls -l data
total 5029300
-rw-rw-r-- 1 art      covid       5110092 Jun  5 14:00 ancestral_sequences.fasta
drwxrwxrwx 2 root     covid          4096 Jun  9 09:48 baseline
-rw-rw-r-- 1 ewong347 ewong347    5590327 Jun 11 17:13 clusters.json
```

**Comment by ewong347** [comment]
I think the issue was that we created covid as a home folder on langley so all the permissions are wacky. Can we just do a blanket permissions change on all files that need to be modified/executed through the pipeline? Another option would be to run scripts as sudo through crontab

**Comment by ArtPoon** [comment]
I've done `chgrp -R` and `chmod -R` but files still reverted to other owners.

**Comment by ArtPoon** [comment]
I'd rather not require us to do this stuff via `sudo`.

**Comment by ArtPoon** [comment]
Maybe we should move everything to `/usr/local/share`

**Comment by ArtPoon** [comment]
Merged `dev` and `refactor-bots` into `master` branch @ewong347

**Comment by ArtPoon** [comment]
@ewong347 can you switch to `master` branch on Langley please and start running `covizu.sh`?

**Comment by ArtPoon** [comment]
Commited local changes to `dev` on Langley and checked out `master`
Running pipeline crashes:
```console
art@Langley:/home/covid/covizu$ ./covizu.sh
Discarded 34 non-human sequences.
Discarded 2579 problematic sequences with prop N > 0.05.
Discarded 367 sequences of length < 29000
Discarded 632 sequences with duplicate accession numbers
Discarded 1229 sequences with mangled headers
All sequences must have the same length (29903), but sequence 'hCoV-19/Spain/COV002720/2020|EPI_ISL_467273|2020-04-07' had length 30357Filter sequences that are too distant
Traceback (most recent call last):
  File "scripts/variants.py", line 167, in <module>
    G = clustering(args.tn93, callback=callback)
  File "scripts/variants.py", line 46, in clustering
    _ = next(handle)
StopIteration
```

**Comment by ArtPoon** [comment]
Duplicate records in `gisaid-aligned.fa`:
```console
art@Langley:/home/covid/covizu$ grep EPI_ISL_467273 data/gisaid-aligned.fa 
>hCoV-19/Spain/COV002720/2020|EPI_ISL_467273|2020-04-07
>hCoV-19/Spain/COV002720/2020|EPI_ISL_467273|2020-04-07
```

**Comment by ArtPoon** [comment]
The first record seems to have a line break in it so there are two lines containing sequence following the header line.  I have made a backup of `gisaid-aligned.fa` to `gisaid-aligned.2020-06-13.bak` and deleted this first record.

Next I am going to run a screen for other duplicate headers.
```python
import gotoh2
>>> for h, s in fasta:
...   if h not in d:
...     d.update({h: None})
...   else:
...     print(h)
... 
hCoV-19/Spain/COV003700/2020|EPI_ISL_467259|2020-04-02
hCoV-19/Spain/COV003676/2020|EPI_ISL_467260|2020-04-02
hCoV-19/Spain/COV003693/2020|EPI_ISL_467261|2020-04-02
hCoV-19/Spain/COV002749/2020|EPI_ISL_467262|2020-04-14
hCoV-19/Spain/COV002714/2020|EPI_ISL_467263|2020-04-07
hCoV-19/Spain/COV002757/2020|EPI_ISL_467264|2020-04-07
hCoV-19/Spain/COV002745/2020|EPI_ISL_467265|2020-04-13
hCoV-19/Spain/COV002726/2020|EPI_ISL_467266|2020-04-15
hCoV-19/Spain/COV002756/2020|EPI_ISL_467267|2020-04-13
hCoV-19/Spain/COV002743/2020|EPI_ISL_467268|2020-04-13
hCoV-19/Spain/COV002748/2020|EPI_ISL_467269|2020-04-13
hCoV-19/Spain/COV002758/2020|EPI_ISL_467270|2020-04-07
hCoV-19/Spain/COV002716/2020|EPI_ISL_467271|2020-04-08
hCoV-19/Spain/COV002730/2020|EPI_ISL_467272|2020-04-13
hCoV-19/Spain/COV002737/2020|EPI_ISL_467274|2020-04-13
hCoV-19/Spain/COV002717/2020|EPI_ISL_467275|2020-04-07
hCoV-19/Spain/COV002727/2020|EPI_ISL_467276|2020-04-15
hCoV-19/Spain/COV002753/2020|EPI_ISL_467277|2020-04-13
hCoV-19/Spain/COV002710/2020|EPI_ISL_467278|2020-04-07
hCoV-19/Spain/COV002718/2020|EPI_ISL_467279|2020-04-07
hCoV-19/Spain/COV002740/2020|EPI_ISL_467280|2020-04-15
hCoV-19/Spain/COV002731/2020|EPI_ISL_467281|2020-04-14
hCoV-19/Spain/COV002750/2020|EPI_ISL_467282|2020-04-13
hCoV-19/Spain/COV002732/2020|EPI_ISL_467283|2020-04-13
hCoV-19/Spain/COV002755/2020|EPI_ISL_467284|2020-04-13
hCoV-19/Spain/COV002734/2020|EPI_ISL_467285|2020-04-13
hCoV-19/Spain/COV002711/2020|EPI_ISL_467286|2020-04-07
hCoV-19/Spain/COV002722/2020|EPI_ISL_467287|2020-04-07
hCoV-19/Spain/COV002754/2020|EPI_ISL_467288|2020-04-13
hCoV-19/Spain/COV002733/2020|EPI_ISL_467289|2020-04-13
```

**Comment by ArtPoon** [comment]
```python
>>> outfile = open('data/issue71.fa', 'w')
>>> fasta = gotoh2.iter_fasta(open('data/gisaid-aligned.fa'))
>>> d = {}
>>> for h, s in fasta:
>>>   if h not in d:
>>>     outfile.write('>{}\n{}\n'.format(h, s))
>>>     d.update({h: None})
>>>   else:
>>>     print(h)
>>> outfile.close()
```

```console
art@Langley:/home/covid/covizu$ wc -l data/*.fa
     77350 data/gisaid-aligned.fa
     67670 data/gisaid-filtered.fa
     77290 data/issue71.fa
       431 data/NC_045512.fa
     24078 data/variants.fa
    246819 total
```

**Comment by ArtPoon** [comment]
Pipeline running normally now:
```console
art@Langley:/home/covid/covizu$ ./covizu.sh 
Discarded 34 non-human sequences.
Discarded 2579 problematic sequences with prop N > 0.05.
Discarded 367 sequences of length < 29000
Discarded 601 sequences with duplicate accession numbers
Discarded 1229 sequences with mangled headers
Read 33835 sequences of length 29903
Will perform 572386695 pairwise distance calculations
Progress:    1.54% (  331958 links found,     2.67e+05 evals/sec)
```

**Comment by ArtPoon** [comment]
Normal run
